decision(in_force, v1, no_consent_needed, basis(['ePrivacy Art. 5(3)'])).
decision(in_force, v2, ask_for_consent, basis(['ePrivacy Art. 5(3)'])).
decision(in_force, v3, ask_for_consent, basis(['ePrivacy Art. 5(3)'])).
decision(in_force, v4, ask_for_consent, basis(['ePrivacy Art. 5(3)'])).
decision(in_force, v5, ask_for_consent, basis(['ePrivacy Art. 5(3)'])).
decision(in_force, v6, ask_for_consent, basis(['ePrivacy Art. 5(3)'])).
decision(in_force, v7, ask_for_consent, basis(['ePrivacy Art. 5(3)'])).
decision(in_force, b1, notify(authority(none), people(none)), basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])).
decision(in_force, b2, notify(authority(within_hours(72)), people(none)), basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])).
decision(in_force, b3, notify(authority(within_hours(72)), people(without_undue_delay)), basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])).
decision(omnibus_proposal, v1, no_consent_needed, basis(['GDPR Art. 88a(3)(b)'])).
decision(omnibus_proposal, v2, no_consent_needed, basis(['GDPR Art. 88a(3)(c)'])).
decision(omnibus_proposal, v3, ask_for_consent, basis(['GDPR Art. 88a(1)'])).
decision(omnibus_proposal, v4, refused_by_signal, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])).
decision(omnibus_proposal, v5, ask_for_consent, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88b(3)'])).
decision(omnibus_proposal, v6, do_not_ask_again, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])).
decision(omnibus_proposal, v7, ask_for_consent, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])).
decision(omnibus_proposal, b1, notify(authority(none), people(none)), basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])).
decision(omnibus_proposal, b2, notify(authority(none), people(none)), basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])).
decision(omnibus_proposal, b3, notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)), basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])).
changed(v2, from(ask_for_consent), to(no_consent_needed), because(['GDPR Art. 88a(3)(c)'])).
changed(v4, from(ask_for_consent), to(refused_by_signal), because(['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])).
changed(v6, from(ask_for_consent), to(do_not_ask_again), because(['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])).
changed(b2, from(notify(authority(within_hours(72)), people(none))), to(notify(authority(none), people(none))), because(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])).
changed(b3, from(notify(authority(within_hours(72)), people(without_undue_delay))), to(notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay))), because(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])).

clause(1, regime(in_force), true).
clause(2, regime(omnibus_proposal), true).
clause(3, site(shop, media_service(no)), true).
clause(4, site(news, media_service(yes)), true).
clause(5, access(cart, purpose(requested_service), aggregated(no), own_use(yes)), true).
clause(6, access(stats, purpose(audience_measurement), aggregated(yes), own_use(yes)), true).
clause(7, access(vendor_stats, purpose(audience_measurement), aggregated(yes), own_use(no)), true).
clause(8, access(ads, purpose(advertising), aggregated(no), own_use(no)), true).
clause(9, visit(v1, shop, cart, first_visit), true).
clause(10, visit(v2, shop, stats, first_visit), true).
clause(11, visit(v3, shop, vendor_stats, first_visit), true).
clause(12, visit(v4, shop, ads, browser_signal(refuse)), true).
clause(13, visit(v5, news, ads, browser_signal(refuse)), true).
clause(14, visit(v6, shop, ads, refused(days_ago(60))), true).
clause(15, visit(v7, shop, ads, refused(days_ago(200))), true).
clause(16, breach(b1, 'encrypted laptop lost, key safe', risk(unlikely)), true).
clause(17, breach(b2, 'customer e-mail addresses exposed', risk(some)), true).
clause(18, breach(b3, 'patient records exposed', risk(high)), true).
clause(19, kind(var('A'), requested_service), access(var('A'), purpose(requested_service), var('__anon0'), var('__anon1'))).
clause(20, kind(var('A'), own_audience_measurement), access(var('A'), purpose(audience_measurement), aggregated(yes), own_use(yes))).
clause(21, kind(var('A'), shared_measurement), access(var('A'), purpose(audience_measurement), var('__anon2'), own_use(no))).
clause(22, kind(var('A'), advertising), access(var('A'), purpose(advertising), var('__anon3'), var('__anon4'))).
clause(23, consent(in_force, requested_service, not_needed, 'ePrivacy Art. 5(3)'), true).
clause(24, consent(in_force, own_audience_measurement, needed, 'ePrivacy Art. 5(3)'), true).
clause(25, consent(in_force, shared_measurement, needed, 'ePrivacy Art. 5(3)'), true).
clause(26, consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), true).
clause(27, consent(omnibus_proposal, requested_service, not_needed, 'GDPR Art. 88a(3)(b)'), true).
clause(28, consent(omnibus_proposal, own_audience_measurement, not_needed, 'GDPR Art. 88a(3)(c)'), true).
clause(29, consent(omnibus_proposal, shared_measurement, needed, 'GDPR Art. 88a(1)'), true).
clause(30, consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), true).
clause(31, ask(in_force, var('__anon5'), var('__anon6'), ask_for_consent, 'ePrivacy Art. 5(3)'), true).
clause(32, ask(omnibus_proposal, var('__anon7'), first_visit, ask_for_consent, 'GDPR Art. 88a(1)'), true).
clause(33, ask(omnibus_proposal, media_service(no), browser_signal(refuse), refused_by_signal, 'GDPR Art. 88b(1)-(2)'), true).
clause(34, ask(omnibus_proposal, media_service(yes), browser_signal(refuse), ask_for_consent, 'GDPR Art. 88b(3)'), true).
clause(35, ask(omnibus_proposal, var('__anon8'), refused(days_ago(var('D'))), do_not_ask_again, 'GDPR Art. 88a(4)(c)'), <(var('D'), 183)).
clause(36, ask(omnibus_proposal, var('__anon9'), refused(days_ago(var('D'))), ask_for_consent, 'GDPR Art. 88a(4)(c)'), >=(var('D'), 183)).
clause(37, authority(in_force, risk(unlikely), none, 'GDPR Art. 33(1)'), true).
clause(38, authority(in_force, risk(some), within_hours(72), 'GDPR Art. 33(1)'), true).
clause(39, authority(in_force, risk(high), within_hours(72), 'GDPR Art. 33(1)'), true).
clause(40, authority(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 33(1) as amended'), true).
clause(41, authority(omnibus_proposal, risk(some), none, 'GDPR Art. 33(1) as amended'), true).
clause(42, authority(omnibus_proposal, risk(high), within_hours_via_single_entry_point(96), 'GDPR Art. 33(1) as amended'), true).
clause(43, people(var('__anon10'), risk(unlikely), none, 'GDPR Art. 34(1)'), true).
clause(44, people(var('__anon11'), risk(some), none, 'GDPR Art. 34(1)'), true).
clause(45, people(var('__anon12'), risk(high), without_undue_delay, 'GDPR Art. 34(1)'), true).
clause(46, outcome(var('R'), var('V'), no_consent_needed, [var('P')]), ','(visit(var('V'), var('__anon13'), var('A'), var('__anon14')), ','(kind(var('A'), var('K')), consent(var('R'), var('K'), not_needed, var('P'))))).
clause(47, outcome(var('R'), var('V'), var('Decision'), var('Basis')), ','(visit(var('V'), var('Site'), var('A'), var('Before')), ','(site(var('Site'), var('Media')), ','(kind(var('A'), var('K')), ','(consent(var('R'), var('K'), needed, var('P')), ','(ask(var('R'), var('Media'), var('Before'), var('Decision'), var('Q')), cite(var('P'), var('Q'), var('Basis')))))))).
clause(48, outcome(var('R'), var('B'), notify(authority(var('When')), people(var('How'))), [var('P'), var('Q')]), ','(breach(var('B'), var('__anon15'), var('Risk')), ','(authority(var('R'), var('Risk'), var('When'), var('P')), people(var('R'), var('Risk'), var('How'), var('Q'))))).
clause(49, cite(var('P'), var('P'), [var('P')]), true).
clause(50, cite(var('P'), var('Q'), [var('P'), var('Q')]), \==(var('P'), var('Q'))).
clause(51, decision(var('R'), var('Case'), var('Outcome'), basis(var('Provisions'))), ','(regime(var('R')), outcome(var('R'), var('Case'), var('Outcome'), var('Provisions')))).
clause(52, changed(var('Case'), from(var('Old')), to(var('New')), because(var('Basis'))), ','(decision(in_force, var('Case'), var('Old'), var('__anon16')), ','(decision(omnibus_proposal, var('Case'), var('New'), basis(var('Basis'))), \==(var('Old'), var('New'))))).

step(decision(in_force, v1, no_consent_needed, basis(['ePrivacy Art. 5(3)'])), rule(51), [=('R', in_force), =('Case', v1), =('Outcome', no_consent_needed), =('Provisions', ['ePrivacy Art. 5(3)'])], [regime(in_force), outcome(in_force, v1, no_consent_needed, ['ePrivacy Art. 5(3)'])]).
step(regime(in_force), fact(1), [], []).
step(outcome(in_force, v1, no_consent_needed, ['ePrivacy Art. 5(3)']), rule(46), [=('R', in_force), =('V', v1), =('P', 'ePrivacy Art. 5(3)'), =('__anon13', shop), =('A', cart), =('__anon14', first_visit), =('K', requested_service)], [visit(v1, shop, cart, first_visit), kind(cart, requested_service), consent(in_force, requested_service, not_needed, 'ePrivacy Art. 5(3)')]).
step(visit(v1, shop, cart, first_visit), fact(9), [], []).
step(kind(cart, requested_service), rule(19), [=('A', cart), =('__anon0', aggregated(no)), =('__anon1', own_use(yes))], [access(cart, purpose(requested_service), aggregated(no), own_use(yes))]).
step(access(cart, purpose(requested_service), aggregated(no), own_use(yes)), fact(5), [], []).
step(consent(in_force, requested_service, not_needed, 'ePrivacy Art. 5(3)'), fact(23), [], []).
step(decision(in_force, v2, ask_for_consent, basis(['ePrivacy Art. 5(3)'])), rule(51), [=('R', in_force), =('Case', v2), =('Outcome', ask_for_consent), =('Provisions', ['ePrivacy Art. 5(3)'])], [regime(in_force), outcome(in_force, v2, ask_for_consent, ['ePrivacy Art. 5(3)'])]).
step(outcome(in_force, v2, ask_for_consent, ['ePrivacy Art. 5(3)']), rule(47), [=('R', in_force), =('V', v2), =('Decision', ask_for_consent), =('Basis', ['ePrivacy Art. 5(3)']), =('Site', shop), =('A', stats), =('Before', first_visit), =('Media', media_service(no)), =('K', own_audience_measurement), =('P', 'ePrivacy Art. 5(3)'), =('Q', 'ePrivacy Art. 5(3)')], [visit(v2, shop, stats, first_visit), site(shop, media_service(no)), kind(stats, own_audience_measurement), consent(in_force, own_audience_measurement, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(no), first_visit, ask_for_consent, 'ePrivacy Art. 5(3)'), cite('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ePrivacy Art. 5(3)'])]).
step(visit(v2, shop, stats, first_visit), fact(10), [], []).
step(site(shop, media_service(no)), fact(3), [], []).
step(kind(stats, own_audience_measurement), rule(20), [=('A', stats)], [access(stats, purpose(audience_measurement), aggregated(yes), own_use(yes))]).
step(access(stats, purpose(audience_measurement), aggregated(yes), own_use(yes)), fact(6), [], []).
step(consent(in_force, own_audience_measurement, needed, 'ePrivacy Art. 5(3)'), fact(24), [], []).
step(ask(in_force, media_service(no), first_visit, ask_for_consent, 'ePrivacy Art. 5(3)'), fact(31), [=('__anon5', media_service(no)), =('__anon6', first_visit)], []).
step(cite('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ePrivacy Art. 5(3)']), fact(49), [=('P', 'ePrivacy Art. 5(3)')], []).
step(decision(in_force, v3, ask_for_consent, basis(['ePrivacy Art. 5(3)'])), rule(51), [=('R', in_force), =('Case', v3), =('Outcome', ask_for_consent), =('Provisions', ['ePrivacy Art. 5(3)'])], [regime(in_force), outcome(in_force, v3, ask_for_consent, ['ePrivacy Art. 5(3)'])]).
step(outcome(in_force, v3, ask_for_consent, ['ePrivacy Art. 5(3)']), rule(47), [=('R', in_force), =('V', v3), =('Decision', ask_for_consent), =('Basis', ['ePrivacy Art. 5(3)']), =('Site', shop), =('A', vendor_stats), =('Before', first_visit), =('Media', media_service(no)), =('K', shared_measurement), =('P', 'ePrivacy Art. 5(3)'), =('Q', 'ePrivacy Art. 5(3)')], [visit(v3, shop, vendor_stats, first_visit), site(shop, media_service(no)), kind(vendor_stats, shared_measurement), consent(in_force, shared_measurement, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(no), first_visit, ask_for_consent, 'ePrivacy Art. 5(3)'), cite('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ePrivacy Art. 5(3)'])]).
step(visit(v3, shop, vendor_stats, first_visit), fact(11), [], []).
step(kind(vendor_stats, shared_measurement), rule(21), [=('A', vendor_stats), =('__anon2', aggregated(yes))], [access(vendor_stats, purpose(audience_measurement), aggregated(yes), own_use(no))]).
step(access(vendor_stats, purpose(audience_measurement), aggregated(yes), own_use(no)), fact(7), [], []).
step(consent(in_force, shared_measurement, needed, 'ePrivacy Art. 5(3)'), fact(25), [], []).
step(decision(in_force, v4, ask_for_consent, basis(['ePrivacy Art. 5(3)'])), rule(51), [=('R', in_force), =('Case', v4), =('Outcome', ask_for_consent), =('Provisions', ['ePrivacy Art. 5(3)'])], [regime(in_force), outcome(in_force, v4, ask_for_consent, ['ePrivacy Art. 5(3)'])]).
step(outcome(in_force, v4, ask_for_consent, ['ePrivacy Art. 5(3)']), rule(47), [=('R', in_force), =('V', v4), =('Decision', ask_for_consent), =('Basis', ['ePrivacy Art. 5(3)']), =('Site', shop), =('A', ads), =('Before', browser_signal(refuse)), =('Media', media_service(no)), =('K', advertising), =('P', 'ePrivacy Art. 5(3)'), =('Q', 'ePrivacy Art. 5(3)')], [visit(v4, shop, ads, browser_signal(refuse)), site(shop, media_service(no)), kind(ads, advertising), consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(no), browser_signal(refuse), ask_for_consent, 'ePrivacy Art. 5(3)'), cite('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ePrivacy Art. 5(3)'])]).
step(visit(v4, shop, ads, browser_signal(refuse)), fact(12), [], []).
step(kind(ads, advertising), rule(22), [=('A', ads), =('__anon3', aggregated(no)), =('__anon4', own_use(no))], [access(ads, purpose(advertising), aggregated(no), own_use(no))]).
step(access(ads, purpose(advertising), aggregated(no), own_use(no)), fact(8), [], []).
step(consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), fact(26), [], []).
step(ask(in_force, media_service(no), browser_signal(refuse), ask_for_consent, 'ePrivacy Art. 5(3)'), fact(31), [=('__anon5', media_service(no)), =('__anon6', browser_signal(refuse))], []).
step(decision(in_force, v5, ask_for_consent, basis(['ePrivacy Art. 5(3)'])), rule(51), [=('R', in_force), =('Case', v5), =('Outcome', ask_for_consent), =('Provisions', ['ePrivacy Art. 5(3)'])], [regime(in_force), outcome(in_force, v5, ask_for_consent, ['ePrivacy Art. 5(3)'])]).
step(outcome(in_force, v5, ask_for_consent, ['ePrivacy Art. 5(3)']), rule(47), [=('R', in_force), =('V', v5), =('Decision', ask_for_consent), =('Basis', ['ePrivacy Art. 5(3)']), =('Site', news), =('A', ads), =('Before', browser_signal(refuse)), =('Media', media_service(yes)), =('K', advertising), =('P', 'ePrivacy Art. 5(3)'), =('Q', 'ePrivacy Art. 5(3)')], [visit(v5, news, ads, browser_signal(refuse)), site(news, media_service(yes)), kind(ads, advertising), consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(yes), browser_signal(refuse), ask_for_consent, 'ePrivacy Art. 5(3)'), cite('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ePrivacy Art. 5(3)'])]).
step(visit(v5, news, ads, browser_signal(refuse)), fact(13), [], []).
step(site(news, media_service(yes)), fact(4), [], []).
step(ask(in_force, media_service(yes), browser_signal(refuse), ask_for_consent, 'ePrivacy Art. 5(3)'), fact(31), [=('__anon5', media_service(yes)), =('__anon6', browser_signal(refuse))], []).
step(decision(in_force, v6, ask_for_consent, basis(['ePrivacy Art. 5(3)'])), rule(51), [=('R', in_force), =('Case', v6), =('Outcome', ask_for_consent), =('Provisions', ['ePrivacy Art. 5(3)'])], [regime(in_force), outcome(in_force, v6, ask_for_consent, ['ePrivacy Art. 5(3)'])]).
step(outcome(in_force, v6, ask_for_consent, ['ePrivacy Art. 5(3)']), rule(47), [=('R', in_force), =('V', v6), =('Decision', ask_for_consent), =('Basis', ['ePrivacy Art. 5(3)']), =('Site', shop), =('A', ads), =('Before', refused(days_ago(60))), =('Media', media_service(no)), =('K', advertising), =('P', 'ePrivacy Art. 5(3)'), =('Q', 'ePrivacy Art. 5(3)')], [visit(v6, shop, ads, refused(days_ago(60))), site(shop, media_service(no)), kind(ads, advertising), consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(no), refused(days_ago(60)), ask_for_consent, 'ePrivacy Art. 5(3)'), cite('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ePrivacy Art. 5(3)'])]).
step(visit(v6, shop, ads, refused(days_ago(60))), fact(14), [], []).
step(ask(in_force, media_service(no), refused(days_ago(60)), ask_for_consent, 'ePrivacy Art. 5(3)'), fact(31), [=('__anon5', media_service(no)), =('__anon6', refused(days_ago(60)))], []).
step(decision(in_force, v7, ask_for_consent, basis(['ePrivacy Art. 5(3)'])), rule(51), [=('R', in_force), =('Case', v7), =('Outcome', ask_for_consent), =('Provisions', ['ePrivacy Art. 5(3)'])], [regime(in_force), outcome(in_force, v7, ask_for_consent, ['ePrivacy Art. 5(3)'])]).
step(outcome(in_force, v7, ask_for_consent, ['ePrivacy Art. 5(3)']), rule(47), [=('R', in_force), =('V', v7), =('Decision', ask_for_consent), =('Basis', ['ePrivacy Art. 5(3)']), =('Site', shop), =('A', ads), =('Before', refused(days_ago(200))), =('Media', media_service(no)), =('K', advertising), =('P', 'ePrivacy Art. 5(3)'), =('Q', 'ePrivacy Art. 5(3)')], [visit(v7, shop, ads, refused(days_ago(200))), site(shop, media_service(no)), kind(ads, advertising), consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(no), refused(days_ago(200)), ask_for_consent, 'ePrivacy Art. 5(3)'), cite('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ePrivacy Art. 5(3)'])]).
step(visit(v7, shop, ads, refused(days_ago(200))), fact(15), [], []).
step(ask(in_force, media_service(no), refused(days_ago(200)), ask_for_consent, 'ePrivacy Art. 5(3)'), fact(31), [=('__anon5', media_service(no)), =('__anon6', refused(days_ago(200)))], []).
step(decision(in_force, b1, notify(authority(none), people(none)), basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])), rule(51), [=('R', in_force), =('Case', b1), =('Outcome', notify(authority(none), people(none))), =('Provisions', ['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])], [regime(in_force), outcome(in_force, b1, notify(authority(none), people(none)), ['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])]).
step(outcome(in_force, b1, notify(authority(none), people(none)), ['GDPR Art. 33(1)', 'GDPR Art. 34(1)']), rule(48), [=('R', in_force), =('B', b1), =('When', none), =('How', none), =('P', 'GDPR Art. 33(1)'), =('Q', 'GDPR Art. 34(1)'), =('__anon15', 'encrypted laptop lost, key safe'), =('Risk', risk(unlikely))], [breach(b1, 'encrypted laptop lost, key safe', risk(unlikely)), authority(in_force, risk(unlikely), none, 'GDPR Art. 33(1)'), people(in_force, risk(unlikely), none, 'GDPR Art. 34(1)')]).
step(breach(b1, 'encrypted laptop lost, key safe', risk(unlikely)), fact(16), [], []).
step(authority(in_force, risk(unlikely), none, 'GDPR Art. 33(1)'), fact(37), [], []).
step(people(in_force, risk(unlikely), none, 'GDPR Art. 34(1)'), fact(43), [=('__anon10', in_force)], []).
step(decision(in_force, b2, notify(authority(within_hours(72)), people(none)), basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])), rule(51), [=('R', in_force), =('Case', b2), =('Outcome', notify(authority(within_hours(72)), people(none))), =('Provisions', ['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])], [regime(in_force), outcome(in_force, b2, notify(authority(within_hours(72)), people(none)), ['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])]).
step(outcome(in_force, b2, notify(authority(within_hours(72)), people(none)), ['GDPR Art. 33(1)', 'GDPR Art. 34(1)']), rule(48), [=('R', in_force), =('B', b2), =('When', within_hours(72)), =('How', none), =('P', 'GDPR Art. 33(1)'), =('Q', 'GDPR Art. 34(1)'), =('__anon15', 'customer e-mail addresses exposed'), =('Risk', risk(some))], [breach(b2, 'customer e-mail addresses exposed', risk(some)), authority(in_force, risk(some), within_hours(72), 'GDPR Art. 33(1)'), people(in_force, risk(some), none, 'GDPR Art. 34(1)')]).
step(breach(b2, 'customer e-mail addresses exposed', risk(some)), fact(17), [], []).
step(authority(in_force, risk(some), within_hours(72), 'GDPR Art. 33(1)'), fact(38), [], []).
step(people(in_force, risk(some), none, 'GDPR Art. 34(1)'), fact(44), [=('__anon11', in_force)], []).
step(decision(in_force, b3, notify(authority(within_hours(72)), people(without_undue_delay)), basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])), rule(51), [=('R', in_force), =('Case', b3), =('Outcome', notify(authority(within_hours(72)), people(without_undue_delay))), =('Provisions', ['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])], [regime(in_force), outcome(in_force, b3, notify(authority(within_hours(72)), people(without_undue_delay)), ['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])]).
step(outcome(in_force, b3, notify(authority(within_hours(72)), people(without_undue_delay)), ['GDPR Art. 33(1)', 'GDPR Art. 34(1)']), rule(48), [=('R', in_force), =('B', b3), =('When', within_hours(72)), =('How', without_undue_delay), =('P', 'GDPR Art. 33(1)'), =('Q', 'GDPR Art. 34(1)'), =('__anon15', 'patient records exposed'), =('Risk', risk(high))], [breach(b3, 'patient records exposed', risk(high)), authority(in_force, risk(high), within_hours(72), 'GDPR Art. 33(1)'), people(in_force, risk(high), without_undue_delay, 'GDPR Art. 34(1)')]).
step(breach(b3, 'patient records exposed', risk(high)), fact(18), [], []).
step(authority(in_force, risk(high), within_hours(72), 'GDPR Art. 33(1)'), fact(39), [], []).
step(people(in_force, risk(high), without_undue_delay, 'GDPR Art. 34(1)'), fact(45), [=('__anon12', in_force)], []).
step(decision(omnibus_proposal, v1, no_consent_needed, basis(['GDPR Art. 88a(3)(b)'])), rule(51), [=('R', omnibus_proposal), =('Case', v1), =('Outcome', no_consent_needed), =('Provisions', ['GDPR Art. 88a(3)(b)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, v1, no_consent_needed, ['GDPR Art. 88a(3)(b)'])]).
step(regime(omnibus_proposal), fact(2), [], []).
step(outcome(omnibus_proposal, v1, no_consent_needed, ['GDPR Art. 88a(3)(b)']), rule(46), [=('R', omnibus_proposal), =('V', v1), =('P', 'GDPR Art. 88a(3)(b)'), =('__anon13', shop), =('A', cart), =('__anon14', first_visit), =('K', requested_service)], [visit(v1, shop, cart, first_visit), kind(cart, requested_service), consent(omnibus_proposal, requested_service, not_needed, 'GDPR Art. 88a(3)(b)')]).
step(consent(omnibus_proposal, requested_service, not_needed, 'GDPR Art. 88a(3)(b)'), fact(27), [], []).
step(decision(omnibus_proposal, v2, no_consent_needed, basis(['GDPR Art. 88a(3)(c)'])), rule(51), [=('R', omnibus_proposal), =('Case', v2), =('Outcome', no_consent_needed), =('Provisions', ['GDPR Art. 88a(3)(c)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, v2, no_consent_needed, ['GDPR Art. 88a(3)(c)'])]).
step(outcome(omnibus_proposal, v2, no_consent_needed, ['GDPR Art. 88a(3)(c)']), rule(46), [=('R', omnibus_proposal), =('V', v2), =('P', 'GDPR Art. 88a(3)(c)'), =('__anon13', shop), =('A', stats), =('__anon14', first_visit), =('K', own_audience_measurement)], [visit(v2, shop, stats, first_visit), kind(stats, own_audience_measurement), consent(omnibus_proposal, own_audience_measurement, not_needed, 'GDPR Art. 88a(3)(c)')]).
step(consent(omnibus_proposal, own_audience_measurement, not_needed, 'GDPR Art. 88a(3)(c)'), fact(28), [], []).
step(decision(omnibus_proposal, v3, ask_for_consent, basis(['GDPR Art. 88a(1)'])), rule(51), [=('R', omnibus_proposal), =('Case', v3), =('Outcome', ask_for_consent), =('Provisions', ['GDPR Art. 88a(1)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, v3, ask_for_consent, ['GDPR Art. 88a(1)'])]).
step(outcome(omnibus_proposal, v3, ask_for_consent, ['GDPR Art. 88a(1)']), rule(47), [=('R', omnibus_proposal), =('V', v3), =('Decision', ask_for_consent), =('Basis', ['GDPR Art. 88a(1)']), =('Site', shop), =('A', vendor_stats), =('Before', first_visit), =('Media', media_service(no)), =('K', shared_measurement), =('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88a(1)')], [visit(v3, shop, vendor_stats, first_visit), site(shop, media_service(no)), kind(vendor_stats, shared_measurement), consent(omnibus_proposal, shared_measurement, needed, 'GDPR Art. 88a(1)'), ask(omnibus_proposal, media_service(no), first_visit, ask_for_consent, 'GDPR Art. 88a(1)'), cite('GDPR Art. 88a(1)', 'GDPR Art. 88a(1)', ['GDPR Art. 88a(1)'])]).
step(consent(omnibus_proposal, shared_measurement, needed, 'GDPR Art. 88a(1)'), fact(29), [], []).
step(ask(omnibus_proposal, media_service(no), first_visit, ask_for_consent, 'GDPR Art. 88a(1)'), fact(32), [=('__anon7', media_service(no))], []).
step(cite('GDPR Art. 88a(1)', 'GDPR Art. 88a(1)', ['GDPR Art. 88a(1)']), fact(49), [=('P', 'GDPR Art. 88a(1)')], []).
step(decision(omnibus_proposal, v4, refused_by_signal, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])), rule(51), [=('R', omnibus_proposal), =('Case', v4), =('Outcome', refused_by_signal), =('Provisions', ['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, v4, refused_by_signal, ['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])]).
step(outcome(omnibus_proposal, v4, refused_by_signal, ['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)']), rule(47), [=('R', omnibus_proposal), =('V', v4), =('Decision', refused_by_signal), =('Basis', ['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)']), =('Site', shop), =('A', ads), =('Before', browser_signal(refuse)), =('Media', media_service(no)), =('K', advertising), =('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88b(1)-(2)')], [visit(v4, shop, ads, browser_signal(refuse)), site(shop, media_service(no)), kind(ads, advertising), consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), ask(omnibus_proposal, media_service(no), browser_signal(refuse), refused_by_signal, 'GDPR Art. 88b(1)-(2)'), cite('GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)', ['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])]).
step(consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), fact(30), [], []).
step(ask(omnibus_proposal, media_service(no), browser_signal(refuse), refused_by_signal, 'GDPR Art. 88b(1)-(2)'), fact(33), [], []).
step(cite('GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)', ['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)']), rule(50), [=('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88b(1)-(2)')], [\==('GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)')]).
step(\==('GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'), builtin, [], []).
step(decision(omnibus_proposal, v5, ask_for_consent, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88b(3)'])), rule(51), [=('R', omnibus_proposal), =('Case', v5), =('Outcome', ask_for_consent), =('Provisions', ['GDPR Art. 88a(1)', 'GDPR Art. 88b(3)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, v5, ask_for_consent, ['GDPR Art. 88a(1)', 'GDPR Art. 88b(3)'])]).
step(outcome(omnibus_proposal, v5, ask_for_consent, ['GDPR Art. 88a(1)', 'GDPR Art. 88b(3)']), rule(47), [=('R', omnibus_proposal), =('V', v5), =('Decision', ask_for_consent), =('Basis', ['GDPR Art. 88a(1)', 'GDPR Art. 88b(3)']), =('Site', news), =('A', ads), =('Before', browser_signal(refuse)), =('Media', media_service(yes)), =('K', advertising), =('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88b(3)')], [visit(v5, news, ads, browser_signal(refuse)), site(news, media_service(yes)), kind(ads, advertising), consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), ask(omnibus_proposal, media_service(yes), browser_signal(refuse), ask_for_consent, 'GDPR Art. 88b(3)'), cite('GDPR Art. 88a(1)', 'GDPR Art. 88b(3)', ['GDPR Art. 88a(1)', 'GDPR Art. 88b(3)'])]).
step(ask(omnibus_proposal, media_service(yes), browser_signal(refuse), ask_for_consent, 'GDPR Art. 88b(3)'), fact(34), [], []).
step(cite('GDPR Art. 88a(1)', 'GDPR Art. 88b(3)', ['GDPR Art. 88a(1)', 'GDPR Art. 88b(3)']), rule(50), [=('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88b(3)')], [\==('GDPR Art. 88a(1)', 'GDPR Art. 88b(3)')]).
step(\==('GDPR Art. 88a(1)', 'GDPR Art. 88b(3)'), builtin, [], []).
step(decision(omnibus_proposal, v6, do_not_ask_again, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])), rule(51), [=('R', omnibus_proposal), =('Case', v6), =('Outcome', do_not_ask_again), =('Provisions', ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, v6, do_not_ask_again, ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])]).
step(outcome(omnibus_proposal, v6, do_not_ask_again, ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']), rule(47), [=('R', omnibus_proposal), =('V', v6), =('Decision', do_not_ask_again), =('Basis', ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']), =('Site', shop), =('A', ads), =('Before', refused(days_ago(60))), =('Media', media_service(no)), =('K', advertising), =('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88a(4)(c)')], [visit(v6, shop, ads, refused(days_ago(60))), site(shop, media_service(no)), kind(ads, advertising), consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), ask(omnibus_proposal, media_service(no), refused(days_ago(60)), do_not_ask_again, 'GDPR Art. 88a(4)(c)'), cite('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)', ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])]).
step(ask(omnibus_proposal, media_service(no), refused(days_ago(60)), do_not_ask_again, 'GDPR Art. 88a(4)(c)'), rule(35), [=('__anon8', media_service(no)), =('D', 60)], [<(60, 183)]).
step(<(60, 183), builtin, [], []).
step(cite('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)', ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']), rule(50), [=('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88a(4)(c)')], [\==('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)')]).
step(\==('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'), builtin, [], []).
step(decision(omnibus_proposal, v7, ask_for_consent, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])), rule(51), [=('R', omnibus_proposal), =('Case', v7), =('Outcome', ask_for_consent), =('Provisions', ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, v7, ask_for_consent, ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])]).
step(outcome(omnibus_proposal, v7, ask_for_consent, ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']), rule(47), [=('R', omnibus_proposal), =('V', v7), =('Decision', ask_for_consent), =('Basis', ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']), =('Site', shop), =('A', ads), =('Before', refused(days_ago(200))), =('Media', media_service(no)), =('K', advertising), =('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88a(4)(c)')], [visit(v7, shop, ads, refused(days_ago(200))), site(shop, media_service(no)), kind(ads, advertising), consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), ask(omnibus_proposal, media_service(no), refused(days_ago(200)), ask_for_consent, 'GDPR Art. 88a(4)(c)'), cite('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)', ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])]).
step(ask(omnibus_proposal, media_service(no), refused(days_ago(200)), ask_for_consent, 'GDPR Art. 88a(4)(c)'), rule(36), [=('__anon9', media_service(no)), =('D', 200)], [>=(200, 183)]).
step(>=(200, 183), builtin, [], []).
step(decision(omnibus_proposal, b1, notify(authority(none), people(none)), basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])), rule(51), [=('R', omnibus_proposal), =('Case', b1), =('Outcome', notify(authority(none), people(none))), =('Provisions', ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, b1, notify(authority(none), people(none)), ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])]).
step(outcome(omnibus_proposal, b1, notify(authority(none), people(none)), ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)']), rule(48), [=('R', omnibus_proposal), =('B', b1), =('When', none), =('How', none), =('P', 'GDPR Art. 33(1) as amended'), =('Q', 'GDPR Art. 34(1)'), =('__anon15', 'encrypted laptop lost, key safe'), =('Risk', risk(unlikely))], [breach(b1, 'encrypted laptop lost, key safe', risk(unlikely)), authority(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 33(1) as amended'), people(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 34(1)')]).
step(authority(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 33(1) as amended'), fact(40), [], []).
step(people(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 34(1)'), fact(43), [=('__anon10', omnibus_proposal)], []).
step(decision(omnibus_proposal, b2, notify(authority(none), people(none)), basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])), rule(51), [=('R', omnibus_proposal), =('Case', b2), =('Outcome', notify(authority(none), people(none))), =('Provisions', ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, b2, notify(authority(none), people(none)), ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])]).
step(outcome(omnibus_proposal, b2, notify(authority(none), people(none)), ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)']), rule(48), [=('R', omnibus_proposal), =('B', b2), =('When', none), =('How', none), =('P', 'GDPR Art. 33(1) as amended'), =('Q', 'GDPR Art. 34(1)'), =('__anon15', 'customer e-mail addresses exposed'), =('Risk', risk(some))], [breach(b2, 'customer e-mail addresses exposed', risk(some)), authority(omnibus_proposal, risk(some), none, 'GDPR Art. 33(1) as amended'), people(omnibus_proposal, risk(some), none, 'GDPR Art. 34(1)')]).
step(authority(omnibus_proposal, risk(some), none, 'GDPR Art. 33(1) as amended'), fact(41), [], []).
step(people(omnibus_proposal, risk(some), none, 'GDPR Art. 34(1)'), fact(44), [=('__anon11', omnibus_proposal)], []).
step(decision(omnibus_proposal, b3, notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)), basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])), rule(51), [=('R', omnibus_proposal), =('Case', b3), =('Outcome', notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay))), =('Provisions', ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])], [regime(omnibus_proposal), outcome(omnibus_proposal, b3, notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)), ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])]).
step(outcome(omnibus_proposal, b3, notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)), ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)']), rule(48), [=('R', omnibus_proposal), =('B', b3), =('When', within_hours_via_single_entry_point(96)), =('How', without_undue_delay), =('P', 'GDPR Art. 33(1) as amended'), =('Q', 'GDPR Art. 34(1)'), =('__anon15', 'patient records exposed'), =('Risk', risk(high))], [breach(b3, 'patient records exposed', risk(high)), authority(omnibus_proposal, risk(high), within_hours_via_single_entry_point(96), 'GDPR Art. 33(1) as amended'), people(omnibus_proposal, risk(high), without_undue_delay, 'GDPR Art. 34(1)')]).
step(authority(omnibus_proposal, risk(high), within_hours_via_single_entry_point(96), 'GDPR Art. 33(1) as amended'), fact(42), [], []).
step(people(omnibus_proposal, risk(high), without_undue_delay, 'GDPR Art. 34(1)'), fact(45), [=('__anon12', omnibus_proposal)], []).
step(changed(v2, from(ask_for_consent), to(no_consent_needed), because(['GDPR Art. 88a(3)(c)'])), rule(52), [=('Case', v2), =('Old', ask_for_consent), =('New', no_consent_needed), =('Basis', ['GDPR Art. 88a(3)(c)']), =('__anon16', basis(['ePrivacy Art. 5(3)']))], [decision(in_force, v2, ask_for_consent, basis(['ePrivacy Art. 5(3)'])), decision(omnibus_proposal, v2, no_consent_needed, basis(['GDPR Art. 88a(3)(c)'])), \==(ask_for_consent, no_consent_needed)]).
step(\==(ask_for_consent, no_consent_needed), builtin, [], []).
step(changed(v4, from(ask_for_consent), to(refused_by_signal), because(['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])), rule(52), [=('Case', v4), =('Old', ask_for_consent), =('New', refused_by_signal), =('Basis', ['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)']), =('__anon16', basis(['ePrivacy Art. 5(3)']))], [decision(in_force, v4, ask_for_consent, basis(['ePrivacy Art. 5(3)'])), decision(omnibus_proposal, v4, refused_by_signal, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])), \==(ask_for_consent, refused_by_signal)]).
step(\==(ask_for_consent, refused_by_signal), builtin, [], []).
step(changed(v6, from(ask_for_consent), to(do_not_ask_again), because(['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])), rule(52), [=('Case', v6), =('Old', ask_for_consent), =('New', do_not_ask_again), =('Basis', ['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']), =('__anon16', basis(['ePrivacy Art. 5(3)']))], [decision(in_force, v6, ask_for_consent, basis(['ePrivacy Art. 5(3)'])), decision(omnibus_proposal, v6, do_not_ask_again, basis(['GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])), \==(ask_for_consent, do_not_ask_again)]).
step(\==(ask_for_consent, do_not_ask_again), builtin, [], []).
step(changed(b2, from(notify(authority(within_hours(72)), people(none))), to(notify(authority(none), people(none))), because(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])), rule(52), [=('Case', b2), =('Old', notify(authority(within_hours(72)), people(none))), =('New', notify(authority(none), people(none))), =('Basis', ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)']), =('__anon16', basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)']))], [decision(in_force, b2, notify(authority(within_hours(72)), people(none)), basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])), decision(omnibus_proposal, b2, notify(authority(none), people(none)), basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])), \==(notify(authority(within_hours(72)), people(none)), notify(authority(none), people(none)))]).
step(\==(notify(authority(within_hours(72)), people(none)), notify(authority(none), people(none))), builtin, [], []).
step(changed(b3, from(notify(authority(within_hours(72)), people(without_undue_delay))), to(notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay))), because(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])), rule(52), [=('Case', b3), =('Old', notify(authority(within_hours(72)), people(without_undue_delay))), =('New', notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay))), =('Basis', ['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)']), =('__anon16', basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)']))], [decision(in_force, b3, notify(authority(within_hours(72)), people(without_undue_delay)), basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)'])), decision(omnibus_proposal, b3, notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)), basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)'])), \==(notify(authority(within_hours(72)), people(without_undue_delay)), notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)))]).
step(\==(notify(authority(within_hours(72)), people(without_undue_delay)), notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay))), builtin, [], []).
