colors(mapEU, [['Belgium', yellow], ['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]).

clause(1, colors(var('_Map'), var('Places')), ','(findall([var('Place'), var('__anon0')], neighbours(var('Place'), var('__anon1')), var('Places')), once(places(var('Places'))))).
clause(2, places([]), true).
clause(3, places([[var('Place'), var('Color')]|var('Tail')]), ','(places(var('Tail')), ','(neighbours(var('Place'), var('Neighbours')), ','(member(var('Color'), [red, green, blue, yellow]), \+(conflict(var('Color'), var('Tail'), var('Neighbours'))))))).
clause(5, member(var('X'), [var('X')|var('__anon2')]), true).
clause(6, member(var('X'), [var('__anon3')|var('Rest')]), member(var('X'), var('Rest'))).
clause(7, neighbours('Belgium', ['France', 'Netherlands', 'Luxemburg', 'Germany']), true).
clause(8, neighbours('Netherlands', ['Belgium', 'Germany']), true).
clause(9, neighbours('Luxemburg', ['Belgium', 'France', 'Germany']), true).
clause(10, neighbours('France', ['Spain', 'Belgium', 'Luxemburg', 'Germany', 'Italy']), true).
clause(11, neighbours('Germany', ['Netherlands', 'Belgium', 'Luxemburg', 'Denmark', 'France', 'Austria', 'Poland', 'Czech Republic']), true).
clause(12, neighbours('Italy', ['France', 'Austria', 'Slovenia']), true).
clause(13, neighbours('Denmark', ['Germany']), true).
clause(14, neighbours('Ireland', []), true).
clause(15, neighbours('Greece', ['Bulgaria']), true).
clause(16, neighbours('Spain', ['France', 'Portugal']), true).
clause(17, neighbours('Portugal', ['Spain']), true).
clause(18, neighbours('Austria', ['Czech Republic', 'Germany', 'Hungary', 'Italy', 'Slovenia', 'Slovakia']), true).
clause(19, neighbours('Sweden', ['Finland']), true).
clause(20, neighbours('Finland', ['Sweden']), true).
clause(21, neighbours('Cyprus', []), true).
clause(22, neighbours('Malta', []), true).
clause(23, neighbours('Poland', ['Germany', 'Czech Republic', 'Slovakia', 'Lithuania']), true).
clause(24, neighbours('Hungary', ['Austria', 'Slovakia', 'Romania', 'Croatia', 'Slovenia']), true).
clause(25, neighbours('Czech Republic', ['Germany', 'Poland', 'Slovakia', 'Austria']), true).
clause(26, neighbours('Slovakia', ['Czech Republic', 'Poland', 'Hungary', 'Austria']), true).
clause(27, neighbours('Slovenia', ['Austria', 'Italy', 'Hungary', 'Croatia']), true).
clause(28, neighbours('Estonia', ['Latvia']), true).
clause(29, neighbours('Latvia', ['Estonia', 'Lithuania']), true).
clause(30, neighbours('Lithuania', ['Latvia', 'Poland']), true).
clause(31, neighbours('Bulgaria', ['Romania', 'Greece']), true).
clause(32, neighbours('Romania', ['Hungary', 'Bulgaria']), true).
clause(33, neighbours('Croatia', ['Slovenia', 'Hungary']), true).

step(colors(mapEU, [['Belgium', yellow], ['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(1), [=('_Map', mapEU), =('Places', [['Belgium', yellow], ['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Place', EYE_Place_23_2), =('__anon0', EYE_____anon0_23_2), =('__anon1', EYE_____anon1_23_2)], [findall([EYE_Place_23_2, EYE_____anon0_23_2], neighbours(EYE_Place_23_2, EYE_____anon1_23_2), [['Belgium', yellow], ['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), once(places([['Belgium', yellow], ['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]))]).
step(findall([EYE_Place_23_2, EYE_____anon0_23_2], neighbours(EYE_Place_23_2, EYE_____anon1_23_2), [['Belgium', yellow], ['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), collected, [], []).
step(once(places([['Belgium', yellow], ['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]])), control, [], [places([['Belgium', yellow], ['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]])]).
step(places([['Belgium', yellow], ['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Belgium'), =('Color', yellow), =('Tail', [['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['France', 'Netherlands', 'Luxemburg', 'Germany'])], [places([['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Belgium', ['France', 'Netherlands', 'Luxemburg', 'Germany']), member(yellow, [red, green, blue, yellow]), \+(conflict(yellow, [['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['France', 'Netherlands', 'Luxemburg', 'Germany']))]).
step(places([['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Netherlands'), =('Color', green), =('Tail', [['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Belgium', 'Germany'])], [places([['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Netherlands', ['Belgium', 'Germany']), member(green, [red, green, blue, yellow]), \+(conflict(green, [['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Belgium', 'Germany']))]).
step(places([['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Luxemburg'), =('Color', green), =('Tail', [['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Belgium', 'France', 'Germany'])], [places([['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Luxemburg', ['Belgium', 'France', 'Germany']), member(green, [red, green, blue, yellow]), \+(conflict(green, [['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Belgium', 'France', 'Germany']))]).
step(places([['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'France'), =('Color', blue), =('Tail', [['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Spain', 'Belgium', 'Luxemburg', 'Germany', 'Italy'])], [places([['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('France', ['Spain', 'Belgium', 'Luxemburg', 'Germany', 'Italy']), member(blue, [red, green, blue, yellow]), \+(conflict(blue, [['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Spain', 'Belgium', 'Luxemburg', 'Germany', 'Italy']))]).
step(places([['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Germany'), =('Color', red), =('Tail', [['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Netherlands', 'Belgium', 'Luxemburg', 'Denmark', 'France', 'Austria', 'Poland', 'Czech Republic'])], [places([['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Germany', ['Netherlands', 'Belgium', 'Luxemburg', 'Denmark', 'France', 'Austria', 'Poland', 'Czech Republic']), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Netherlands', 'Belgium', 'Luxemburg', 'Denmark', 'France', 'Austria', 'Poland', 'Czech Republic']))]).
step(places([['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Italy'), =('Color', red), =('Tail', [['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['France', 'Austria', 'Slovenia'])], [places([['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Italy', ['France', 'Austria', 'Slovenia']), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['France', 'Austria', 'Slovenia']))]).
step(places([['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Denmark'), =('Color', green), =('Tail', [['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Germany'])], [places([['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Denmark', ['Germany']), member(green, [red, green, blue, yellow]), \+(conflict(green, [['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Germany']))]).
step(places([['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Ireland'), =('Color', red), =('Tail', [['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', [])], [places([['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Ireland', []), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], []))]).
step(places([['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Greece'), =('Color', red), =('Tail', [['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Bulgaria'])], [places([['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Greece', ['Bulgaria']), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Bulgaria']))]).
step(places([['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Spain'), =('Color', green), =('Tail', [['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['France', 'Portugal'])], [places([['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Spain', ['France', 'Portugal']), member(green, [red, green, blue, yellow]), \+(conflict(green, [['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['France', 'Portugal']))]).
step(places([['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Portugal'), =('Color', red), =('Tail', [['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Spain'])], [places([['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Portugal', ['Spain']), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Spain']))]).
step(places([['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Austria'), =('Color', yellow), =('Tail', [['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Czech Republic', 'Germany', 'Hungary', 'Italy', 'Slovenia', 'Slovakia'])], [places([['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Austria', ['Czech Republic', 'Germany', 'Hungary', 'Italy', 'Slovenia', 'Slovakia']), member(yellow, [red, green, blue, yellow]), \+(conflict(yellow, [['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Czech Republic', 'Germany', 'Hungary', 'Italy', 'Slovenia', 'Slovakia']))]).
step(places([['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Sweden'), =('Color', green), =('Tail', [['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Finland'])], [places([['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Sweden', ['Finland']), member(green, [red, green, blue, yellow]), \+(conflict(green, [['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Finland']))]).
step(places([['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Finland'), =('Color', red), =('Tail', [['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Sweden'])], [places([['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Finland', ['Sweden']), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Sweden']))]).
step(places([['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Cyprus'), =('Color', red), =('Tail', [['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', [])], [places([['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Cyprus', []), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], []))]).
step(places([['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Malta'), =('Color', red), =('Tail', [['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', [])], [places([['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Malta', []), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], []))]).
step(places([['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Poland'), =('Color', blue), =('Tail', [['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Germany', 'Czech Republic', 'Slovakia', 'Lithuania'])], [places([['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Poland', ['Germany', 'Czech Republic', 'Slovakia', 'Lithuania']), member(blue, [red, green, blue, yellow]), \+(conflict(blue, [['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Germany', 'Czech Republic', 'Slovakia', 'Lithuania']))]).
step(places([['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Hungary'), =('Color', blue), =('Tail', [['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Austria', 'Slovakia', 'Romania', 'Croatia', 'Slovenia'])], [places([['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Hungary', ['Austria', 'Slovakia', 'Romania', 'Croatia', 'Slovenia']), member(blue, [red, green, blue, yellow]), \+(conflict(blue, [['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Austria', 'Slovakia', 'Romania', 'Croatia', 'Slovenia']))]).
step(places([['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Czech Republic'), =('Color', green), =('Tail', [['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Germany', 'Poland', 'Slovakia', 'Austria'])], [places([['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Czech Republic', ['Germany', 'Poland', 'Slovakia', 'Austria']), member(green, [red, green, blue, yellow]), \+(conflict(green, [['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Germany', 'Poland', 'Slovakia', 'Austria']))]).
step(places([['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Slovakia'), =('Color', red), =('Tail', [['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Czech Republic', 'Poland', 'Hungary', 'Austria'])], [places([['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Slovakia', ['Czech Republic', 'Poland', 'Hungary', 'Austria']), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Czech Republic', 'Poland', 'Hungary', 'Austria']))]).
step(places([['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Slovenia'), =('Color', green), =('Tail', [['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Austria', 'Italy', 'Hungary', 'Croatia'])], [places([['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Slovenia', ['Austria', 'Italy', 'Hungary', 'Croatia']), member(green, [red, green, blue, yellow]), \+(conflict(green, [['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Austria', 'Italy', 'Hungary', 'Croatia']))]).
step(places([['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Estonia'), =('Color', red), =('Tail', [['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Latvia'])], [places([['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Estonia', ['Latvia']), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Latvia']))]).
step(places([['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Latvia'), =('Color', green), =('Tail', [['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Estonia', 'Lithuania'])], [places([['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Latvia', ['Estonia', 'Lithuania']), member(green, [red, green, blue, yellow]), \+(conflict(green, [['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Estonia', 'Lithuania']))]).
step(places([['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Lithuania'), =('Color', red), =('Tail', [['Bulgaria', green], ['Romania', red], ['Croatia', red]]), =('Neighbours', ['Latvia', 'Poland'])], [places([['Bulgaria', green], ['Romania', red], ['Croatia', red]]), neighbours('Lithuania', ['Latvia', 'Poland']), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Latvia', 'Poland']))]).
step(places([['Bulgaria', green], ['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Bulgaria'), =('Color', green), =('Tail', [['Romania', red], ['Croatia', red]]), =('Neighbours', ['Romania', 'Greece'])], [places([['Romania', red], ['Croatia', red]]), neighbours('Bulgaria', ['Romania', 'Greece']), member(green, [red, green, blue, yellow]), \+(conflict(green, [['Romania', red], ['Croatia', red]], ['Romania', 'Greece']))]).
step(places([['Romania', red], ['Croatia', red]]), rule(3), [=('Place', 'Romania'), =('Color', red), =('Tail', [['Croatia', red]]), =('Neighbours', ['Hungary', 'Bulgaria'])], [places([['Croatia', red]]), neighbours('Romania', ['Hungary', 'Bulgaria']), member(red, [red, green, blue, yellow]), \+(conflict(red, [['Croatia', red]], ['Hungary', 'Bulgaria']))]).
step(places([['Croatia', red]]), rule(3), [=('Place', 'Croatia'), =('Color', red), =('Tail', []), =('Neighbours', ['Slovenia', 'Hungary'])], [places([]), neighbours('Croatia', ['Slovenia', 'Hungary']), member(red, [red, green, blue, yellow]), \+(conflict(red, [], ['Slovenia', 'Hungary']))]).
step(places([]), fact(2), [], []).
step(neighbours('Croatia', ['Slovenia', 'Hungary']), fact(33), [], []).
step(member(red, [red, green, blue, yellow]), fact(5), [=('X', red), =('__anon2', [green, blue, yellow])], []).
step(\+(conflict(red, [], ['Slovenia', 'Hungary'])), absent, [], []).
step(neighbours('Romania', ['Hungary', 'Bulgaria']), fact(32), [], []).
step(\+(conflict(red, [['Croatia', red]], ['Hungary', 'Bulgaria'])), absent, [], []).
step(neighbours('Bulgaria', ['Romania', 'Greece']), fact(31), [], []).
step(member(green, [red, green, blue, yellow]), rule(6), [=('X', green), =('__anon3', red), =('Rest', [green, blue, yellow])], [member(green, [green, blue, yellow])]).
step(member(green, [green, blue, yellow]), fact(5), [=('X', green), =('__anon2', [blue, yellow])], []).
step(\+(conflict(green, [['Romania', red], ['Croatia', red]], ['Romania', 'Greece'])), absent, [], []).
step(neighbours('Lithuania', ['Latvia', 'Poland']), fact(30), [], []).
step(\+(conflict(red, [['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Latvia', 'Poland'])), absent, [], []).
step(neighbours('Latvia', ['Estonia', 'Lithuania']), fact(29), [], []).
step(\+(conflict(green, [['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Estonia', 'Lithuania'])), absent, [], []).
step(neighbours('Estonia', ['Latvia']), fact(28), [], []).
step(\+(conflict(red, [['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Latvia'])), absent, [], []).
step(neighbours('Slovenia', ['Austria', 'Italy', 'Hungary', 'Croatia']), fact(27), [], []).
step(\+(conflict(green, [['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Austria', 'Italy', 'Hungary', 'Croatia'])), absent, [], []).
step(neighbours('Slovakia', ['Czech Republic', 'Poland', 'Hungary', 'Austria']), fact(26), [], []).
step(\+(conflict(red, [['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Czech Republic', 'Poland', 'Hungary', 'Austria'])), absent, [], []).
step(neighbours('Czech Republic', ['Germany', 'Poland', 'Slovakia', 'Austria']), fact(25), [], []).
step(\+(conflict(green, [['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Germany', 'Poland', 'Slovakia', 'Austria'])), absent, [], []).
step(neighbours('Hungary', ['Austria', 'Slovakia', 'Romania', 'Croatia', 'Slovenia']), fact(24), [], []).
step(member(blue, [red, green, blue, yellow]), rule(6), [=('X', blue), =('__anon3', red), =('Rest', [green, blue, yellow])], [member(blue, [green, blue, yellow])]).
step(member(blue, [green, blue, yellow]), rule(6), [=('X', blue), =('__anon3', green), =('Rest', [blue, yellow])], [member(blue, [blue, yellow])]).
step(member(blue, [blue, yellow]), fact(5), [=('X', blue), =('__anon2', [yellow])], []).
step(\+(conflict(blue, [['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Austria', 'Slovakia', 'Romania', 'Croatia', 'Slovenia'])), absent, [], []).
step(neighbours('Poland', ['Germany', 'Czech Republic', 'Slovakia', 'Lithuania']), fact(23), [], []).
step(\+(conflict(blue, [['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Germany', 'Czech Republic', 'Slovakia', 'Lithuania'])), absent, [], []).
step(neighbours('Malta', []), fact(22), [], []).
step(\+(conflict(red, [['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], [])), absent, [], []).
step(neighbours('Cyprus', []), fact(21), [], []).
step(\+(conflict(red, [['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], [])), absent, [], []).
step(neighbours('Finland', ['Sweden']), fact(20), [], []).
step(\+(conflict(red, [['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Sweden'])), absent, [], []).
step(neighbours('Sweden', ['Finland']), fact(19), [], []).
step(\+(conflict(green, [['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Finland'])), absent, [], []).
step(neighbours('Austria', ['Czech Republic', 'Germany', 'Hungary', 'Italy', 'Slovenia', 'Slovakia']), fact(18), [], []).
step(member(yellow, [red, green, blue, yellow]), rule(6), [=('X', yellow), =('__anon3', red), =('Rest', [green, blue, yellow])], [member(yellow, [green, blue, yellow])]).
step(member(yellow, [green, blue, yellow]), rule(6), [=('X', yellow), =('__anon3', green), =('Rest', [blue, yellow])], [member(yellow, [blue, yellow])]).
step(member(yellow, [blue, yellow]), rule(6), [=('X', yellow), =('__anon3', blue), =('Rest', [yellow])], [member(yellow, [yellow])]).
step(member(yellow, [yellow]), fact(5), [=('X', yellow), =('__anon2', [])], []).
step(\+(conflict(yellow, [['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Czech Republic', 'Germany', 'Hungary', 'Italy', 'Slovenia', 'Slovakia'])), absent, [], []).
step(neighbours('Portugal', ['Spain']), fact(17), [], []).
step(\+(conflict(red, [['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Spain'])), absent, [], []).
step(neighbours('Spain', ['France', 'Portugal']), fact(16), [], []).
step(\+(conflict(green, [['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['France', 'Portugal'])), absent, [], []).
step(neighbours('Greece', ['Bulgaria']), fact(15), [], []).
step(\+(conflict(red, [['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Bulgaria'])), absent, [], []).
step(neighbours('Ireland', []), fact(14), [], []).
step(\+(conflict(red, [['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], [])), absent, [], []).
step(neighbours('Denmark', ['Germany']), fact(13), [], []).
step(\+(conflict(green, [['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Germany'])), absent, [], []).
step(neighbours('Italy', ['France', 'Austria', 'Slovenia']), fact(12), [], []).
step(\+(conflict(red, [['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['France', 'Austria', 'Slovenia'])), absent, [], []).
step(neighbours('Germany', ['Netherlands', 'Belgium', 'Luxemburg', 'Denmark', 'France', 'Austria', 'Poland', 'Czech Republic']), fact(11), [], []).
step(\+(conflict(red, [['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Netherlands', 'Belgium', 'Luxemburg', 'Denmark', 'France', 'Austria', 'Poland', 'Czech Republic'])), absent, [], []).
step(neighbours('France', ['Spain', 'Belgium', 'Luxemburg', 'Germany', 'Italy']), fact(10), [], []).
step(\+(conflict(blue, [['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Spain', 'Belgium', 'Luxemburg', 'Germany', 'Italy'])), absent, [], []).
step(neighbours('Luxemburg', ['Belgium', 'France', 'Germany']), fact(9), [], []).
step(\+(conflict(green, [['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Belgium', 'France', 'Germany'])), absent, [], []).
step(neighbours('Netherlands', ['Belgium', 'Germany']), fact(8), [], []).
step(\+(conflict(green, [['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['Belgium', 'Germany'])), absent, [], []).
step(neighbours('Belgium', ['France', 'Netherlands', 'Luxemburg', 'Germany']), fact(7), [], []).
step(\+(conflict(yellow, [['Netherlands', green], ['Luxemburg', green], ['France', blue], ['Germany', red], ['Italy', red], ['Denmark', green], ['Ireland', red], ['Greece', red], ['Spain', green], ['Portugal', red], ['Austria', yellow], ['Sweden', green], ['Finland', red], ['Cyprus', red], ['Malta', red], ['Poland', blue], ['Hungary', blue], ['Czech Republic', green], ['Slovakia', red], ['Slovenia', green], ['Estonia', red], ['Latvia', green], ['Lithuania', red], ['Bulgaria', green], ['Romania', red], ['Croatia', red]], ['France', 'Netherlands', 'Luxemburg', 'Germany'])), absent, [], []).
