decision('ex:r3', deny(prohibited_by('ex:noMarketing'))).
decision('ex:r6', deny(prohibited_by('ex:noTransferUS'))).
conflict('ex:r6', resolved_by('odrl:prohibit', 'ex:noTransferUS', overrides('ex:research'))).
decision('ex:r1', permit('ex:research')).
decision('ex:r2', deny(not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')]))).
decision('ex:r4', deny(not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')]))).
decision('ex:r5', deny(not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)]))).
duty('ex:r1', 'odrl:delete', within_days(90)).

clause(5, t('ex:partnerBE', 'odrl:partOf', 'ex:consortium'), true).
clause(6, t('ex:partnerUS', 'odrl:partOf', 'ex:consortium'), true).
clause(10, t('ex:policy', 'odrl:conflict', 'odrl:prohibit'), true).
clause(11, t('ex:policy', 'odrl:permission', 'ex:research'), true).
clause(12, t('ex:research', 'odrl:assignee', 'ex:consortium'), true).
clause(13, t('ex:research', 'odrl:action', 'odrl:use'), true).
clause(14, t('ex:research', 'odrl:target', 'ex:labResults'), true).
clause(20, t('ex:research', 'odrl:duty', 'ex:deletion'), true).
clause(21, t('ex:deletion', 'odrl:action', 'odrl:delete'), true).
clause(22, t('ex:deletion', 'ex:withinDays', 90), true).
clause(23, t('ex:policy', 'odrl:prohibition', 'ex:noMarketing'), true).
clause(24, t('ex:noMarketing', 'odrl:assignee', 'ex:consortium'), true).
clause(25, t('ex:noMarketing', 'odrl:action', 'odrl:distribute'), true).
clause(26, t('ex:noMarketing', 'odrl:target', 'ex:labResults'), true).
clause(28, t('ex:policy', 'odrl:prohibition', 'ex:noTransferUS'), true).
clause(29, t('ex:noTransferUS', 'odrl:assignee', 'ex:partnerUS'), true).
clause(30, t('ex:noTransferUS', 'odrl:action', 'odrl:use'), true).
clause(31, t('ex:noTransferUS', 'odrl:target', 'ex:labResults'), true).
clause(38, process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(39, process('ex:r2', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:PersonalisedAdvertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(40, process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(41, process('ex:r4', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:CommercialResearch', 'dpv:ConsentWithdrawn', 'dpv:Pseudonymisation', 20261115), true).
clause(42, process('ex:r5', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Encryption', 20270301), true).
clause(43, process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(44, t(var('P'), 'rdf:type', 'dpv:Process'), process(var('P'), var('__anon0'), var('__anon1'), var('__anon2'), var('__anon3'), var('__anon4'), var('__anon5'), var('__anon6'))).
clause(45, t(var('P'), 'ex:requestedBy', var('Who')), process(var('P'), var('Who'), var('__anon7'), var('__anon8'), var('__anon9'), var('__anon10'), var('__anon11'), var('__anon12'))).
clause(46, t(var('P'), 'dpv:hasProcessing', var('X')), process(var('P'), var('__anon13'), var('X'), var('__anon14'), var('__anon15'), var('__anon16'), var('__anon17'), var('__anon18'))).
clause(47, t(var('P'), 'dpv:hasPersonalData', var('X')), process(var('P'), var('__anon19'), var('__anon20'), var('X'), var('__anon21'), var('__anon22'), var('__anon23'), var('__anon24'))).
clause(53, action('dpv:Use', 'odrl:use'), true).
clause(54, action('dpv:Share', 'odrl:distribute'), true).
clause(65, party(var('Who'), var('Who')), true).
clause(66, party(var('Who'), var('Group')), t(var('Who'), 'odrl:partOf', var('Group'))).
clause(67, addresses(var('P'), var('Rule')), ','(t(var('P'), 'ex:requestedBy', var('Who')), ','(t(var('Rule'), 'odrl:assignee', var('Assignee')), ','(party(var('Who'), var('Assignee')), ','(t(var('P'), 'dpv:hasProcessing', var('Processing')), ','(action(var('Processing'), var('Action')), ','(t(var('Rule'), 'odrl:action', var('Action')), ','(t(var('P'), 'dpv:hasPersonalData', var('Data')), t(var('Rule'), 'odrl:target', var('Data')))))))))).
clause(70, applies(var('P'), var('Rule')), ','(addresses(var('P'), var('Rule')), findall(var('Why'), unmet(var('P'), var('Rule'), var('Why')), []))).
clause(71, permitted(var('P'), var('Rule')), ','(t('ex:policy', 'odrl:permission', var('Rule')), applies(var('P'), var('Rule')))).
clause(72, prohibited(var('P'), var('Rule')), ','(t('ex:policy', 'odrl:prohibition', var('Rule')), applies(var('P'), var('Rule')))).
clause(73, decision(var('P'), permit(var('Rule'))), ','(t(var('P'), 'rdf:type', 'dpv:Process'), ','(permitted(var('P'), var('Rule')), findall(var('R'), prohibited(var('P'), var('R')), [])))).
clause(74, decision(var('P'), deny(prohibited_by(var('Rule')))), ','(t(var('P'), 'rdf:type', 'dpv:Process'), prohibited(var('P'), var('Rule')))).
clause(75, decision(var('P'), deny(not_permitted(var('Reasons')))), ','(t(var('P'), 'rdf:type', 'dpv:Process'), ','(findall(var('R'), permitted(var('P'), var('R')), []), ','(findall(var('R'), prohibited(var('P'), var('R')), []), findall(var('Why'), ','(t('ex:policy', 'odrl:permission', var('Rule')), unmet(var('P'), var('Rule'), var('Why'))), var('Reasons')))))).
clause(76, conflict(var('P'), resolved_by('odrl:prohibit', var('Prohibition'), overrides(var('Permission')))), ','(t('ex:policy', 'odrl:conflict', 'odrl:prohibit'), ','(t(var('P'), 'rdf:type', 'dpv:Process'), ','(permitted(var('P'), var('Permission')), prohibited(var('P'), var('Prohibition')))))).
clause(77, duty(var('P'), var('Action'), within_days(var('Days'))), ','(decision(var('P'), permit(var('Rule'))), ','(t(var('Rule'), 'odrl:duty', var('Duty')), ','(t(var('Duty'), 'odrl:action', var('Action')), t(var('Duty'), 'ex:withinDays', var('Days')))))).

step(decision('ex:r3', deny(prohibited_by('ex:noMarketing'))), rule(74), [=('P', 'ex:r3'), =('Rule', 'ex:noMarketing')], [t('ex:r3', 'rdf:type', 'dpv:Process'), prohibited('ex:r3', 'ex:noMarketing')]).
step(t('ex:r3', 'rdf:type', 'dpv:Process'), rule(44), [=('P', 'ex:r3'), =('__anon0', 'ex:partnerBE'), =('__anon1', 'dpv:Share'), =('__anon2', 'ex:labResults'), =('__anon3', 'dpv:Advertising'), =('__anon4', 'dpv:ConsentGiven'), =('__anon5', 'dpv:Pseudonymisation'), =('__anon6', 20261115)], [process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(40), [], []).
step(prohibited('ex:r3', 'ex:noMarketing'), rule(72), [=('P', 'ex:r3'), =('Rule', 'ex:noMarketing')], [t('ex:policy', 'odrl:prohibition', 'ex:noMarketing'), applies('ex:r3', 'ex:noMarketing')]).
step(t('ex:policy', 'odrl:prohibition', 'ex:noMarketing'), fact(23), [], []).
step(applies('ex:r3', 'ex:noMarketing'), rule(70), [=('P', 'ex:r3'), =('Rule', 'ex:noMarketing'), =('Why', EYE_57_68_79_23_37_34)], [addresses('ex:r3', 'ex:noMarketing'), findall(EYE_57_68_79_23_37_34, unmet('ex:r3', 'ex:noMarketing', EYE_57_68_79_23_37_34), [])]).
step(addresses('ex:r3', 'ex:noMarketing'), rule(67), [=('P', 'ex:r3'), =('Rule', 'ex:noMarketing'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Share'), =('Action', 'odrl:distribute'), =('Data', 'ex:labResults')], [t('ex:r3', 'ex:requestedBy', 'ex:partnerBE'), t('ex:noMarketing', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r3', 'dpv:hasProcessing', 'dpv:Share'), action('dpv:Share', 'odrl:distribute'), t('ex:noMarketing', 'odrl:action', 'odrl:distribute'), t('ex:r3', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:noMarketing', 'odrl:target', 'ex:labResults')]).
step(t('ex:r3', 'ex:requestedBy', 'ex:partnerBE'), rule(45), [=('P', 'ex:r3'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Share'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:Advertising'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:noMarketing', 'odrl:assignee', 'ex:consortium'), fact(24), [], []).
step(party('ex:partnerBE', 'ex:consortium'), rule(66), [=('Who', 'ex:partnerBE'), =('Group', 'ex:consortium')], [t('ex:partnerBE', 'odrl:partOf', 'ex:consortium')]).
step(t('ex:partnerBE', 'odrl:partOf', 'ex:consortium'), fact(5), [], []).
step(t('ex:r3', 'dpv:hasProcessing', 'dpv:Share'), rule(46), [=('P', 'ex:r3'), =('X', 'dpv:Share'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:Advertising'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(action('dpv:Share', 'odrl:distribute'), fact(54), [], []).
step(t('ex:noMarketing', 'odrl:action', 'odrl:distribute'), fact(25), [], []).
step(t('ex:r3', 'dpv:hasPersonalData', 'ex:labResults'), rule(47), [=('P', 'ex:r3'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Share'), =('__anon21', 'dpv:Advertising'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:noMarketing', 'odrl:target', 'ex:labResults'), fact(26), [], []).
step(findall(EYE_57_68_79_23_37_34, unmet('ex:r3', 'ex:noMarketing', EYE_57_68_79_23_37_34), []), collected, [], []).
step(decision('ex:r6', deny(prohibited_by('ex:noTransferUS'))), rule(74), [=('P', 'ex:r6'), =('Rule', 'ex:noTransferUS')], [t('ex:r6', 'rdf:type', 'dpv:Process'), prohibited('ex:r6', 'ex:noTransferUS')]).
step(t('ex:r6', 'rdf:type', 'dpv:Process'), rule(44), [=('P', 'ex:r6'), =('__anon0', 'ex:partnerUS'), =('__anon1', 'dpv:Use'), =('__anon2', 'ex:labResults'), =('__anon3', 'dpv:AcademicResearch'), =('__anon4', 'dpv:ConsentGiven'), =('__anon5', 'dpv:Pseudonymisation'), =('__anon6', 20261115)], [process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(43), [], []).
step(prohibited('ex:r6', 'ex:noTransferUS'), rule(72), [=('P', 'ex:r6'), =('Rule', 'ex:noTransferUS')], [t('ex:policy', 'odrl:prohibition', 'ex:noTransferUS'), applies('ex:r6', 'ex:noTransferUS')]).
step(t('ex:policy', 'odrl:prohibition', 'ex:noTransferUS'), fact(28), [], []).
step(applies('ex:r6', 'ex:noTransferUS'), rule(70), [=('P', 'ex:r6'), =('Rule', 'ex:noTransferUS'), =('Why', EYE_57_68_79_23_32_34_32)], [addresses('ex:r6', 'ex:noTransferUS'), findall(EYE_57_68_79_23_32_34_32, unmet('ex:r6', 'ex:noTransferUS', EYE_57_68_79_23_32_34_32), [])]).
step(addresses('ex:r6', 'ex:noTransferUS'), rule(67), [=('P', 'ex:r6'), =('Rule', 'ex:noTransferUS'), =('Who', 'ex:partnerUS'), =('Assignee', 'ex:partnerUS'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r6', 'ex:requestedBy', 'ex:partnerUS'), t('ex:noTransferUS', 'odrl:assignee', 'ex:partnerUS'), party('ex:partnerUS', 'ex:partnerUS'), t('ex:r6', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:noTransferUS', 'odrl:action', 'odrl:use'), t('ex:r6', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:noTransferUS', 'odrl:target', 'ex:labResults')]).
step(t('ex:r6', 'ex:requestedBy', 'ex:partnerUS'), rule(45), [=('P', 'ex:r6'), =('Who', 'ex:partnerUS'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:AcademicResearch'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:noTransferUS', 'odrl:assignee', 'ex:partnerUS'), fact(29), [], []).
step(party('ex:partnerUS', 'ex:partnerUS'), fact(65), [=('Who', 'ex:partnerUS')], []).
step(t('ex:r6', 'dpv:hasProcessing', 'dpv:Use'), rule(46), [=('P', 'ex:r6'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerUS'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:AcademicResearch'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(action('dpv:Use', 'odrl:use'), fact(53), [], []).
step(t('ex:noTransferUS', 'odrl:action', 'odrl:use'), fact(30), [], []).
step(t('ex:r6', 'dpv:hasPersonalData', 'ex:labResults'), rule(47), [=('P', 'ex:r6'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerUS'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:AcademicResearch'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:noTransferUS', 'odrl:target', 'ex:labResults'), fact(31), [], []).
step(findall(EYE_57_68_79_23_32_34_32, unmet('ex:r6', 'ex:noTransferUS', EYE_57_68_79_23_32_34_32), []), collected, [], []).
step(conflict('ex:r6', resolved_by('odrl:prohibit', 'ex:noTransferUS', overrides('ex:research'))), rule(76), [=('P', 'ex:r6'), =('Prohibition', 'ex:noTransferUS'), =('Permission', 'ex:research')], [t('ex:policy', 'odrl:conflict', 'odrl:prohibit'), t('ex:r6', 'rdf:type', 'dpv:Process'), permitted('ex:r6', 'ex:research'), prohibited('ex:r6', 'ex:noTransferUS')]).
step(t('ex:policy', 'odrl:conflict', 'odrl:prohibit'), fact(10), [], []).
step(permitted('ex:r6', 'ex:research'), rule(71), [=('P', 'ex:r6'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), applies('ex:r6', 'ex:research')]).
step(t('ex:policy', 'odrl:permission', 'ex:research'), fact(11), [], []).
step(applies('ex:r6', 'ex:research'), rule(70), [=('P', 'ex:r6'), =('Rule', 'ex:research'), =('Why', EYE_57_68_79_23_38_31_30)], [addresses('ex:r6', 'ex:research'), findall(EYE_57_68_79_23_38_31_30, unmet('ex:r6', 'ex:research', EYE_57_68_79_23_38_31_30), [])]).
step(addresses('ex:r6', 'ex:research'), rule(67), [=('P', 'ex:r6'), =('Rule', 'ex:research'), =('Who', 'ex:partnerUS'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r6', 'ex:requestedBy', 'ex:partnerUS'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerUS', 'ex:consortium'), t('ex:r6', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r6', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:research', 'odrl:assignee', 'ex:consortium'), fact(12), [], []).
step(party('ex:partnerUS', 'ex:consortium'), rule(66), [=('Who', 'ex:partnerUS'), =('Group', 'ex:consortium')], [t('ex:partnerUS', 'odrl:partOf', 'ex:consortium')]).
step(t('ex:partnerUS', 'odrl:partOf', 'ex:consortium'), fact(6), [], []).
step(t('ex:research', 'odrl:action', 'odrl:use'), fact(13), [], []).
step(t('ex:research', 'odrl:target', 'ex:labResults'), fact(14), [], []).
step(findall(EYE_57_68_79_23_38_31_30, unmet('ex:r6', 'ex:research', EYE_57_68_79_23_38_31_30), []), collected, [], []).
step(decision('ex:r1', permit('ex:research')), rule(73), [=('P', 'ex:r1'), =('Rule', 'ex:research'), =('R', EYE_52_23_31_39_37_37)], [t('ex:r1', 'rdf:type', 'dpv:Process'), permitted('ex:r1', 'ex:research'), findall(EYE_52_23_31_39_37_37, prohibited('ex:r1', EYE_52_23_31_39_37_37), [])]).
step(t('ex:r1', 'rdf:type', 'dpv:Process'), rule(44), [=('P', 'ex:r1'), =('__anon0', 'ex:partnerBE'), =('__anon1', 'dpv:Use'), =('__anon2', 'ex:labResults'), =('__anon3', 'dpv:AcademicResearch'), =('__anon4', 'dpv:ConsentGiven'), =('__anon5', 'dpv:Pseudonymisation'), =('__anon6', 20261115)], [process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(38), [], []).
step(permitted('ex:r1', 'ex:research'), rule(71), [=('P', 'ex:r1'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), applies('ex:r1', 'ex:research')]).
step(applies('ex:r1', 'ex:research'), rule(70), [=('P', 'ex:r1'), =('Rule', 'ex:research'), =('Why', EYE_57_68_79_23_31_39_38_34)], [addresses('ex:r1', 'ex:research'), findall(EYE_57_68_79_23_31_39_38_34, unmet('ex:r1', 'ex:research', EYE_57_68_79_23_31_39_38_34), [])]).
step(addresses('ex:r1', 'ex:research'), rule(67), [=('P', 'ex:r1'), =('Rule', 'ex:research'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r1', 'ex:requestedBy', 'ex:partnerBE'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r1', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r1', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r1', 'ex:requestedBy', 'ex:partnerBE'), rule(45), [=('P', 'ex:r1'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:AcademicResearch'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r1', 'dpv:hasProcessing', 'dpv:Use'), rule(46), [=('P', 'ex:r1'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:AcademicResearch'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r1', 'dpv:hasPersonalData', 'ex:labResults'), rule(47), [=('P', 'ex:r1'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:AcademicResearch'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(findall(EYE_57_68_79_23_31_39_38_34, unmet('ex:r1', 'ex:research', EYE_57_68_79_23_31_39_38_34), []), collected, [], []).
step(findall(EYE_52_23_31_39_37_37, prohibited('ex:r1', EYE_52_23_31_39_37_37), []), collected, [], []).
step(decision('ex:r2', deny(not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')]))), rule(75), [=('P', 'ex:r2'), =('Reasons', [unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')]), =('R', EYE_52_23_32_36_37_32), =('Why', EYE_57_68_79_23_32_36_37_32), =('Rule', EYE_52_75_6c_65_23_32_36_37_32)], [t('ex:r2', 'rdf:type', 'dpv:Process'), findall(EYE_52_23_32_36_37_32, permitted('ex:r2', EYE_52_23_32_36_37_32), []), findall(EYE_52_23_32_36_37_32, prohibited('ex:r2', EYE_52_23_32_36_37_32), []), findall(EYE_57_68_79_23_32_36_37_32, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_32_36_37_32), unmet('ex:r2', EYE_52_75_6c_65_23_32_36_37_32, EYE_57_68_79_23_32_36_37_32)), [unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])]).
step(t('ex:r2', 'rdf:type', 'dpv:Process'), rule(44), [=('P', 'ex:r2'), =('__anon0', 'ex:partnerBE'), =('__anon1', 'dpv:Use'), =('__anon2', 'ex:labResults'), =('__anon3', 'dpv:PersonalisedAdvertising'), =('__anon4', 'dpv:ConsentGiven'), =('__anon5', 'dpv:Pseudonymisation'), =('__anon6', 20261115)], [process('ex:r2', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:PersonalisedAdvertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r2', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:PersonalisedAdvertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(39), [], []).
step(findall(EYE_52_23_32_36_37_32, permitted('ex:r2', EYE_52_23_32_36_37_32), []), collected, [], []).
step(findall(EYE_52_23_32_36_37_32, prohibited('ex:r2', EYE_52_23_32_36_37_32), []), collected, [], []).
step(findall(EYE_57_68_79_23_32_36_37_32, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_32_36_37_32), unmet('ex:r2', EYE_52_75_6c_65_23_32_36_37_32, EYE_57_68_79_23_32_36_37_32)), [unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')]), collected, [], []).
step(decision('ex:r4', deny(not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')]))), rule(75), [=('P', 'ex:r4'), =('Reasons', [unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')]), =('R', EYE_52_23_32_36_37_32), =('Why', EYE_57_68_79_23_32_36_37_32), =('Rule', EYE_52_75_6c_65_23_32_36_37_32)], [t('ex:r4', 'rdf:type', 'dpv:Process'), findall(EYE_52_23_32_36_37_32, permitted('ex:r4', EYE_52_23_32_36_37_32), []), findall(EYE_52_23_32_36_37_32, prohibited('ex:r4', EYE_52_23_32_36_37_32), []), findall(EYE_57_68_79_23_32_36_37_32, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_32_36_37_32), unmet('ex:r4', EYE_52_75_6c_65_23_32_36_37_32, EYE_57_68_79_23_32_36_37_32)), [unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])]).
step(t('ex:r4', 'rdf:type', 'dpv:Process'), rule(44), [=('P', 'ex:r4'), =('__anon0', 'ex:partnerBE'), =('__anon1', 'dpv:Use'), =('__anon2', 'ex:labResults'), =('__anon3', 'dpv:CommercialResearch'), =('__anon4', 'dpv:ConsentWithdrawn'), =('__anon5', 'dpv:Pseudonymisation'), =('__anon6', 20261115)], [process('ex:r4', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:CommercialResearch', 'dpv:ConsentWithdrawn', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r4', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:CommercialResearch', 'dpv:ConsentWithdrawn', 'dpv:Pseudonymisation', 20261115), fact(41), [], []).
step(findall(EYE_52_23_32_36_37_32, permitted('ex:r4', EYE_52_23_32_36_37_32), []), collected, [], []).
step(findall(EYE_52_23_32_36_37_32, prohibited('ex:r4', EYE_52_23_32_36_37_32), []), collected, [], []).
step(findall(EYE_57_68_79_23_32_36_37_32, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_32_36_37_32), unmet('ex:r4', EYE_52_75_6c_65_23_32_36_37_32, EYE_57_68_79_23_32_36_37_32)), [unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')]), collected, [], []).
step(decision('ex:r5', deny(not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)]))), rule(75), [=('P', 'ex:r5'), =('Reasons', [unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)]), =('R', EYE_52_23_32_36_37_32), =('Why', EYE_57_68_79_23_32_36_37_32), =('Rule', EYE_52_75_6c_65_23_32_36_37_32)], [t('ex:r5', 'rdf:type', 'dpv:Process'), findall(EYE_52_23_32_36_37_32, permitted('ex:r5', EYE_52_23_32_36_37_32), []), findall(EYE_52_23_32_36_37_32, prohibited('ex:r5', EYE_52_23_32_36_37_32), []), findall(EYE_57_68_79_23_32_36_37_32, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_32_36_37_32), unmet('ex:r5', EYE_52_75_6c_65_23_32_36_37_32, EYE_57_68_79_23_32_36_37_32)), [unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])]).
step(t('ex:r5', 'rdf:type', 'dpv:Process'), rule(44), [=('P', 'ex:r5'), =('__anon0', 'ex:partnerBE'), =('__anon1', 'dpv:Use'), =('__anon2', 'ex:labResults'), =('__anon3', 'dpv:AcademicResearch'), =('__anon4', 'dpv:ConsentGiven'), =('__anon5', 'dpv:Encryption'), =('__anon6', 20270301)], [process('ex:r5', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Encryption', 20270301)]).
step(process('ex:r5', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Encryption', 20270301), fact(42), [], []).
step(findall(EYE_52_23_32_36_37_32, permitted('ex:r5', EYE_52_23_32_36_37_32), []), collected, [], []).
step(findall(EYE_52_23_32_36_37_32, prohibited('ex:r5', EYE_52_23_32_36_37_32), []), collected, [], []).
step(findall(EYE_57_68_79_23_32_36_37_32, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_32_36_37_32), unmet('ex:r5', EYE_52_75_6c_65_23_32_36_37_32, EYE_57_68_79_23_32_36_37_32)), [unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)]), collected, [], []).
step(duty('ex:r1', 'odrl:delete', within_days(90)), rule(77), [=('P', 'ex:r1'), =('Action', 'odrl:delete'), =('Days', 90), =('Rule', 'ex:research'), =('Duty', 'ex:deletion')], [decision('ex:r1', permit('ex:research')), t('ex:research', 'odrl:duty', 'ex:deletion'), t('ex:deletion', 'odrl:action', 'odrl:delete'), t('ex:deletion', 'ex:withinDays', 90)]).
step(t('ex:research', 'odrl:duty', 'ex:deletion'), fact(20), [], []).
step(t('ex:deletion', 'odrl:action', 'odrl:delete'), fact(21), [], []).
step(t('ex:deletion', 'ex:withinDays', 90), fact(22), [], []).
