assessment(directive_2015, c7, refused_by_terms([unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]), basis(['ex:terms'])).
assessment(directive_2015, c8, refused_by_terms([unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')]), basis(['ex:terms'])).
assessment(revised_2026, c7, refused_by_terms([unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]), basis(['ex:terms'])).
assessment(revised_2026, c8, refused_by_terms([unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')]), basis(['ex:terms'])).
assessment(directive_2015, c1, pay_fee(percent(25), fee(600), refund(1800), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c2, pay_fee(percent(100), fee(1800), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c3, refund(1500, within_days(14)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c4, pay_fee(percent(100), fee(2100), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c5, refund(1200, within_days(14)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c6, voucher(value(1600), terms(as_agreed)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD 2015: no voucher rules'])).
assessment(revised_2026, c1, pay_fee(percent(25), fee(600), refund(1800), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(revised_2026, c2, pay_fee(percent(100), fee(1800), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(revised_2026, c3, refund(1500, within_days(14)), basis(['ex:terms', 'revised PTD: destination', 'PTD Art. 12(4)'])).
assessment(revised_2026, c4, refund(2100, within_days(14)), basis(['ex:terms', 'revised PTD: point of departure', 'PTD Art. 12(4)'])).
assessment(revised_2026, c5, refund(1200, within_days(14)), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])).
assessment(revised_2026, c6, voucher(value(1600), valid_months(12), unused_value_refunded), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])).
complaint_plan(directive_2015, k1, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])).
complaint_plan(directive_2015, k2, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])).
complaint_plan(revised_2026, k1, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])).
complaint_plan(revised_2026, k2, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])).
changed(cancellation(c4), from(pay_fee(percent(100), fee(2100), refund(0), within_days(14))), to(refund(2100, within_days(14)))).
changed(cancellation(c6), from(voucher(value(1600), terms(as_agreed))), to(voucher(value(1600), valid_months(12), unused_value_refunded))).
changed(complaint(k1), from(deadlines(set_by_national_law)), to(deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))).
changed(complaint(k2), from(deadlines(set_by_national_law)), to(deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))).

clause(1, regime(directive_2015), true).
clause(2, regime(revised_2026), true).
clause(3, t('ex:terms', 'rdf:type', 'odrl:Offer'), true).
clause(4, t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), true).
clause(5, t('ex:terms', 'odrl:permission', 'ex:cancellation'), true).
clause(6, t('ex:cancellation', 'odrl:action', 'ex:cancel'), true).
clause(7, t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), true).
clause(8, t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), true).
clause(9, t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), true).
clause(10, t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), true).
clause(11, t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), true).
clause(12, t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), true).
clause(13, t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), true).
clause(14, t('ex:beforeDeparture', 'odrl:rightOperand', 0), true).
clause(15, t('ex:cancellation', 'odrl:duty', 'ex:fee'), true).
clause(16, t('ex:fee', 'odrl:action', 'odrl:compensate'), true).
clause(17, t('ex:fee', 'ex:feeScale', [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)]), true).
clause(18, booking(bk1, operator('ex:sunTrips'), lead(anna), price(2400)), true).
clause(19, booking(bk2, operator('ex:sunTrips'), lead(ben), price(1800)), true).
clause(20, booking(bk3, operator('ex:sunTrips'), lead(chloe), price(1500)), true).
clause(21, booking(bk4, operator('ex:sunTrips'), lead(david), price(2100)), true).
clause(22, booking(bk5, operator('ex:sunTrips'), lead(emma), price(1200)), true).
clause(23, booking(bk6, operator('ex:sunTrips'), lead(farid), price(1600)), true).
clause(24, booking(bk7, operator('ex:sunTrips'), lead(gina), price(900)), true).
clause(25, booking(bk8, operator('ex:sunTrips'), lead(ivy), price(1300)), true).
clause(26, request(c1, bk1, by(anna), 'ex:cancel', days(90), circumstances(none), voucher(not_offered)), true).
clause(27, request(c2, bk2, by(ben), 'ex:cancel', days(20), circumstances(none), voucher(not_offered)), true).
clause(28, request(c3, bk3, by(chloe), 'ex:cancel', days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), true).
clause(29, request(c4, bk4, by(david), 'ex:cancel', days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), true).
clause(30, request(c5, bk5, by(emma), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), true).
clause(31, request(c6, bk6, by(farid), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), true).
clause(32, request(c7, bk7, by(gina), 'ex:cancel', days(-2), circumstances(none), voucher(not_offered)), true).
clause(33, request(c8, bk8, by(hugo), 'ex:cancel', days(40), circumstances(none), voucher(not_offered)), true).
clause(34, value(var('C'), 'ex:requesterRole', 'ex:leadTraveller'), ','(request(var('C'), var('B'), by(var('X')), var('__anon0'), var('__anon1'), var('__anon2'), var('__anon3')), booking(var('B'), var('__anon4'), lead(var('X')), var('__anon5')))).
clause(35, value(var('C'), 'ex:requesterRole', 'ex:otherPerson'), ','(request(var('C'), var('B'), by(var('X')), var('__anon6'), var('__anon7'), var('__anon8'), var('__anon9')), ','(booking(var('B'), var('__anon10'), lead(var('L')), var('__anon11')), \==(var('X'), var('L'))))).
clause(36, value(var('C'), 'ex:daysBeforeDeparture', var('D')), request(var('C'), var('__anon12'), var('__anon13'), var('__anon14'), days(var('D')), var('__anon15'), var('__anon16'))).
clause(37, compare('odrl:eq', var('V'), var('R'), true), ==(var('V'), var('R'))).
clause(38, compare('odrl:eq', var('V'), var('R'), false), \==(var('V'), var('R'))).
clause(39, compare('odrl:gt', var('V'), var('R'), true), >(var('V'), var('R'))).
clause(40, compare('odrl:gt', var('V'), var('R'), false), =<(var('V'), var('R'))).
clause(41, addresses(var('C'), var('Rule')), ','(t(var('Offer'), 'rdf:type', 'odrl:Offer'), ','(t(var('Offer'), 'odrl:assigner', var('Operator')), ','(t(var('Offer'), 'odrl:permission', var('Rule')), ','(t(var('Rule'), 'odrl:action', var('Action')), ','(request(var('C'), var('B'), var('__anon17'), var('Action'), var('__anon18'), var('__anon19'), var('__anon20')), booking(var('B'), operator(var('Operator')), var('__anon21'), var('__anon22')))))))).
clause(42, condition(var('C'), var('K'), var('Result')), ','(t(var('K'), 'odrl:leftOperand', var('Left')), ','(t(var('K'), 'odrl:operator', var('Op')), ','(t(var('K'), 'odrl:rightOperand', var('Right')), ','(value(var('C'), var('Left'), var('V')), ','(compare(var('Op'), var('V'), var('Right'), var('Holds')), result(var('Holds'), var('K'), var('Left'), var('V'), var('Op'), var('Right'), var('Result')))))))).
clause(43, result(true, var('__anon23'), var('__anon24'), var('__anon25'), var('__anon26'), var('__anon27'), met), true).
clause(44, result(false, var('K'), var('Left'), var('V'), var('Op'), var('Right'), unmet(var('K'), var('Left'), var('V'), var('Op'), var('Right'))), true).
clause(45, unmet(var('__anon28'), [], []), true).
clause(46, unmet(var('C'), [var('K')|var('Ks')], var('Reasons')), ','(condition(var('C'), var('K'), met), unmet(var('C'), var('Ks'), var('Reasons')))).
clause(47, unmet(var('C'), [var('K')|var('Ks')], [var('Why')|var('Reasons')]), ','(condition(var('C'), var('K'), var('Why')), ','(\==(var('Why'), met), unmet(var('C'), var('Ks'), var('Reasons'))))).
clause(48, policy_result(var('C'), permit(var('Rule'))), ','(addresses(var('C'), var('Rule')), ','(t(var('Rule'), 'odrl:constraint', var('X')), ','(t(var('X'), 'odrl:and', var('Ks')), unmet(var('C'), var('Ks'), []))))).
clause(49, policy_result(var('C'), refuse(var('Reasons'))), ','(addresses(var('C'), var('Rule')), ','(t(var('Rule'), 'odrl:constraint', var('X')), ','(t(var('X'), 'odrl:and', var('Ks')), ','(unmet(var('C'), var('Ks'), var('Reasons')), \==(var('Reasons'), [])))))).
clause(50, fee_percent(var('Rule'), var('D'), var('Pct')), ','(t(var('Rule'), 'odrl:duty', var('Duty')), ','(t(var('Duty'), 'odrl:action', 'odrl:compensate'), ','(t(var('Duty'), 'ex:feeScale', var('Bands')), band(var('D'), var('Bands'), var('Pct')))))).
clause(51, band(var('D'), [band(var('Min'), var('Max'), var('Pct'))|var('__anon29')], var('Pct')), ','(=<(var('Min'), var('D')), =<(var('D'), var('Max')))).
clause(52, band(var('D'), [band(var('Min'), var('__anon30'), var('__anon31'))|var('Bands')], var('Pct')), ','(<(var('D'), var('Min')), band(var('D'), var('Bands'), var('Pct')))).
clause(53, free_cancellation(directive_2015, none, no, 'PTD Art. 12(1)'), true).
clause(54, free_cancellation(directive_2015, at(destination, var('__anon32')), yes, 'PTD Art. 12(2)'), true).
clause(55, free_cancellation(directive_2015, at(departure, var('__anon33')), no, 'PTD Art. 12(1)'), true).
clause(56, free_cancellation(revised_2026, none, no, 'PTD Art. 12(1)'), true).
clause(57, free_cancellation(revised_2026, at(destination, var('__anon34')), yes, 'revised PTD: destination'), true).
clause(58, free_cancellation(revised_2026, at(departure, var('__anon35')), yes, 'revised PTD: point of departure'), true).
clause(59, settle(var('__anon36'), no, var('Rule'), var('P'), var('D'), var('__anon37'), pay_fee(percent(var('Pct')), fee(var('F')), refund(var('Back')), within_days(14))), ','(fee_percent(var('Rule'), var('D'), var('Pct')), ','(is(var('F'), //(*(var('P'), var('Pct')), 100)), is(var('Back'), -(var('P'), var('F')))))).
clause(60, settle(var('__anon38'), yes, var('__anon39'), var('P'), var('__anon40'), not_offered, refund(var('P'), within_days(14))), true).
clause(61, settle(var('__anon41'), yes, var('__anon42'), var('P'), var('__anon43'), offered(refused), refund(var('P'), within_days(14))), true).
clause(62, settle(directive_2015, yes, var('__anon44'), var('P'), var('__anon45'), offered(accepted), voucher(value(var('P')), terms(as_agreed))), true).
clause(63, settle(revised_2026, yes, var('__anon46'), var('P'), var('__anon47'), offered(accepted), voucher(value(var('P')), valid_months(12), unused_value_refunded)), true).
clause(64, money_basis(var('__anon48'), no, var('__anon49'), 'PTD Art. 12(4)'), true).
clause(65, money_basis(var('__anon50'), yes, not_offered, 'PTD Art. 12(4)'), true).
clause(66, money_basis(directive_2015, yes, offered(refused), 'PTD Art. 12(4)'), true).
clause(67, money_basis(directive_2015, yes, offered(accepted), 'PTD 2015: no voucher rules'), true).
clause(68, money_basis(revised_2026, yes, offered(var('__anon51')), 'revised PTD: vouchers'), true).
clause(69, assessment(var('R'), var('C'), refused_by_terms(var('Reasons')), basis(['ex:terms'])), ','(regime(var('R')), policy_result(var('C'), refuse(var('Reasons'))))).
clause(70, assessment(var('R'), var('C'), var('Outcome'), basis(['ex:terms', var('Free'), var('Money')])), ','(regime(var('R')), ','(policy_result(var('C'), permit(var('Rule'))), ','(request(var('C'), var('B'), var('__anon52'), var('__anon53'), days(var('D')), circumstances(var('What')), voucher(var('V'))), ','(booking(var('B'), var('__anon54'), var('__anon55'), price(var('P'))), ','(free_cancellation(var('R'), var('What'), var('F'), var('Free')), ','(settle(var('R'), var('F'), var('Rule'), var('P'), var('D'), var('V'), var('Outcome')), money_basis(var('R'), var('F'), var('V'), var('Money'))))))))).
clause(71, complaint(k1, 'pool closed for the whole stay'), true).
clause(72, complaint(k2, 'refund not received'), true).
clause(73, complaint_plan(directive_2015, var('K'), deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), complaint(var('K'), var('__anon56'))).
clause(74, complaint_plan(revised_2026, var('K'), deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), complaint(var('K'), var('__anon57'))).
clause(75, changed(cancellation(var('C')), from(var('Old')), to(var('New'))), ','(assessment(directive_2015, var('C'), var('Old'), var('__anon58')), ','(assessment(revised_2026, var('C'), var('New'), var('__anon59')), \==(var('Old'), var('New'))))).
clause(76, changed(complaint(var('K')), from(var('Old')), to(var('New'))), ','(complaint_plan(directive_2015, var('K'), var('Old'), var('__anon60')), ','(complaint_plan(revised_2026, var('K'), var('New'), var('__anon61')), \==(var('Old'), var('New'))))).

step(assessment(directive_2015, c7, refused_by_terms([unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]), basis(['ex:terms'])), rule(69), [=('R', directive_2015), =('C', c7), =('Reasons', [unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)])], [regime(directive_2015), policy_result(c7, refuse([unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]))]).
step(regime(directive_2015), fact(1), [], []).
step(policy_result(c7, refuse([unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)])), rule(49), [=('C', c7), =('Reasons', [unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]), =('Rule', 'ex:cancellation'), =('X', 'ex:conditions'), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [addresses(c7, 'ex:cancellation'), t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c7, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]), \==([unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)], [])]).
step(addresses(c7, 'ex:cancellation'), rule(41), [=('C', c7), =('Rule', 'ex:cancellation'), =('Offer', 'ex:terms'), =('Operator', 'ex:sunTrips'), =('Action', 'ex:cancel'), =('B', bk7), =('__anon17', by(gina)), =('__anon18', days(-2)), =('__anon19', circumstances(none)), =('__anon20', voucher(not_offered)), =('__anon21', lead(gina)), =('__anon22', price(900))], [t('ex:terms', 'rdf:type', 'odrl:Offer'), t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), t('ex:terms', 'odrl:permission', 'ex:cancellation'), t('ex:cancellation', 'odrl:action', 'ex:cancel'), request(c7, bk7, by(gina), 'ex:cancel', days(-2), circumstances(none), voucher(not_offered)), booking(bk7, operator('ex:sunTrips'), lead(gina), price(900))]).
step(t('ex:terms', 'rdf:type', 'odrl:Offer'), fact(3), [], []).
step(t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), fact(4), [], []).
step(t('ex:terms', 'odrl:permission', 'ex:cancellation'), fact(5), [], []).
step(t('ex:cancellation', 'odrl:action', 'ex:cancel'), fact(6), [], []).
step(request(c7, bk7, by(gina), 'ex:cancel', days(-2), circumstances(none), voucher(not_offered)), fact(32), [], []).
step(booking(bk7, operator('ex:sunTrips'), lead(gina), price(900)), fact(24), [], []).
step(t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), fact(7), [], []).
step(t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), fact(8), [], []).
step(unmet(c7, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]), rule(46), [=('C', c7), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)])], [condition(c7, 'ex:byLeadTraveller', met), unmet(c7, ['ex:beforeDeparture'], [unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)])]).
step(condition(c7, 'ex:byLeadTraveller', met), rule(42), [=('C', c7), =('K', 'ex:byLeadTraveller'), =('Result', met), =('Left', 'ex:requesterRole'), =('Op', 'odrl:eq'), =('Right', 'ex:leadTraveller'), =('V', 'ex:leadTraveller'), =('Holds', true)], [t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), value(c7, 'ex:requesterRole', 'ex:leadTraveller'), compare('odrl:eq', 'ex:leadTraveller', 'ex:leadTraveller', true), result(true, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:leadTraveller', 'odrl:eq', 'ex:leadTraveller', met)]).
step(t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), fact(9), [], []).
step(t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), fact(10), [], []).
step(t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), fact(11), [], []).
step(value(c7, 'ex:requesterRole', 'ex:leadTraveller'), rule(34), [=('C', c7), =('B', bk7), =('X', gina), =('__anon0', 'ex:cancel'), =('__anon1', days(-2)), =('__anon2', circumstances(none)), =('__anon3', voucher(not_offered)), =('__anon4', operator('ex:sunTrips')), =('__anon5', price(900))], [request(c7, bk7, by(gina), 'ex:cancel', days(-2), circumstances(none), voucher(not_offered)), booking(bk7, operator('ex:sunTrips'), lead(gina), price(900))]).
step(compare('odrl:eq', 'ex:leadTraveller', 'ex:leadTraveller', true), rule(37), [=('V', 'ex:leadTraveller'), =('R', 'ex:leadTraveller')], [==('ex:leadTraveller', 'ex:leadTraveller')]).
step(==('ex:leadTraveller', 'ex:leadTraveller'), builtin, [], []).
step(result(true, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:leadTraveller', 'odrl:eq', 'ex:leadTraveller', met), fact(43), [=('__anon23', 'ex:byLeadTraveller'), =('__anon24', 'ex:requesterRole'), =('__anon25', 'ex:leadTraveller'), =('__anon26', 'odrl:eq'), =('__anon27', 'ex:leadTraveller')], []).
step(unmet(c7, ['ex:beforeDeparture'], [unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]), rule(47), [=('C', c7), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Why', unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)), =('Reasons', [])], [condition(c7, 'ex:beforeDeparture', unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)), \==(unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0), met), unmet(c7, [], [])]).
step(condition(c7, 'ex:beforeDeparture', unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)), rule(42), [=('C', c7), =('K', 'ex:beforeDeparture'), =('Result', unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)), =('Left', 'ex:daysBeforeDeparture'), =('Op', 'odrl:gt'), =('Right', 0), =('V', -2), =('Holds', false)], [t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), t('ex:beforeDeparture', 'odrl:rightOperand', 0), value(c7, 'ex:daysBeforeDeparture', -2), compare('odrl:gt', -2, 0, false), result(false, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0, unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0))]).
step(t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), fact(12), [], []).
step(t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), fact(13), [], []).
step(t('ex:beforeDeparture', 'odrl:rightOperand', 0), fact(14), [], []).
step(value(c7, 'ex:daysBeforeDeparture', -2), rule(36), [=('C', c7), =('D', -2), =('__anon12', bk7), =('__anon13', by(gina)), =('__anon14', 'ex:cancel'), =('__anon15', circumstances(none)), =('__anon16', voucher(not_offered))], [request(c7, bk7, by(gina), 'ex:cancel', days(-2), circumstances(none), voucher(not_offered))]).
step(compare('odrl:gt', -2, 0, false), rule(40), [=('V', -2), =('R', 0)], [=<(-2, 0)]).
step(=<(-2, 0), builtin, [], []).
step(result(false, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0, unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)), fact(44), [=('K', 'ex:beforeDeparture'), =('Left', 'ex:daysBeforeDeparture'), =('V', -2), =('Op', 'odrl:gt'), =('Right', 0)], []).
step(\==(unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0), met), builtin, [], []).
step(unmet(c7, [], []), fact(45), [=('__anon28', c7)], []).
step(\==([unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)], []), builtin, [], []).
step(assessment(directive_2015, c8, refused_by_terms([unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')]), basis(['ex:terms'])), rule(69), [=('R', directive_2015), =('C', c8), =('Reasons', [unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')])], [regime(directive_2015), policy_result(c8, refuse([unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')]))]).
step(policy_result(c8, refuse([unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')])), rule(49), [=('C', c8), =('Reasons', [unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')]), =('Rule', 'ex:cancellation'), =('X', 'ex:conditions'), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [addresses(c8, 'ex:cancellation'), t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c8, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')]), \==([unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')], [])]).
step(addresses(c8, 'ex:cancellation'), rule(41), [=('C', c8), =('Rule', 'ex:cancellation'), =('Offer', 'ex:terms'), =('Operator', 'ex:sunTrips'), =('Action', 'ex:cancel'), =('B', bk8), =('__anon17', by(hugo)), =('__anon18', days(40)), =('__anon19', circumstances(none)), =('__anon20', voucher(not_offered)), =('__anon21', lead(ivy)), =('__anon22', price(1300))], [t('ex:terms', 'rdf:type', 'odrl:Offer'), t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), t('ex:terms', 'odrl:permission', 'ex:cancellation'), t('ex:cancellation', 'odrl:action', 'ex:cancel'), request(c8, bk8, by(hugo), 'ex:cancel', days(40), circumstances(none), voucher(not_offered)), booking(bk8, operator('ex:sunTrips'), lead(ivy), price(1300))]).
step(request(c8, bk8, by(hugo), 'ex:cancel', days(40), circumstances(none), voucher(not_offered)), fact(33), [], []).
step(booking(bk8, operator('ex:sunTrips'), lead(ivy), price(1300)), fact(25), [], []).
step(unmet(c8, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')]), rule(47), [=('C', c8), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Why', unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')), =('Reasons', [])], [condition(c8, 'ex:byLeadTraveller', unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')), \==(unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller'), met), unmet(c8, ['ex:beforeDeparture'], [])]).
step(condition(c8, 'ex:byLeadTraveller', unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')), rule(42), [=('C', c8), =('K', 'ex:byLeadTraveller'), =('Result', unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')), =('Left', 'ex:requesterRole'), =('Op', 'odrl:eq'), =('Right', 'ex:leadTraveller'), =('V', 'ex:otherPerson'), =('Holds', false)], [t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), value(c8, 'ex:requesterRole', 'ex:otherPerson'), compare('odrl:eq', 'ex:otherPerson', 'ex:leadTraveller', false), result(false, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller', unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller'))]).
step(value(c8, 'ex:requesterRole', 'ex:otherPerson'), rule(35), [=('C', c8), =('B', bk8), =('X', hugo), =('__anon6', 'ex:cancel'), =('__anon7', days(40)), =('__anon8', circumstances(none)), =('__anon9', voucher(not_offered)), =('__anon10', operator('ex:sunTrips')), =('L', ivy), =('__anon11', price(1300))], [request(c8, bk8, by(hugo), 'ex:cancel', days(40), circumstances(none), voucher(not_offered)), booking(bk8, operator('ex:sunTrips'), lead(ivy), price(1300)), \==(hugo, ivy)]).
step(\==(hugo, ivy), builtin, [], []).
step(compare('odrl:eq', 'ex:otherPerson', 'ex:leadTraveller', false), rule(38), [=('V', 'ex:otherPerson'), =('R', 'ex:leadTraveller')], [\==('ex:otherPerson', 'ex:leadTraveller')]).
step(\==('ex:otherPerson', 'ex:leadTraveller'), builtin, [], []).
step(result(false, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller', unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')), fact(44), [=('K', 'ex:byLeadTraveller'), =('Left', 'ex:requesterRole'), =('V', 'ex:otherPerson'), =('Op', 'odrl:eq'), =('Right', 'ex:leadTraveller')], []).
step(\==(unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller'), met), builtin, [], []).
step(unmet(c8, ['ex:beforeDeparture'], []), rule(46), [=('C', c8), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [condition(c8, 'ex:beforeDeparture', met), unmet(c8, [], [])]).
step(condition(c8, 'ex:beforeDeparture', met), rule(42), [=('C', c8), =('K', 'ex:beforeDeparture'), =('Result', met), =('Left', 'ex:daysBeforeDeparture'), =('Op', 'odrl:gt'), =('Right', 0), =('V', 40), =('Holds', true)], [t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), t('ex:beforeDeparture', 'odrl:rightOperand', 0), value(c8, 'ex:daysBeforeDeparture', 40), compare('odrl:gt', 40, 0, true), result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 40, 'odrl:gt', 0, met)]).
step(value(c8, 'ex:daysBeforeDeparture', 40), rule(36), [=('C', c8), =('D', 40), =('__anon12', bk8), =('__anon13', by(hugo)), =('__anon14', 'ex:cancel'), =('__anon15', circumstances(none)), =('__anon16', voucher(not_offered))], [request(c8, bk8, by(hugo), 'ex:cancel', days(40), circumstances(none), voucher(not_offered))]).
step(compare('odrl:gt', 40, 0, true), rule(39), [=('V', 40), =('R', 0)], [>(40, 0)]).
step(>(40, 0), builtin, [], []).
step(result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 40, 'odrl:gt', 0, met), fact(43), [=('__anon23', 'ex:beforeDeparture'), =('__anon24', 'ex:daysBeforeDeparture'), =('__anon25', 40), =('__anon26', 'odrl:gt'), =('__anon27', 0)], []).
step(unmet(c8, [], []), fact(45), [=('__anon28', c8)], []).
step(\==([unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')], []), builtin, [], []).
step(assessment(revised_2026, c7, refused_by_terms([unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]), basis(['ex:terms'])), rule(69), [=('R', revised_2026), =('C', c7), =('Reasons', [unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)])], [regime(revised_2026), policy_result(c7, refuse([unmet('ex:beforeDeparture', 'ex:daysBeforeDeparture', -2, 'odrl:gt', 0)]))]).
step(regime(revised_2026), fact(2), [], []).
step(assessment(revised_2026, c8, refused_by_terms([unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')]), basis(['ex:terms'])), rule(69), [=('R', revised_2026), =('C', c8), =('Reasons', [unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')])], [regime(revised_2026), policy_result(c8, refuse([unmet('ex:byLeadTraveller', 'ex:requesterRole', 'ex:otherPerson', 'odrl:eq', 'ex:leadTraveller')]))]).
step(assessment(directive_2015, c1, pay_fee(percent(25), fee(600), refund(1800), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(70), [=('R', directive_2015), =('C', c1), =('Outcome', pay_fee(percent(25), fee(600), refund(1800), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('Rule', 'ex:cancellation'), =('B', bk1), =('__anon52', by(anna)), =('__anon53', 'ex:cancel'), =('D', 90), =('What', none), =('V', not_offered), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(anna)), =('P', 2400), =('F', no)], [regime(directive_2015), policy_result(c1, permit('ex:cancellation')), request(c1, bk1, by(anna), 'ex:cancel', days(90), circumstances(none), voucher(not_offered)), booking(bk1, operator('ex:sunTrips'), lead(anna), price(2400)), free_cancellation(directive_2015, none, no, 'PTD Art. 12(1)'), settle(directive_2015, no, 'ex:cancellation', 2400, 90, not_offered, pay_fee(percent(25), fee(600), refund(1800), within_days(14))), money_basis(directive_2015, no, not_offered, 'PTD Art. 12(4)')]).
step(policy_result(c1, permit('ex:cancellation')), rule(48), [=('C', c1), =('Rule', 'ex:cancellation'), =('X', 'ex:conditions'), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [addresses(c1, 'ex:cancellation'), t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c1, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(addresses(c1, 'ex:cancellation'), rule(41), [=('C', c1), =('Rule', 'ex:cancellation'), =('Offer', 'ex:terms'), =('Operator', 'ex:sunTrips'), =('Action', 'ex:cancel'), =('B', bk1), =('__anon17', by(anna)), =('__anon18', days(90)), =('__anon19', circumstances(none)), =('__anon20', voucher(not_offered)), =('__anon21', lead(anna)), =('__anon22', price(2400))], [t('ex:terms', 'rdf:type', 'odrl:Offer'), t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), t('ex:terms', 'odrl:permission', 'ex:cancellation'), t('ex:cancellation', 'odrl:action', 'ex:cancel'), request(c1, bk1, by(anna), 'ex:cancel', days(90), circumstances(none), voucher(not_offered)), booking(bk1, operator('ex:sunTrips'), lead(anna), price(2400))]).
step(request(c1, bk1, by(anna), 'ex:cancel', days(90), circumstances(none), voucher(not_offered)), fact(26), [], []).
step(booking(bk1, operator('ex:sunTrips'), lead(anna), price(2400)), fact(18), [], []).
step(unmet(c1, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(46), [=('C', c1), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [condition(c1, 'ex:byLeadTraveller', met), unmet(c1, ['ex:beforeDeparture'], [])]).
step(condition(c1, 'ex:byLeadTraveller', met), rule(42), [=('C', c1), =('K', 'ex:byLeadTraveller'), =('Result', met), =('Left', 'ex:requesterRole'), =('Op', 'odrl:eq'), =('Right', 'ex:leadTraveller'), =('V', 'ex:leadTraveller'), =('Holds', true)], [t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), value(c1, 'ex:requesterRole', 'ex:leadTraveller'), compare('odrl:eq', 'ex:leadTraveller', 'ex:leadTraveller', true), result(true, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:leadTraveller', 'odrl:eq', 'ex:leadTraveller', met)]).
step(value(c1, 'ex:requesterRole', 'ex:leadTraveller'), rule(34), [=('C', c1), =('B', bk1), =('X', anna), =('__anon0', 'ex:cancel'), =('__anon1', days(90)), =('__anon2', circumstances(none)), =('__anon3', voucher(not_offered)), =('__anon4', operator('ex:sunTrips')), =('__anon5', price(2400))], [request(c1, bk1, by(anna), 'ex:cancel', days(90), circumstances(none), voucher(not_offered)), booking(bk1, operator('ex:sunTrips'), lead(anna), price(2400))]).
step(unmet(c1, ['ex:beforeDeparture'], []), rule(46), [=('C', c1), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [condition(c1, 'ex:beforeDeparture', met), unmet(c1, [], [])]).
step(condition(c1, 'ex:beforeDeparture', met), rule(42), [=('C', c1), =('K', 'ex:beforeDeparture'), =('Result', met), =('Left', 'ex:daysBeforeDeparture'), =('Op', 'odrl:gt'), =('Right', 0), =('V', 90), =('Holds', true)], [t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), t('ex:beforeDeparture', 'odrl:rightOperand', 0), value(c1, 'ex:daysBeforeDeparture', 90), compare('odrl:gt', 90, 0, true), result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 90, 'odrl:gt', 0, met)]).
step(value(c1, 'ex:daysBeforeDeparture', 90), rule(36), [=('C', c1), =('D', 90), =('__anon12', bk1), =('__anon13', by(anna)), =('__anon14', 'ex:cancel'), =('__anon15', circumstances(none)), =('__anon16', voucher(not_offered))], [request(c1, bk1, by(anna), 'ex:cancel', days(90), circumstances(none), voucher(not_offered))]).
step(compare('odrl:gt', 90, 0, true), rule(39), [=('V', 90), =('R', 0)], [>(90, 0)]).
step(>(90, 0), builtin, [], []).
step(result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 90, 'odrl:gt', 0, met), fact(43), [=('__anon23', 'ex:beforeDeparture'), =('__anon24', 'ex:daysBeforeDeparture'), =('__anon25', 90), =('__anon26', 'odrl:gt'), =('__anon27', 0)], []).
step(unmet(c1, [], []), fact(45), [=('__anon28', c1)], []).
step(free_cancellation(directive_2015, none, no, 'PTD Art. 12(1)'), fact(53), [], []).
step(settle(directive_2015, no, 'ex:cancellation', 2400, 90, not_offered, pay_fee(percent(25), fee(600), refund(1800), within_days(14))), rule(59), [=('__anon36', directive_2015), =('Rule', 'ex:cancellation'), =('P', 2400), =('D', 90), =('__anon37', not_offered), =('Pct', 25), =('F', 600), =('Back', 1800)], [fee_percent('ex:cancellation', 90, 25), is(600, //(*(2400, 25), 100)), is(1800, -(2400, 600))]).
step(fee_percent('ex:cancellation', 90, 25), rule(50), [=('Rule', 'ex:cancellation'), =('D', 90), =('Pct', 25), =('Duty', 'ex:fee'), =('Bands', [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)])], [t('ex:cancellation', 'odrl:duty', 'ex:fee'), t('ex:fee', 'odrl:action', 'odrl:compensate'), t('ex:fee', 'ex:feeScale', [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)]), band(90, [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)], 25)]).
step(t('ex:cancellation', 'odrl:duty', 'ex:fee'), fact(15), [], []).
step(t('ex:fee', 'odrl:action', 'odrl:compensate'), fact(16), [], []).
step(t('ex:fee', 'ex:feeScale', [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)]), fact(17), [], []).
step(band(90, [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)], 25), rule(51), [=('D', 90), =('Min', 60), =('Max', 999), =('Pct', 25), =('__anon29', [band(30, 59, 50), band(1, 29, 100)])], [=<(60, 90), =<(90, 999)]).
step(=<(60, 90), builtin, [], []).
step(=<(90, 999), builtin, [], []).
step(is(600, //(*(2400, 25), 100)), builtin, [], []).
step(is(1800, -(2400, 600)), builtin, [], []).
step(money_basis(directive_2015, no, not_offered, 'PTD Art. 12(4)'), fact(64), [=('__anon48', directive_2015), =('__anon49', not_offered)], []).
step(assessment(directive_2015, c2, pay_fee(percent(100), fee(1800), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(70), [=('R', directive_2015), =('C', c2), =('Outcome', pay_fee(percent(100), fee(1800), refund(0), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('Rule', 'ex:cancellation'), =('B', bk2), =('__anon52', by(ben)), =('__anon53', 'ex:cancel'), =('D', 20), =('What', none), =('V', not_offered), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(ben)), =('P', 1800), =('F', no)], [regime(directive_2015), policy_result(c2, permit('ex:cancellation')), request(c2, bk2, by(ben), 'ex:cancel', days(20), circumstances(none), voucher(not_offered)), booking(bk2, operator('ex:sunTrips'), lead(ben), price(1800)), free_cancellation(directive_2015, none, no, 'PTD Art. 12(1)'), settle(directive_2015, no, 'ex:cancellation', 1800, 20, not_offered, pay_fee(percent(100), fee(1800), refund(0), within_days(14))), money_basis(directive_2015, no, not_offered, 'PTD Art. 12(4)')]).
step(policy_result(c2, permit('ex:cancellation')), rule(48), [=('C', c2), =('Rule', 'ex:cancellation'), =('X', 'ex:conditions'), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [addresses(c2, 'ex:cancellation'), t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c2, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(addresses(c2, 'ex:cancellation'), rule(41), [=('C', c2), =('Rule', 'ex:cancellation'), =('Offer', 'ex:terms'), =('Operator', 'ex:sunTrips'), =('Action', 'ex:cancel'), =('B', bk2), =('__anon17', by(ben)), =('__anon18', days(20)), =('__anon19', circumstances(none)), =('__anon20', voucher(not_offered)), =('__anon21', lead(ben)), =('__anon22', price(1800))], [t('ex:terms', 'rdf:type', 'odrl:Offer'), t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), t('ex:terms', 'odrl:permission', 'ex:cancellation'), t('ex:cancellation', 'odrl:action', 'ex:cancel'), request(c2, bk2, by(ben), 'ex:cancel', days(20), circumstances(none), voucher(not_offered)), booking(bk2, operator('ex:sunTrips'), lead(ben), price(1800))]).
step(request(c2, bk2, by(ben), 'ex:cancel', days(20), circumstances(none), voucher(not_offered)), fact(27), [], []).
step(booking(bk2, operator('ex:sunTrips'), lead(ben), price(1800)), fact(19), [], []).
step(unmet(c2, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(46), [=('C', c2), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [condition(c2, 'ex:byLeadTraveller', met), unmet(c2, ['ex:beforeDeparture'], [])]).
step(condition(c2, 'ex:byLeadTraveller', met), rule(42), [=('C', c2), =('K', 'ex:byLeadTraveller'), =('Result', met), =('Left', 'ex:requesterRole'), =('Op', 'odrl:eq'), =('Right', 'ex:leadTraveller'), =('V', 'ex:leadTraveller'), =('Holds', true)], [t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), value(c2, 'ex:requesterRole', 'ex:leadTraveller'), compare('odrl:eq', 'ex:leadTraveller', 'ex:leadTraveller', true), result(true, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:leadTraveller', 'odrl:eq', 'ex:leadTraveller', met)]).
step(value(c2, 'ex:requesterRole', 'ex:leadTraveller'), rule(34), [=('C', c2), =('B', bk2), =('X', ben), =('__anon0', 'ex:cancel'), =('__anon1', days(20)), =('__anon2', circumstances(none)), =('__anon3', voucher(not_offered)), =('__anon4', operator('ex:sunTrips')), =('__anon5', price(1800))], [request(c2, bk2, by(ben), 'ex:cancel', days(20), circumstances(none), voucher(not_offered)), booking(bk2, operator('ex:sunTrips'), lead(ben), price(1800))]).
step(unmet(c2, ['ex:beforeDeparture'], []), rule(46), [=('C', c2), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [condition(c2, 'ex:beforeDeparture', met), unmet(c2, [], [])]).
step(condition(c2, 'ex:beforeDeparture', met), rule(42), [=('C', c2), =('K', 'ex:beforeDeparture'), =('Result', met), =('Left', 'ex:daysBeforeDeparture'), =('Op', 'odrl:gt'), =('Right', 0), =('V', 20), =('Holds', true)], [t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), t('ex:beforeDeparture', 'odrl:rightOperand', 0), value(c2, 'ex:daysBeforeDeparture', 20), compare('odrl:gt', 20, 0, true), result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 20, 'odrl:gt', 0, met)]).
step(value(c2, 'ex:daysBeforeDeparture', 20), rule(36), [=('C', c2), =('D', 20), =('__anon12', bk2), =('__anon13', by(ben)), =('__anon14', 'ex:cancel'), =('__anon15', circumstances(none)), =('__anon16', voucher(not_offered))], [request(c2, bk2, by(ben), 'ex:cancel', days(20), circumstances(none), voucher(not_offered))]).
step(compare('odrl:gt', 20, 0, true), rule(39), [=('V', 20), =('R', 0)], [>(20, 0)]).
step(>(20, 0), builtin, [], []).
step(result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 20, 'odrl:gt', 0, met), fact(43), [=('__anon23', 'ex:beforeDeparture'), =('__anon24', 'ex:daysBeforeDeparture'), =('__anon25', 20), =('__anon26', 'odrl:gt'), =('__anon27', 0)], []).
step(unmet(c2, [], []), fact(45), [=('__anon28', c2)], []).
step(settle(directive_2015, no, 'ex:cancellation', 1800, 20, not_offered, pay_fee(percent(100), fee(1800), refund(0), within_days(14))), rule(59), [=('__anon36', directive_2015), =('Rule', 'ex:cancellation'), =('P', 1800), =('D', 20), =('__anon37', not_offered), =('Pct', 100), =('F', 1800), =('Back', 0)], [fee_percent('ex:cancellation', 20, 100), is(1800, //(*(1800, 100), 100)), is(0, -(1800, 1800))]).
step(fee_percent('ex:cancellation', 20, 100), rule(50), [=('Rule', 'ex:cancellation'), =('D', 20), =('Pct', 100), =('Duty', 'ex:fee'), =('Bands', [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)])], [t('ex:cancellation', 'odrl:duty', 'ex:fee'), t('ex:fee', 'odrl:action', 'odrl:compensate'), t('ex:fee', 'ex:feeScale', [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)]), band(20, [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)], 100)]).
step(band(20, [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)], 100), rule(52), [=('D', 20), =('Min', 60), =('__anon30', 999), =('__anon31', 25), =('Bands', [band(30, 59, 50), band(1, 29, 100)]), =('Pct', 100)], [<(20, 60), band(20, [band(30, 59, 50), band(1, 29, 100)], 100)]).
step(<(20, 60), builtin, [], []).
step(band(20, [band(30, 59, 50), band(1, 29, 100)], 100), rule(52), [=('D', 20), =('Min', 30), =('__anon30', 59), =('__anon31', 50), =('Bands', [band(1, 29, 100)]), =('Pct', 100)], [<(20, 30), band(20, [band(1, 29, 100)], 100)]).
step(<(20, 30), builtin, [], []).
step(band(20, [band(1, 29, 100)], 100), rule(51), [=('D', 20), =('Min', 1), =('Max', 29), =('Pct', 100), =('__anon29', [])], [=<(1, 20), =<(20, 29)]).
step(=<(1, 20), builtin, [], []).
step(=<(20, 29), builtin, [], []).
step(is(1800, //(*(1800, 100), 100)), builtin, [], []).
step(is(0, -(1800, 1800)), builtin, [], []).
step(assessment(directive_2015, c3, refund(1500, within_days(14)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD Art. 12(4)'])), rule(70), [=('R', directive_2015), =('C', c3), =('Outcome', refund(1500, within_days(14))), =('Free', 'PTD Art. 12(2)'), =('Money', 'PTD Art. 12(4)'), =('Rule', 'ex:cancellation'), =('B', bk3), =('__anon52', by(chloe)), =('__anon53', 'ex:cancel'), =('D', 10), =('What', at(destination, hurricane)), =('V', not_offered), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(chloe)), =('P', 1500), =('F', yes)], [regime(directive_2015), policy_result(c3, permit('ex:cancellation')), request(c3, bk3, by(chloe), 'ex:cancel', days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), booking(bk3, operator('ex:sunTrips'), lead(chloe), price(1500)), free_cancellation(directive_2015, at(destination, hurricane), yes, 'PTD Art. 12(2)'), settle(directive_2015, yes, 'ex:cancellation', 1500, 10, not_offered, refund(1500, within_days(14))), money_basis(directive_2015, yes, not_offered, 'PTD Art. 12(4)')]).
step(policy_result(c3, permit('ex:cancellation')), rule(48), [=('C', c3), =('Rule', 'ex:cancellation'), =('X', 'ex:conditions'), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [addresses(c3, 'ex:cancellation'), t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c3, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(addresses(c3, 'ex:cancellation'), rule(41), [=('C', c3), =('Rule', 'ex:cancellation'), =('Offer', 'ex:terms'), =('Operator', 'ex:sunTrips'), =('Action', 'ex:cancel'), =('B', bk3), =('__anon17', by(chloe)), =('__anon18', days(10)), =('__anon19', circumstances(at(destination, hurricane))), =('__anon20', voucher(not_offered)), =('__anon21', lead(chloe)), =('__anon22', price(1500))], [t('ex:terms', 'rdf:type', 'odrl:Offer'), t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), t('ex:terms', 'odrl:permission', 'ex:cancellation'), t('ex:cancellation', 'odrl:action', 'ex:cancel'), request(c3, bk3, by(chloe), 'ex:cancel', days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), booking(bk3, operator('ex:sunTrips'), lead(chloe), price(1500))]).
step(request(c3, bk3, by(chloe), 'ex:cancel', days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), fact(28), [], []).
step(booking(bk3, operator('ex:sunTrips'), lead(chloe), price(1500)), fact(20), [], []).
step(unmet(c3, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(46), [=('C', c3), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [condition(c3, 'ex:byLeadTraveller', met), unmet(c3, ['ex:beforeDeparture'], [])]).
step(condition(c3, 'ex:byLeadTraveller', met), rule(42), [=('C', c3), =('K', 'ex:byLeadTraveller'), =('Result', met), =('Left', 'ex:requesterRole'), =('Op', 'odrl:eq'), =('Right', 'ex:leadTraveller'), =('V', 'ex:leadTraveller'), =('Holds', true)], [t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), value(c3, 'ex:requesterRole', 'ex:leadTraveller'), compare('odrl:eq', 'ex:leadTraveller', 'ex:leadTraveller', true), result(true, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:leadTraveller', 'odrl:eq', 'ex:leadTraveller', met)]).
step(value(c3, 'ex:requesterRole', 'ex:leadTraveller'), rule(34), [=('C', c3), =('B', bk3), =('X', chloe), =('__anon0', 'ex:cancel'), =('__anon1', days(10)), =('__anon2', circumstances(at(destination, hurricane))), =('__anon3', voucher(not_offered)), =('__anon4', operator('ex:sunTrips')), =('__anon5', price(1500))], [request(c3, bk3, by(chloe), 'ex:cancel', days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), booking(bk3, operator('ex:sunTrips'), lead(chloe), price(1500))]).
step(unmet(c3, ['ex:beforeDeparture'], []), rule(46), [=('C', c3), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [condition(c3, 'ex:beforeDeparture', met), unmet(c3, [], [])]).
step(condition(c3, 'ex:beforeDeparture', met), rule(42), [=('C', c3), =('K', 'ex:beforeDeparture'), =('Result', met), =('Left', 'ex:daysBeforeDeparture'), =('Op', 'odrl:gt'), =('Right', 0), =('V', 10), =('Holds', true)], [t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), t('ex:beforeDeparture', 'odrl:rightOperand', 0), value(c3, 'ex:daysBeforeDeparture', 10), compare('odrl:gt', 10, 0, true), result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 10, 'odrl:gt', 0, met)]).
step(value(c3, 'ex:daysBeforeDeparture', 10), rule(36), [=('C', c3), =('D', 10), =('__anon12', bk3), =('__anon13', by(chloe)), =('__anon14', 'ex:cancel'), =('__anon15', circumstances(at(destination, hurricane))), =('__anon16', voucher(not_offered))], [request(c3, bk3, by(chloe), 'ex:cancel', days(10), circumstances(at(destination, hurricane)), voucher(not_offered))]).
step(compare('odrl:gt', 10, 0, true), rule(39), [=('V', 10), =('R', 0)], [>(10, 0)]).
step(>(10, 0), builtin, [], []).
step(result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 10, 'odrl:gt', 0, met), fact(43), [=('__anon23', 'ex:beforeDeparture'), =('__anon24', 'ex:daysBeforeDeparture'), =('__anon25', 10), =('__anon26', 'odrl:gt'), =('__anon27', 0)], []).
step(unmet(c3, [], []), fact(45), [=('__anon28', c3)], []).
step(free_cancellation(directive_2015, at(destination, hurricane), yes, 'PTD Art. 12(2)'), fact(54), [=('__anon32', hurricane)], []).
step(settle(directive_2015, yes, 'ex:cancellation', 1500, 10, not_offered, refund(1500, within_days(14))), fact(60), [=('__anon38', directive_2015), =('__anon39', 'ex:cancellation'), =('P', 1500), =('__anon40', 10)], []).
step(money_basis(directive_2015, yes, not_offered, 'PTD Art. 12(4)'), fact(65), [=('__anon50', directive_2015)], []).
step(assessment(directive_2015, c4, pay_fee(percent(100), fee(2100), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(70), [=('R', directive_2015), =('C', c4), =('Outcome', pay_fee(percent(100), fee(2100), refund(0), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('Rule', 'ex:cancellation'), =('B', bk4), =('__anon52', by(david)), =('__anon53', 'ex:cancel'), =('D', 5), =('What', at(departure, airport_closed_by_floods)), =('V', not_offered), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(david)), =('P', 2100), =('F', no)], [regime(directive_2015), policy_result(c4, permit('ex:cancellation')), request(c4, bk4, by(david), 'ex:cancel', days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), booking(bk4, operator('ex:sunTrips'), lead(david), price(2100)), free_cancellation(directive_2015, at(departure, airport_closed_by_floods), no, 'PTD Art. 12(1)'), settle(directive_2015, no, 'ex:cancellation', 2100, 5, not_offered, pay_fee(percent(100), fee(2100), refund(0), within_days(14))), money_basis(directive_2015, no, not_offered, 'PTD Art. 12(4)')]).
step(policy_result(c4, permit('ex:cancellation')), rule(48), [=('C', c4), =('Rule', 'ex:cancellation'), =('X', 'ex:conditions'), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [addresses(c4, 'ex:cancellation'), t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c4, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(addresses(c4, 'ex:cancellation'), rule(41), [=('C', c4), =('Rule', 'ex:cancellation'), =('Offer', 'ex:terms'), =('Operator', 'ex:sunTrips'), =('Action', 'ex:cancel'), =('B', bk4), =('__anon17', by(david)), =('__anon18', days(5)), =('__anon19', circumstances(at(departure, airport_closed_by_floods))), =('__anon20', voucher(not_offered)), =('__anon21', lead(david)), =('__anon22', price(2100))], [t('ex:terms', 'rdf:type', 'odrl:Offer'), t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), t('ex:terms', 'odrl:permission', 'ex:cancellation'), t('ex:cancellation', 'odrl:action', 'ex:cancel'), request(c4, bk4, by(david), 'ex:cancel', days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), booking(bk4, operator('ex:sunTrips'), lead(david), price(2100))]).
step(request(c4, bk4, by(david), 'ex:cancel', days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), fact(29), [], []).
step(booking(bk4, operator('ex:sunTrips'), lead(david), price(2100)), fact(21), [], []).
step(unmet(c4, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(46), [=('C', c4), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [condition(c4, 'ex:byLeadTraveller', met), unmet(c4, ['ex:beforeDeparture'], [])]).
step(condition(c4, 'ex:byLeadTraveller', met), rule(42), [=('C', c4), =('K', 'ex:byLeadTraveller'), =('Result', met), =('Left', 'ex:requesterRole'), =('Op', 'odrl:eq'), =('Right', 'ex:leadTraveller'), =('V', 'ex:leadTraveller'), =('Holds', true)], [t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), value(c4, 'ex:requesterRole', 'ex:leadTraveller'), compare('odrl:eq', 'ex:leadTraveller', 'ex:leadTraveller', true), result(true, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:leadTraveller', 'odrl:eq', 'ex:leadTraveller', met)]).
step(value(c4, 'ex:requesterRole', 'ex:leadTraveller'), rule(34), [=('C', c4), =('B', bk4), =('X', david), =('__anon0', 'ex:cancel'), =('__anon1', days(5)), =('__anon2', circumstances(at(departure, airport_closed_by_floods))), =('__anon3', voucher(not_offered)), =('__anon4', operator('ex:sunTrips')), =('__anon5', price(2100))], [request(c4, bk4, by(david), 'ex:cancel', days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), booking(bk4, operator('ex:sunTrips'), lead(david), price(2100))]).
step(unmet(c4, ['ex:beforeDeparture'], []), rule(46), [=('C', c4), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [condition(c4, 'ex:beforeDeparture', met), unmet(c4, [], [])]).
step(condition(c4, 'ex:beforeDeparture', met), rule(42), [=('C', c4), =('K', 'ex:beforeDeparture'), =('Result', met), =('Left', 'ex:daysBeforeDeparture'), =('Op', 'odrl:gt'), =('Right', 0), =('V', 5), =('Holds', true)], [t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), t('ex:beforeDeparture', 'odrl:rightOperand', 0), value(c4, 'ex:daysBeforeDeparture', 5), compare('odrl:gt', 5, 0, true), result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 5, 'odrl:gt', 0, met)]).
step(value(c4, 'ex:daysBeforeDeparture', 5), rule(36), [=('C', c4), =('D', 5), =('__anon12', bk4), =('__anon13', by(david)), =('__anon14', 'ex:cancel'), =('__anon15', circumstances(at(departure, airport_closed_by_floods))), =('__anon16', voucher(not_offered))], [request(c4, bk4, by(david), 'ex:cancel', days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered))]).
step(compare('odrl:gt', 5, 0, true), rule(39), [=('V', 5), =('R', 0)], [>(5, 0)]).
step(>(5, 0), builtin, [], []).
step(result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 5, 'odrl:gt', 0, met), fact(43), [=('__anon23', 'ex:beforeDeparture'), =('__anon24', 'ex:daysBeforeDeparture'), =('__anon25', 5), =('__anon26', 'odrl:gt'), =('__anon27', 0)], []).
step(unmet(c4, [], []), fact(45), [=('__anon28', c4)], []).
step(free_cancellation(directive_2015, at(departure, airport_closed_by_floods), no, 'PTD Art. 12(1)'), fact(55), [=('__anon33', airport_closed_by_floods)], []).
step(settle(directive_2015, no, 'ex:cancellation', 2100, 5, not_offered, pay_fee(percent(100), fee(2100), refund(0), within_days(14))), rule(59), [=('__anon36', directive_2015), =('Rule', 'ex:cancellation'), =('P', 2100), =('D', 5), =('__anon37', not_offered), =('Pct', 100), =('F', 2100), =('Back', 0)], [fee_percent('ex:cancellation', 5, 100), is(2100, //(*(2100, 100), 100)), is(0, -(2100, 2100))]).
step(fee_percent('ex:cancellation', 5, 100), rule(50), [=('Rule', 'ex:cancellation'), =('D', 5), =('Pct', 100), =('Duty', 'ex:fee'), =('Bands', [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)])], [t('ex:cancellation', 'odrl:duty', 'ex:fee'), t('ex:fee', 'odrl:action', 'odrl:compensate'), t('ex:fee', 'ex:feeScale', [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)]), band(5, [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)], 100)]).
step(band(5, [band(60, 999, 25), band(30, 59, 50), band(1, 29, 100)], 100), rule(52), [=('D', 5), =('Min', 60), =('__anon30', 999), =('__anon31', 25), =('Bands', [band(30, 59, 50), band(1, 29, 100)]), =('Pct', 100)], [<(5, 60), band(5, [band(30, 59, 50), band(1, 29, 100)], 100)]).
step(<(5, 60), builtin, [], []).
step(band(5, [band(30, 59, 50), band(1, 29, 100)], 100), rule(52), [=('D', 5), =('Min', 30), =('__anon30', 59), =('__anon31', 50), =('Bands', [band(1, 29, 100)]), =('Pct', 100)], [<(5, 30), band(5, [band(1, 29, 100)], 100)]).
step(<(5, 30), builtin, [], []).
step(band(5, [band(1, 29, 100)], 100), rule(51), [=('D', 5), =('Min', 1), =('Max', 29), =('Pct', 100), =('__anon29', [])], [=<(1, 5), =<(5, 29)]).
step(=<(1, 5), builtin, [], []).
step(=<(5, 29), builtin, [], []).
step(is(2100, //(*(2100, 100), 100)), builtin, [], []).
step(is(0, -(2100, 2100)), builtin, [], []).
step(assessment(directive_2015, c5, refund(1200, within_days(14)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD Art. 12(4)'])), rule(70), [=('R', directive_2015), =('C', c5), =('Outcome', refund(1200, within_days(14))), =('Free', 'PTD Art. 12(2)'), =('Money', 'PTD Art. 12(4)'), =('Rule', 'ex:cancellation'), =('B', bk5), =('__anon52', by(emma)), =('__anon53', 'ex:cancel'), =('D', 12), =('What', at(destination, hurricane)), =('V', offered(refused)), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(emma)), =('P', 1200), =('F', yes)], [regime(directive_2015), policy_result(c5, permit('ex:cancellation')), request(c5, bk5, by(emma), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), booking(bk5, operator('ex:sunTrips'), lead(emma), price(1200)), free_cancellation(directive_2015, at(destination, hurricane), yes, 'PTD Art. 12(2)'), settle(directive_2015, yes, 'ex:cancellation', 1200, 12, offered(refused), refund(1200, within_days(14))), money_basis(directive_2015, yes, offered(refused), 'PTD Art. 12(4)')]).
step(policy_result(c5, permit('ex:cancellation')), rule(48), [=('C', c5), =('Rule', 'ex:cancellation'), =('X', 'ex:conditions'), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [addresses(c5, 'ex:cancellation'), t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c5, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(addresses(c5, 'ex:cancellation'), rule(41), [=('C', c5), =('Rule', 'ex:cancellation'), =('Offer', 'ex:terms'), =('Operator', 'ex:sunTrips'), =('Action', 'ex:cancel'), =('B', bk5), =('__anon17', by(emma)), =('__anon18', days(12)), =('__anon19', circumstances(at(destination, hurricane))), =('__anon20', voucher(offered(refused))), =('__anon21', lead(emma)), =('__anon22', price(1200))], [t('ex:terms', 'rdf:type', 'odrl:Offer'), t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), t('ex:terms', 'odrl:permission', 'ex:cancellation'), t('ex:cancellation', 'odrl:action', 'ex:cancel'), request(c5, bk5, by(emma), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), booking(bk5, operator('ex:sunTrips'), lead(emma), price(1200))]).
step(request(c5, bk5, by(emma), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), fact(30), [], []).
step(booking(bk5, operator('ex:sunTrips'), lead(emma), price(1200)), fact(22), [], []).
step(unmet(c5, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(46), [=('C', c5), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [condition(c5, 'ex:byLeadTraveller', met), unmet(c5, ['ex:beforeDeparture'], [])]).
step(condition(c5, 'ex:byLeadTraveller', met), rule(42), [=('C', c5), =('K', 'ex:byLeadTraveller'), =('Result', met), =('Left', 'ex:requesterRole'), =('Op', 'odrl:eq'), =('Right', 'ex:leadTraveller'), =('V', 'ex:leadTraveller'), =('Holds', true)], [t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), value(c5, 'ex:requesterRole', 'ex:leadTraveller'), compare('odrl:eq', 'ex:leadTraveller', 'ex:leadTraveller', true), result(true, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:leadTraveller', 'odrl:eq', 'ex:leadTraveller', met)]).
step(value(c5, 'ex:requesterRole', 'ex:leadTraveller'), rule(34), [=('C', c5), =('B', bk5), =('X', emma), =('__anon0', 'ex:cancel'), =('__anon1', days(12)), =('__anon2', circumstances(at(destination, hurricane))), =('__anon3', voucher(offered(refused))), =('__anon4', operator('ex:sunTrips')), =('__anon5', price(1200))], [request(c5, bk5, by(emma), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), booking(bk5, operator('ex:sunTrips'), lead(emma), price(1200))]).
step(unmet(c5, ['ex:beforeDeparture'], []), rule(46), [=('C', c5), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [condition(c5, 'ex:beforeDeparture', met), unmet(c5, [], [])]).
step(condition(c5, 'ex:beforeDeparture', met), rule(42), [=('C', c5), =('K', 'ex:beforeDeparture'), =('Result', met), =('Left', 'ex:daysBeforeDeparture'), =('Op', 'odrl:gt'), =('Right', 0), =('V', 12), =('Holds', true)], [t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), t('ex:beforeDeparture', 'odrl:rightOperand', 0), value(c5, 'ex:daysBeforeDeparture', 12), compare('odrl:gt', 12, 0, true), result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 12, 'odrl:gt', 0, met)]).
step(value(c5, 'ex:daysBeforeDeparture', 12), rule(36), [=('C', c5), =('D', 12), =('__anon12', bk5), =('__anon13', by(emma)), =('__anon14', 'ex:cancel'), =('__anon15', circumstances(at(destination, hurricane))), =('__anon16', voucher(offered(refused)))], [request(c5, bk5, by(emma), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(refused)))]).
step(compare('odrl:gt', 12, 0, true), rule(39), [=('V', 12), =('R', 0)], [>(12, 0)]).
step(>(12, 0), builtin, [], []).
step(result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 12, 'odrl:gt', 0, met), fact(43), [=('__anon23', 'ex:beforeDeparture'), =('__anon24', 'ex:daysBeforeDeparture'), =('__anon25', 12), =('__anon26', 'odrl:gt'), =('__anon27', 0)], []).
step(unmet(c5, [], []), fact(45), [=('__anon28', c5)], []).
step(settle(directive_2015, yes, 'ex:cancellation', 1200, 12, offered(refused), refund(1200, within_days(14))), fact(61), [=('__anon41', directive_2015), =('__anon42', 'ex:cancellation'), =('P', 1200), =('__anon43', 12)], []).
step(money_basis(directive_2015, yes, offered(refused), 'PTD Art. 12(4)'), fact(66), [], []).
step(assessment(directive_2015, c6, voucher(value(1600), terms(as_agreed)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD 2015: no voucher rules'])), rule(70), [=('R', directive_2015), =('C', c6), =('Outcome', voucher(value(1600), terms(as_agreed))), =('Free', 'PTD Art. 12(2)'), =('Money', 'PTD 2015: no voucher rules'), =('Rule', 'ex:cancellation'), =('B', bk6), =('__anon52', by(farid)), =('__anon53', 'ex:cancel'), =('D', 12), =('What', at(destination, hurricane)), =('V', offered(accepted)), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(farid)), =('P', 1600), =('F', yes)], [regime(directive_2015), policy_result(c6, permit('ex:cancellation')), request(c6, bk6, by(farid), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), booking(bk6, operator('ex:sunTrips'), lead(farid), price(1600)), free_cancellation(directive_2015, at(destination, hurricane), yes, 'PTD Art. 12(2)'), settle(directive_2015, yes, 'ex:cancellation', 1600, 12, offered(accepted), voucher(value(1600), terms(as_agreed))), money_basis(directive_2015, yes, offered(accepted), 'PTD 2015: no voucher rules')]).
step(policy_result(c6, permit('ex:cancellation')), rule(48), [=('C', c6), =('Rule', 'ex:cancellation'), =('X', 'ex:conditions'), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [addresses(c6, 'ex:cancellation'), t('ex:cancellation', 'odrl:constraint', 'ex:conditions'), t('ex:conditions', 'odrl:and', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c6, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(addresses(c6, 'ex:cancellation'), rule(41), [=('C', c6), =('Rule', 'ex:cancellation'), =('Offer', 'ex:terms'), =('Operator', 'ex:sunTrips'), =('Action', 'ex:cancel'), =('B', bk6), =('__anon17', by(farid)), =('__anon18', days(12)), =('__anon19', circumstances(at(destination, hurricane))), =('__anon20', voucher(offered(accepted))), =('__anon21', lead(farid)), =('__anon22', price(1600))], [t('ex:terms', 'rdf:type', 'odrl:Offer'), t('ex:terms', 'odrl:assigner', 'ex:sunTrips'), t('ex:terms', 'odrl:permission', 'ex:cancellation'), t('ex:cancellation', 'odrl:action', 'ex:cancel'), request(c6, bk6, by(farid), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), booking(bk6, operator('ex:sunTrips'), lead(farid), price(1600))]).
step(request(c6, bk6, by(farid), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), fact(31), [], []).
step(booking(bk6, operator('ex:sunTrips'), lead(farid), price(1600)), fact(23), [], []).
step(unmet(c6, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(46), [=('C', c6), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [condition(c6, 'ex:byLeadTraveller', met), unmet(c6, ['ex:beforeDeparture'], [])]).
step(condition(c6, 'ex:byLeadTraveller', met), rule(42), [=('C', c6), =('K', 'ex:byLeadTraveller'), =('Result', met), =('Left', 'ex:requesterRole'), =('Op', 'odrl:eq'), =('Right', 'ex:leadTraveller'), =('V', 'ex:leadTraveller'), =('Holds', true)], [t('ex:byLeadTraveller', 'odrl:leftOperand', 'ex:requesterRole'), t('ex:byLeadTraveller', 'odrl:operator', 'odrl:eq'), t('ex:byLeadTraveller', 'odrl:rightOperand', 'ex:leadTraveller'), value(c6, 'ex:requesterRole', 'ex:leadTraveller'), compare('odrl:eq', 'ex:leadTraveller', 'ex:leadTraveller', true), result(true, 'ex:byLeadTraveller', 'ex:requesterRole', 'ex:leadTraveller', 'odrl:eq', 'ex:leadTraveller', met)]).
step(value(c6, 'ex:requesterRole', 'ex:leadTraveller'), rule(34), [=('C', c6), =('B', bk6), =('X', farid), =('__anon0', 'ex:cancel'), =('__anon1', days(12)), =('__anon2', circumstances(at(destination, hurricane))), =('__anon3', voucher(offered(accepted))), =('__anon4', operator('ex:sunTrips')), =('__anon5', price(1600))], [request(c6, bk6, by(farid), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), booking(bk6, operator('ex:sunTrips'), lead(farid), price(1600))]).
step(unmet(c6, ['ex:beforeDeparture'], []), rule(46), [=('C', c6), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [condition(c6, 'ex:beforeDeparture', met), unmet(c6, [], [])]).
step(condition(c6, 'ex:beforeDeparture', met), rule(42), [=('C', c6), =('K', 'ex:beforeDeparture'), =('Result', met), =('Left', 'ex:daysBeforeDeparture'), =('Op', 'odrl:gt'), =('Right', 0), =('V', 12), =('Holds', true)], [t('ex:beforeDeparture', 'odrl:leftOperand', 'ex:daysBeforeDeparture'), t('ex:beforeDeparture', 'odrl:operator', 'odrl:gt'), t('ex:beforeDeparture', 'odrl:rightOperand', 0), value(c6, 'ex:daysBeforeDeparture', 12), compare('odrl:gt', 12, 0, true), result(true, 'ex:beforeDeparture', 'ex:daysBeforeDeparture', 12, 'odrl:gt', 0, met)]).
step(value(c6, 'ex:daysBeforeDeparture', 12), rule(36), [=('C', c6), =('D', 12), =('__anon12', bk6), =('__anon13', by(farid)), =('__anon14', 'ex:cancel'), =('__anon15', circumstances(at(destination, hurricane))), =('__anon16', voucher(offered(accepted)))], [request(c6, bk6, by(farid), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted)))]).
step(unmet(c6, [], []), fact(45), [=('__anon28', c6)], []).
step(settle(directive_2015, yes, 'ex:cancellation', 1600, 12, offered(accepted), voucher(value(1600), terms(as_agreed))), fact(62), [=('__anon44', 'ex:cancellation'), =('P', 1600), =('__anon45', 12)], []).
step(money_basis(directive_2015, yes, offered(accepted), 'PTD 2015: no voucher rules'), fact(67), [], []).
step(assessment(revised_2026, c1, pay_fee(percent(25), fee(600), refund(1800), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(70), [=('R', revised_2026), =('C', c1), =('Outcome', pay_fee(percent(25), fee(600), refund(1800), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('Rule', 'ex:cancellation'), =('B', bk1), =('__anon52', by(anna)), =('__anon53', 'ex:cancel'), =('D', 90), =('What', none), =('V', not_offered), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(anna)), =('P', 2400), =('F', no)], [regime(revised_2026), policy_result(c1, permit('ex:cancellation')), request(c1, bk1, by(anna), 'ex:cancel', days(90), circumstances(none), voucher(not_offered)), booking(bk1, operator('ex:sunTrips'), lead(anna), price(2400)), free_cancellation(revised_2026, none, no, 'PTD Art. 12(1)'), settle(revised_2026, no, 'ex:cancellation', 2400, 90, not_offered, pay_fee(percent(25), fee(600), refund(1800), within_days(14))), money_basis(revised_2026, no, not_offered, 'PTD Art. 12(4)')]).
step(free_cancellation(revised_2026, none, no, 'PTD Art. 12(1)'), fact(56), [], []).
step(settle(revised_2026, no, 'ex:cancellation', 2400, 90, not_offered, pay_fee(percent(25), fee(600), refund(1800), within_days(14))), rule(59), [=('__anon36', revised_2026), =('Rule', 'ex:cancellation'), =('P', 2400), =('D', 90), =('__anon37', not_offered), =('Pct', 25), =('F', 600), =('Back', 1800)], [fee_percent('ex:cancellation', 90, 25), is(600, //(*(2400, 25), 100)), is(1800, -(2400, 600))]).
step(money_basis(revised_2026, no, not_offered, 'PTD Art. 12(4)'), fact(64), [=('__anon48', revised_2026), =('__anon49', not_offered)], []).
step(assessment(revised_2026, c2, pay_fee(percent(100), fee(1800), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(70), [=('R', revised_2026), =('C', c2), =('Outcome', pay_fee(percent(100), fee(1800), refund(0), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('Rule', 'ex:cancellation'), =('B', bk2), =('__anon52', by(ben)), =('__anon53', 'ex:cancel'), =('D', 20), =('What', none), =('V', not_offered), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(ben)), =('P', 1800), =('F', no)], [regime(revised_2026), policy_result(c2, permit('ex:cancellation')), request(c2, bk2, by(ben), 'ex:cancel', days(20), circumstances(none), voucher(not_offered)), booking(bk2, operator('ex:sunTrips'), lead(ben), price(1800)), free_cancellation(revised_2026, none, no, 'PTD Art. 12(1)'), settle(revised_2026, no, 'ex:cancellation', 1800, 20, not_offered, pay_fee(percent(100), fee(1800), refund(0), within_days(14))), money_basis(revised_2026, no, not_offered, 'PTD Art. 12(4)')]).
step(settle(revised_2026, no, 'ex:cancellation', 1800, 20, not_offered, pay_fee(percent(100), fee(1800), refund(0), within_days(14))), rule(59), [=('__anon36', revised_2026), =('Rule', 'ex:cancellation'), =('P', 1800), =('D', 20), =('__anon37', not_offered), =('Pct', 100), =('F', 1800), =('Back', 0)], [fee_percent('ex:cancellation', 20, 100), is(1800, //(*(1800, 100), 100)), is(0, -(1800, 1800))]).
step(assessment(revised_2026, c3, refund(1500, within_days(14)), basis(['ex:terms', 'revised PTD: destination', 'PTD Art. 12(4)'])), rule(70), [=('R', revised_2026), =('C', c3), =('Outcome', refund(1500, within_days(14))), =('Free', 'revised PTD: destination'), =('Money', 'PTD Art. 12(4)'), =('Rule', 'ex:cancellation'), =('B', bk3), =('__anon52', by(chloe)), =('__anon53', 'ex:cancel'), =('D', 10), =('What', at(destination, hurricane)), =('V', not_offered), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(chloe)), =('P', 1500), =('F', yes)], [regime(revised_2026), policy_result(c3, permit('ex:cancellation')), request(c3, bk3, by(chloe), 'ex:cancel', days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), booking(bk3, operator('ex:sunTrips'), lead(chloe), price(1500)), free_cancellation(revised_2026, at(destination, hurricane), yes, 'revised PTD: destination'), settle(revised_2026, yes, 'ex:cancellation', 1500, 10, not_offered, refund(1500, within_days(14))), money_basis(revised_2026, yes, not_offered, 'PTD Art. 12(4)')]).
step(free_cancellation(revised_2026, at(destination, hurricane), yes, 'revised PTD: destination'), fact(57), [=('__anon34', hurricane)], []).
step(settle(revised_2026, yes, 'ex:cancellation', 1500, 10, not_offered, refund(1500, within_days(14))), fact(60), [=('__anon38', revised_2026), =('__anon39', 'ex:cancellation'), =('P', 1500), =('__anon40', 10)], []).
step(money_basis(revised_2026, yes, not_offered, 'PTD Art. 12(4)'), fact(65), [=('__anon50', revised_2026)], []).
step(assessment(revised_2026, c4, refund(2100, within_days(14)), basis(['ex:terms', 'revised PTD: point of departure', 'PTD Art. 12(4)'])), rule(70), [=('R', revised_2026), =('C', c4), =('Outcome', refund(2100, within_days(14))), =('Free', 'revised PTD: point of departure'), =('Money', 'PTD Art. 12(4)'), =('Rule', 'ex:cancellation'), =('B', bk4), =('__anon52', by(david)), =('__anon53', 'ex:cancel'), =('D', 5), =('What', at(departure, airport_closed_by_floods)), =('V', not_offered), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(david)), =('P', 2100), =('F', yes)], [regime(revised_2026), policy_result(c4, permit('ex:cancellation')), request(c4, bk4, by(david), 'ex:cancel', days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), booking(bk4, operator('ex:sunTrips'), lead(david), price(2100)), free_cancellation(revised_2026, at(departure, airport_closed_by_floods), yes, 'revised PTD: point of departure'), settle(revised_2026, yes, 'ex:cancellation', 2100, 5, not_offered, refund(2100, within_days(14))), money_basis(revised_2026, yes, not_offered, 'PTD Art. 12(4)')]).
step(free_cancellation(revised_2026, at(departure, airport_closed_by_floods), yes, 'revised PTD: point of departure'), fact(58), [=('__anon35', airport_closed_by_floods)], []).
step(settle(revised_2026, yes, 'ex:cancellation', 2100, 5, not_offered, refund(2100, within_days(14))), fact(60), [=('__anon38', revised_2026), =('__anon39', 'ex:cancellation'), =('P', 2100), =('__anon40', 5)], []).
step(assessment(revised_2026, c5, refund(1200, within_days(14)), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])), rule(70), [=('R', revised_2026), =('C', c5), =('Outcome', refund(1200, within_days(14))), =('Free', 'revised PTD: destination'), =('Money', 'revised PTD: vouchers'), =('Rule', 'ex:cancellation'), =('B', bk5), =('__anon52', by(emma)), =('__anon53', 'ex:cancel'), =('D', 12), =('What', at(destination, hurricane)), =('V', offered(refused)), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(emma)), =('P', 1200), =('F', yes)], [regime(revised_2026), policy_result(c5, permit('ex:cancellation')), request(c5, bk5, by(emma), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), booking(bk5, operator('ex:sunTrips'), lead(emma), price(1200)), free_cancellation(revised_2026, at(destination, hurricane), yes, 'revised PTD: destination'), settle(revised_2026, yes, 'ex:cancellation', 1200, 12, offered(refused), refund(1200, within_days(14))), money_basis(revised_2026, yes, offered(refused), 'revised PTD: vouchers')]).
step(settle(revised_2026, yes, 'ex:cancellation', 1200, 12, offered(refused), refund(1200, within_days(14))), fact(61), [=('__anon41', revised_2026), =('__anon42', 'ex:cancellation'), =('P', 1200), =('__anon43', 12)], []).
step(money_basis(revised_2026, yes, offered(refused), 'revised PTD: vouchers'), fact(68), [=('__anon51', refused)], []).
step(assessment(revised_2026, c6, voucher(value(1600), valid_months(12), unused_value_refunded), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])), rule(70), [=('R', revised_2026), =('C', c6), =('Outcome', voucher(value(1600), valid_months(12), unused_value_refunded)), =('Free', 'revised PTD: destination'), =('Money', 'revised PTD: vouchers'), =('Rule', 'ex:cancellation'), =('B', bk6), =('__anon52', by(farid)), =('__anon53', 'ex:cancel'), =('D', 12), =('What', at(destination, hurricane)), =('V', offered(accepted)), =('__anon54', operator('ex:sunTrips')), =('__anon55', lead(farid)), =('P', 1600), =('F', yes)], [regime(revised_2026), policy_result(c6, permit('ex:cancellation')), request(c6, bk6, by(farid), 'ex:cancel', days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), booking(bk6, operator('ex:sunTrips'), lead(farid), price(1600)), free_cancellation(revised_2026, at(destination, hurricane), yes, 'revised PTD: destination'), settle(revised_2026, yes, 'ex:cancellation', 1600, 12, offered(accepted), voucher(value(1600), valid_months(12), unused_value_refunded)), money_basis(revised_2026, yes, offered(accepted), 'revised PTD: vouchers')]).
step(settle(revised_2026, yes, 'ex:cancellation', 1600, 12, offered(accepted), voucher(value(1600), valid_months(12), unused_value_refunded)), fact(63), [=('__anon46', 'ex:cancellation'), =('P', 1600), =('__anon47', 12)], []).
step(money_basis(revised_2026, yes, offered(accepted), 'revised PTD: vouchers'), fact(68), [=('__anon51', accepted)], []).
step(complaint_plan(directive_2015, k1, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), rule(73), [=('K', k1), =('__anon56', 'pool closed for the whole stay')], [complaint(k1, 'pool closed for the whole stay')]).
step(complaint(k1, 'pool closed for the whole stay'), fact(71), [], []).
step(complaint_plan(directive_2015, k2, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), rule(73), [=('K', k2), =('__anon56', 'refund not received')], [complaint(k2, 'refund not received')]).
step(complaint(k2, 'refund not received'), fact(72), [], []).
step(complaint_plan(revised_2026, k1, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), rule(74), [=('K', k1), =('__anon57', 'pool closed for the whole stay')], [complaint(k1, 'pool closed for the whole stay')]).
step(complaint_plan(revised_2026, k2, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), rule(74), [=('K', k2), =('__anon57', 'refund not received')], [complaint(k2, 'refund not received')]).
step(changed(cancellation(c4), from(pay_fee(percent(100), fee(2100), refund(0), within_days(14))), to(refund(2100, within_days(14)))), rule(75), [=('C', c4), =('Old', pay_fee(percent(100), fee(2100), refund(0), within_days(14))), =('New', refund(2100, within_days(14))), =('__anon58', basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), =('__anon59', basis(['ex:terms', 'revised PTD: point of departure', 'PTD Art. 12(4)']))], [assessment(directive_2015, c4, pay_fee(percent(100), fee(2100), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), assessment(revised_2026, c4, refund(2100, within_days(14)), basis(['ex:terms', 'revised PTD: point of departure', 'PTD Art. 12(4)'])), \==(pay_fee(percent(100), fee(2100), refund(0), within_days(14)), refund(2100, within_days(14)))]).
step(\==(pay_fee(percent(100), fee(2100), refund(0), within_days(14)), refund(2100, within_days(14))), builtin, [], []).
step(changed(cancellation(c6), from(voucher(value(1600), terms(as_agreed))), to(voucher(value(1600), valid_months(12), unused_value_refunded))), rule(75), [=('C', c6), =('Old', voucher(value(1600), terms(as_agreed))), =('New', voucher(value(1600), valid_months(12), unused_value_refunded)), =('__anon58', basis(['ex:terms', 'PTD Art. 12(2)', 'PTD 2015: no voucher rules'])), =('__anon59', basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers']))], [assessment(directive_2015, c6, voucher(value(1600), terms(as_agreed)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD 2015: no voucher rules'])), assessment(revised_2026, c6, voucher(value(1600), valid_months(12), unused_value_refunded), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])), \==(voucher(value(1600), terms(as_agreed)), voucher(value(1600), valid_months(12), unused_value_refunded))]).
step(\==(voucher(value(1600), terms(as_agreed)), voucher(value(1600), valid_months(12), unused_value_refunded)), builtin, [], []).
step(changed(complaint(k1), from(deadlines(set_by_national_law)), to(deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))), rule(76), [=('K', k1), =('Old', deadlines(set_by_national_law)), =('New', deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60)))), =('__anon60', basis(['PTD 2015: no complaint deadlines'])), =('__anon61', basis(['revised PTD: complaints']))], [complaint_plan(directive_2015, k1, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), complaint_plan(revised_2026, k1, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), \==(deadlines(set_by_national_law), deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))]).
step(\==(deadlines(set_by_national_law), deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60)))), builtin, [], []).
step(changed(complaint(k2), from(deadlines(set_by_national_law)), to(deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))), rule(76), [=('K', k2), =('Old', deadlines(set_by_national_law)), =('New', deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60)))), =('__anon60', basis(['PTD 2015: no complaint deadlines'])), =('__anon61', basis(['revised PTD: complaints']))], [complaint_plan(directive_2015, k2, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), complaint_plan(revised_2026, k2, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), \==(deadlines(set_by_national_law), deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))]).
