assessment(directive_2015, c7, refused_by_terms([unmet(days_before_departure(-2))]), basis(['ex:terms'])).
assessment(directive_2015, c8, refused_by_terms([unmet(requested_by(hugo), lead_traveller(ivy))]), basis(['ex:terms'])).
assessment(revised_2026, c7, refused_by_terms([unmet(days_before_departure(-2))]), basis(['ex:terms'])).
assessment(revised_2026, c8, refused_by_terms([unmet(requested_by(hugo), lead_traveller(ivy))]), basis(['ex:terms'])).
assessment(directive_2015, c1, pay_fee(percent(25), fee(600), refund(1800), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c2, pay_fee(percent(100), fee(1800), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c3, refund(1500, within_days(14)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c4, pay_fee(percent(100), fee(2100), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c5, refund(1200, within_days(14)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD Art. 12(4)'])).
assessment(directive_2015, c6, voucher(value(1600), terms(as_agreed)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD 2015: no voucher rules'])).
assessment(revised_2026, c1, pay_fee(percent(25), fee(600), refund(1800), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(revised_2026, c2, pay_fee(percent(100), fee(1800), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])).
assessment(revised_2026, c3, refund(1500, within_days(14)), basis(['ex:terms', 'revised PTD: destination', 'PTD Art. 12(4)'])).
assessment(revised_2026, c4, refund(2100, within_days(14)), basis(['ex:terms', 'revised PTD: point of departure', 'PTD Art. 12(4)'])).
assessment(revised_2026, c5, refund(1200, within_days(14)), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])).
assessment(revised_2026, c6, voucher(value(1600), valid_months(12), unused_value_refunded), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])).
complaint_plan(directive_2015, k1, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])).
complaint_plan(directive_2015, k2, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])).
complaint_plan(revised_2026, k1, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])).
complaint_plan(revised_2026, k2, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])).
changed(cancellation(c4), from(pay_fee(percent(100), fee(2100), refund(0), within_days(14))), to(refund(2100, within_days(14)))).
changed(cancellation(c6), from(voucher(value(1600), terms(as_agreed))), to(voucher(value(1600), valid_months(12), unused_value_refunded))).
changed(complaint(k1), from(deadlines(set_by_national_law)), to(deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))).
changed(complaint(k2), from(deadlines(set_by_national_law)), to(deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))).

clause(1, regime(directive_2015), true).
clause(2, regime(revised_2026), true).
clause(9, conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), true).
clause(10, fee_band(60, 999, 25), true).
clause(12, fee_band(1, 29, 100), true).
clause(13, booking(bk1, lead(anna), price(2400)), true).
clause(14, booking(bk2, lead(ben), price(1800)), true).
clause(15, booking(bk3, lead(chloe), price(1500)), true).
clause(16, booking(bk4, lead(david), price(2100)), true).
clause(17, booking(bk5, lead(emma), price(1200)), true).
clause(18, booking(bk6, lead(farid), price(1600)), true).
clause(19, booking(bk7, lead(gina), price(900)), true).
clause(20, booking(bk8, lead(ivy), price(1300)), true).
clause(21, request(c1, bk1, by(anna), days(90), circumstances(none), voucher(not_offered)), true).
clause(22, request(c2, bk2, by(ben), days(20), circumstances(none), voucher(not_offered)), true).
clause(23, request(c3, bk3, by(chloe), days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), true).
clause(24, request(c4, bk4, by(david), days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), true).
clause(25, request(c5, bk5, by(emma), days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), true).
clause(26, request(c6, bk6, by(farid), days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), true).
clause(27, request(c7, bk7, by(gina), days(-2), circumstances(none), voucher(not_offered)), true).
clause(28, request(c8, bk8, by(hugo), days(40), circumstances(none), voucher(not_offered)), true).
clause(29, check(var('C'), 'ex:byLeadTraveller', met), ','(request(var('C'), var('B'), by(var('X')), var('__anon0'), var('__anon1'), var('__anon2')), booking(var('B'), lead(var('X')), var('__anon3')))).
clause(30, check(var('C'), 'ex:byLeadTraveller', unmet(requested_by(var('X')), lead_traveller(var('L')))), ','(request(var('C'), var('B'), by(var('X')), var('__anon4'), var('__anon5'), var('__anon6')), ','(booking(var('B'), lead(var('L')), var('__anon7')), \==(var('X'), var('L'))))).
clause(31, check(var('C'), 'ex:beforeDeparture', met), ','(request(var('C'), var('__anon8'), var('__anon9'), days(var('D')), var('__anon10'), var('__anon11')), >(var('D'), 0))).
clause(32, check(var('C'), 'ex:beforeDeparture', unmet(days_before_departure(var('D')))), ','(request(var('C'), var('__anon12'), var('__anon13'), days(var('D')), var('__anon14'), var('__anon15')), =<(var('D'), 0))).
clause(33, unmet(var('__anon16'), [], []), true).
clause(34, unmet(var('C'), [var('K')|var('Ks')], var('Reasons')), ','(check(var('C'), var('K'), met), unmet(var('C'), var('Ks'), var('Reasons')))).
clause(35, unmet(var('C'), [var('K')|var('Ks')], [var('Why')|var('Reasons')]), ','(check(var('C'), var('K'), var('Why')), ','(\==(var('Why'), met), unmet(var('C'), var('Ks'), var('Reasons'))))).
clause(36, policy_result(var('C'), permit), ','(request(var('C'), var('__anon17'), var('__anon18'), var('__anon19'), var('__anon20'), var('__anon21')), ','(conditions('ex:cancellation', var('Ks')), unmet(var('C'), var('Ks'), [])))).
clause(37, policy_result(var('C'), refuse(var('Reasons'))), ','(request(var('C'), var('__anon22'), var('__anon23'), var('__anon24'), var('__anon25'), var('__anon26')), ','(conditions('ex:cancellation', var('Ks')), ','(unmet(var('C'), var('Ks'), var('Reasons')), \==(var('Reasons'), []))))).
clause(38, free_cancellation(directive_2015, none, no, 'PTD Art. 12(1)'), true).
clause(39, free_cancellation(directive_2015, at(destination, var('__anon27')), yes, 'PTD Art. 12(2)'), true).
clause(40, free_cancellation(directive_2015, at(departure, var('__anon28')), no, 'PTD Art. 12(1)'), true).
clause(41, free_cancellation(revised_2026, none, no, 'PTD Art. 12(1)'), true).
clause(42, free_cancellation(revised_2026, at(destination, var('__anon29')), yes, 'revised PTD: destination'), true).
clause(43, free_cancellation(revised_2026, at(departure, var('__anon30')), yes, 'revised PTD: point of departure'), true).
clause(44, settle(var('__anon31'), no, var('P'), var('D'), var('__anon32'), pay_fee(percent(var('Pct')), fee(var('F')), refund(var('Back')), within_days(14))), ','(fee_band(var('Min'), var('Max'), var('Pct')), ','(=<(var('Min'), var('D')), ','(=<(var('D'), var('Max')), ','(is(var('F'), //(*(var('P'), var('Pct')), 100)), is(var('Back'), -(var('P'), var('F')))))))).
clause(45, settle(var('__anon33'), yes, var('P'), var('__anon34'), not_offered, refund(var('P'), within_days(14))), true).
clause(46, settle(var('__anon35'), yes, var('P'), var('__anon36'), offered(refused), refund(var('P'), within_days(14))), true).
clause(47, settle(directive_2015, yes, var('P'), var('__anon37'), offered(accepted), voucher(value(var('P')), terms(as_agreed))), true).
clause(48, settle(revised_2026, yes, var('P'), var('__anon38'), offered(accepted), voucher(value(var('P')), valid_months(12), unused_value_refunded)), true).
clause(49, money_basis(var('__anon39'), no, var('__anon40'), 'PTD Art. 12(4)'), true).
clause(50, money_basis(var('__anon41'), yes, not_offered, 'PTD Art. 12(4)'), true).
clause(51, money_basis(directive_2015, yes, offered(refused), 'PTD Art. 12(4)'), true).
clause(52, money_basis(directive_2015, yes, offered(accepted), 'PTD 2015: no voucher rules'), true).
clause(53, money_basis(revised_2026, yes, offered(var('__anon42')), 'revised PTD: vouchers'), true).
clause(54, assessment(var('R'), var('C'), refused_by_terms(var('Reasons')), basis(['ex:terms'])), ','(regime(var('R')), policy_result(var('C'), refuse(var('Reasons'))))).
clause(55, assessment(var('R'), var('C'), var('Outcome'), basis(['ex:terms', var('Free'), var('Money')])), ','(regime(var('R')), ','(policy_result(var('C'), permit), ','(request(var('C'), var('B'), var('__anon43'), days(var('D')), circumstances(var('What')), voucher(var('V'))), ','(booking(var('B'), var('__anon44'), price(var('P'))), ','(free_cancellation(var('R'), var('What'), var('F'), var('Free')), ','(settle(var('R'), var('F'), var('P'), var('D'), var('V'), var('Outcome')), money_basis(var('R'), var('F'), var('V'), var('Money'))))))))).
clause(56, complaint(k1, 'pool closed for the whole stay'), true).
clause(57, complaint(k2, 'refund not received'), true).
clause(58, complaint_plan(directive_2015, var('K'), deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), complaint(var('K'), var('__anon45'))).
clause(59, complaint_plan(revised_2026, var('K'), deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), complaint(var('K'), var('__anon46'))).
clause(60, changed(cancellation(var('C')), from(var('Old')), to(var('New'))), ','(assessment(directive_2015, var('C'), var('Old'), var('__anon47')), ','(assessment(revised_2026, var('C'), var('New'), var('__anon48')), \==(var('Old'), var('New'))))).
clause(61, changed(complaint(var('K')), from(var('Old')), to(var('New'))), ','(complaint_plan(directive_2015, var('K'), var('Old'), var('__anon49')), ','(complaint_plan(revised_2026, var('K'), var('New'), var('__anon50')), \==(var('Old'), var('New'))))).

step(assessment(directive_2015, c7, refused_by_terms([unmet(days_before_departure(-2))]), basis(['ex:terms'])), rule(54), [=('R', directive_2015), =('C', c7), =('Reasons', [unmet(days_before_departure(-2))])], [regime(directive_2015), policy_result(c7, refuse([unmet(days_before_departure(-2))]))]).
step(regime(directive_2015), fact(1), [], []).
step(policy_result(c7, refuse([unmet(days_before_departure(-2))])), rule(37), [=('C', c7), =('Reasons', [unmet(days_before_departure(-2))]), =('__anon22', bk7), =('__anon23', by(gina)), =('__anon24', days(-2)), =('__anon25', circumstances(none)), =('__anon26', voucher(not_offered)), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [request(c7, bk7, by(gina), days(-2), circumstances(none), voucher(not_offered)), conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c7, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [unmet(days_before_departure(-2))]), \==([unmet(days_before_departure(-2))], [])]).
step(request(c7, bk7, by(gina), days(-2), circumstances(none), voucher(not_offered)), fact(27), [], []).
step(conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), fact(9), [], []).
step(unmet(c7, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [unmet(days_before_departure(-2))]), rule(34), [=('C', c7), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [unmet(days_before_departure(-2))])], [check(c7, 'ex:byLeadTraveller', met), unmet(c7, ['ex:beforeDeparture'], [unmet(days_before_departure(-2))])]).
step(check(c7, 'ex:byLeadTraveller', met), rule(29), [=('C', c7), =('B', bk7), =('X', gina), =('__anon0', days(-2)), =('__anon1', circumstances(none)), =('__anon2', voucher(not_offered)), =('__anon3', price(900))], [request(c7, bk7, by(gina), days(-2), circumstances(none), voucher(not_offered)), booking(bk7, lead(gina), price(900))]).
step(booking(bk7, lead(gina), price(900)), fact(19), [], []).
step(unmet(c7, ['ex:beforeDeparture'], [unmet(days_before_departure(-2))]), rule(35), [=('C', c7), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Why', unmet(days_before_departure(-2))), =('Reasons', [])], [check(c7, 'ex:beforeDeparture', unmet(days_before_departure(-2))), \==(unmet(days_before_departure(-2)), met), unmet(c7, [], [])]).
step(check(c7, 'ex:beforeDeparture', unmet(days_before_departure(-2))), rule(32), [=('C', c7), =('D', -2), =('__anon12', bk7), =('__anon13', by(gina)), =('__anon14', circumstances(none)), =('__anon15', voucher(not_offered))], [request(c7, bk7, by(gina), days(-2), circumstances(none), voucher(not_offered)), =<(-2, 0)]).
step(=<(-2, 0), builtin, [], []).
step(\==(unmet(days_before_departure(-2)), met), builtin, [], []).
step(unmet(c7, [], []), fact(33), [=('__anon16', c7)], []).
step(\==([unmet(days_before_departure(-2))], []), builtin, [], []).
step(assessment(directive_2015, c8, refused_by_terms([unmet(requested_by(hugo), lead_traveller(ivy))]), basis(['ex:terms'])), rule(54), [=('R', directive_2015), =('C', c8), =('Reasons', [unmet(requested_by(hugo), lead_traveller(ivy))])], [regime(directive_2015), policy_result(c8, refuse([unmet(requested_by(hugo), lead_traveller(ivy))]))]).
step(policy_result(c8, refuse([unmet(requested_by(hugo), lead_traveller(ivy))])), rule(37), [=('C', c8), =('Reasons', [unmet(requested_by(hugo), lead_traveller(ivy))]), =('__anon22', bk8), =('__anon23', by(hugo)), =('__anon24', days(40)), =('__anon25', circumstances(none)), =('__anon26', voucher(not_offered)), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [request(c8, bk8, by(hugo), days(40), circumstances(none), voucher(not_offered)), conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c8, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [unmet(requested_by(hugo), lead_traveller(ivy))]), \==([unmet(requested_by(hugo), lead_traveller(ivy))], [])]).
step(request(c8, bk8, by(hugo), days(40), circumstances(none), voucher(not_offered)), fact(28), [], []).
step(unmet(c8, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [unmet(requested_by(hugo), lead_traveller(ivy))]), rule(35), [=('C', c8), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Why', unmet(requested_by(hugo), lead_traveller(ivy))), =('Reasons', [])], [check(c8, 'ex:byLeadTraveller', unmet(requested_by(hugo), lead_traveller(ivy))), \==(unmet(requested_by(hugo), lead_traveller(ivy)), met), unmet(c8, ['ex:beforeDeparture'], [])]).
step(check(c8, 'ex:byLeadTraveller', unmet(requested_by(hugo), lead_traveller(ivy))), rule(30), [=('C', c8), =('X', hugo), =('L', ivy), =('B', bk8), =('__anon4', days(40)), =('__anon5', circumstances(none)), =('__anon6', voucher(not_offered)), =('__anon7', price(1300))], [request(c8, bk8, by(hugo), days(40), circumstances(none), voucher(not_offered)), booking(bk8, lead(ivy), price(1300)), \==(hugo, ivy)]).
step(booking(bk8, lead(ivy), price(1300)), fact(20), [], []).
step(\==(hugo, ivy), builtin, [], []).
step(\==(unmet(requested_by(hugo), lead_traveller(ivy)), met), builtin, [], []).
step(unmet(c8, ['ex:beforeDeparture'], []), rule(34), [=('C', c8), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [check(c8, 'ex:beforeDeparture', met), unmet(c8, [], [])]).
step(check(c8, 'ex:beforeDeparture', met), rule(31), [=('C', c8), =('__anon8', bk8), =('__anon9', by(hugo)), =('D', 40), =('__anon10', circumstances(none)), =('__anon11', voucher(not_offered))], [request(c8, bk8, by(hugo), days(40), circumstances(none), voucher(not_offered)), >(40, 0)]).
step(>(40, 0), builtin, [], []).
step(unmet(c8, [], []), fact(33), [=('__anon16', c8)], []).
step(\==([unmet(requested_by(hugo), lead_traveller(ivy))], []), builtin, [], []).
step(assessment(revised_2026, c7, refused_by_terms([unmet(days_before_departure(-2))]), basis(['ex:terms'])), rule(54), [=('R', revised_2026), =('C', c7), =('Reasons', [unmet(days_before_departure(-2))])], [regime(revised_2026), policy_result(c7, refuse([unmet(days_before_departure(-2))]))]).
step(regime(revised_2026), fact(2), [], []).
step(assessment(revised_2026, c8, refused_by_terms([unmet(requested_by(hugo), lead_traveller(ivy))]), basis(['ex:terms'])), rule(54), [=('R', revised_2026), =('C', c8), =('Reasons', [unmet(requested_by(hugo), lead_traveller(ivy))])], [regime(revised_2026), policy_result(c8, refuse([unmet(requested_by(hugo), lead_traveller(ivy))]))]).
step(assessment(directive_2015, c1, pay_fee(percent(25), fee(600), refund(1800), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(55), [=('R', directive_2015), =('C', c1), =('Outcome', pay_fee(percent(25), fee(600), refund(1800), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('B', bk1), =('__anon43', by(anna)), =('D', 90), =('What', none), =('V', not_offered), =('__anon44', lead(anna)), =('P', 2400), =('F', no)], [regime(directive_2015), policy_result(c1, permit), request(c1, bk1, by(anna), days(90), circumstances(none), voucher(not_offered)), booking(bk1, lead(anna), price(2400)), free_cancellation(directive_2015, none, no, 'PTD Art. 12(1)'), settle(directive_2015, no, 2400, 90, not_offered, pay_fee(percent(25), fee(600), refund(1800), within_days(14))), money_basis(directive_2015, no, not_offered, 'PTD Art. 12(4)')]).
step(policy_result(c1, permit), rule(36), [=('C', c1), =('__anon17', bk1), =('__anon18', by(anna)), =('__anon19', days(90)), =('__anon20', circumstances(none)), =('__anon21', voucher(not_offered)), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [request(c1, bk1, by(anna), days(90), circumstances(none), voucher(not_offered)), conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c1, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(request(c1, bk1, by(anna), days(90), circumstances(none), voucher(not_offered)), fact(21), [], []).
step(unmet(c1, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(34), [=('C', c1), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [check(c1, 'ex:byLeadTraveller', met), unmet(c1, ['ex:beforeDeparture'], [])]).
step(check(c1, 'ex:byLeadTraveller', met), rule(29), [=('C', c1), =('B', bk1), =('X', anna), =('__anon0', days(90)), =('__anon1', circumstances(none)), =('__anon2', voucher(not_offered)), =('__anon3', price(2400))], [request(c1, bk1, by(anna), days(90), circumstances(none), voucher(not_offered)), booking(bk1, lead(anna), price(2400))]).
step(booking(bk1, lead(anna), price(2400)), fact(13), [], []).
step(unmet(c1, ['ex:beforeDeparture'], []), rule(34), [=('C', c1), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [check(c1, 'ex:beforeDeparture', met), unmet(c1, [], [])]).
step(check(c1, 'ex:beforeDeparture', met), rule(31), [=('C', c1), =('__anon8', bk1), =('__anon9', by(anna)), =('D', 90), =('__anon10', circumstances(none)), =('__anon11', voucher(not_offered))], [request(c1, bk1, by(anna), days(90), circumstances(none), voucher(not_offered)), >(90, 0)]).
step(>(90, 0), builtin, [], []).
step(unmet(c1, [], []), fact(33), [=('__anon16', c1)], []).
step(free_cancellation(directive_2015, none, no, 'PTD Art. 12(1)'), fact(38), [], []).
step(settle(directive_2015, no, 2400, 90, not_offered, pay_fee(percent(25), fee(600), refund(1800), within_days(14))), rule(44), [=('__anon31', directive_2015), =('P', 2400), =('D', 90), =('__anon32', not_offered), =('Pct', 25), =('F', 600), =('Back', 1800), =('Min', 60), =('Max', 999)], [fee_band(60, 999, 25), =<(60, 90), =<(90, 999), is(600, //(*(2400, 25), 100)), is(1800, -(2400, 600))]).
step(fee_band(60, 999, 25), fact(10), [], []).
step(=<(60, 90), builtin, [], []).
step(=<(90, 999), builtin, [], []).
step(is(600, //(*(2400, 25), 100)), builtin, [], []).
step(is(1800, -(2400, 600)), builtin, [], []).
step(money_basis(directive_2015, no, not_offered, 'PTD Art. 12(4)'), fact(49), [=('__anon39', directive_2015), =('__anon40', not_offered)], []).
step(assessment(directive_2015, c2, pay_fee(percent(100), fee(1800), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(55), [=('R', directive_2015), =('C', c2), =('Outcome', pay_fee(percent(100), fee(1800), refund(0), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('B', bk2), =('__anon43', by(ben)), =('D', 20), =('What', none), =('V', not_offered), =('__anon44', lead(ben)), =('P', 1800), =('F', no)], [regime(directive_2015), policy_result(c2, permit), request(c2, bk2, by(ben), days(20), circumstances(none), voucher(not_offered)), booking(bk2, lead(ben), price(1800)), free_cancellation(directive_2015, none, no, 'PTD Art. 12(1)'), settle(directive_2015, no, 1800, 20, not_offered, pay_fee(percent(100), fee(1800), refund(0), within_days(14))), money_basis(directive_2015, no, not_offered, 'PTD Art. 12(4)')]).
step(policy_result(c2, permit), rule(36), [=('C', c2), =('__anon17', bk2), =('__anon18', by(ben)), =('__anon19', days(20)), =('__anon20', circumstances(none)), =('__anon21', voucher(not_offered)), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [request(c2, bk2, by(ben), days(20), circumstances(none), voucher(not_offered)), conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c2, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(request(c2, bk2, by(ben), days(20), circumstances(none), voucher(not_offered)), fact(22), [], []).
step(unmet(c2, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(34), [=('C', c2), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [check(c2, 'ex:byLeadTraveller', met), unmet(c2, ['ex:beforeDeparture'], [])]).
step(check(c2, 'ex:byLeadTraveller', met), rule(29), [=('C', c2), =('B', bk2), =('X', ben), =('__anon0', days(20)), =('__anon1', circumstances(none)), =('__anon2', voucher(not_offered)), =('__anon3', price(1800))], [request(c2, bk2, by(ben), days(20), circumstances(none), voucher(not_offered)), booking(bk2, lead(ben), price(1800))]).
step(booking(bk2, lead(ben), price(1800)), fact(14), [], []).
step(unmet(c2, ['ex:beforeDeparture'], []), rule(34), [=('C', c2), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [check(c2, 'ex:beforeDeparture', met), unmet(c2, [], [])]).
step(check(c2, 'ex:beforeDeparture', met), rule(31), [=('C', c2), =('__anon8', bk2), =('__anon9', by(ben)), =('D', 20), =('__anon10', circumstances(none)), =('__anon11', voucher(not_offered))], [request(c2, bk2, by(ben), days(20), circumstances(none), voucher(not_offered)), >(20, 0)]).
step(>(20, 0), builtin, [], []).
step(unmet(c2, [], []), fact(33), [=('__anon16', c2)], []).
step(settle(directive_2015, no, 1800, 20, not_offered, pay_fee(percent(100), fee(1800), refund(0), within_days(14))), rule(44), [=('__anon31', directive_2015), =('P', 1800), =('D', 20), =('__anon32', not_offered), =('Pct', 100), =('F', 1800), =('Back', 0), =('Min', 1), =('Max', 29)], [fee_band(1, 29, 100), =<(1, 20), =<(20, 29), is(1800, //(*(1800, 100), 100)), is(0, -(1800, 1800))]).
step(fee_band(1, 29, 100), fact(12), [], []).
step(=<(1, 20), builtin, [], []).
step(=<(20, 29), builtin, [], []).
step(is(1800, //(*(1800, 100), 100)), builtin, [], []).
step(is(0, -(1800, 1800)), builtin, [], []).
step(assessment(directive_2015, c3, refund(1500, within_days(14)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD Art. 12(4)'])), rule(55), [=('R', directive_2015), =('C', c3), =('Outcome', refund(1500, within_days(14))), =('Free', 'PTD Art. 12(2)'), =('Money', 'PTD Art. 12(4)'), =('B', bk3), =('__anon43', by(chloe)), =('D', 10), =('What', at(destination, hurricane)), =('V', not_offered), =('__anon44', lead(chloe)), =('P', 1500), =('F', yes)], [regime(directive_2015), policy_result(c3, permit), request(c3, bk3, by(chloe), days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), booking(bk3, lead(chloe), price(1500)), free_cancellation(directive_2015, at(destination, hurricane), yes, 'PTD Art. 12(2)'), settle(directive_2015, yes, 1500, 10, not_offered, refund(1500, within_days(14))), money_basis(directive_2015, yes, not_offered, 'PTD Art. 12(4)')]).
step(policy_result(c3, permit), rule(36), [=('C', c3), =('__anon17', bk3), =('__anon18', by(chloe)), =('__anon19', days(10)), =('__anon20', circumstances(at(destination, hurricane))), =('__anon21', voucher(not_offered)), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [request(c3, bk3, by(chloe), days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c3, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(request(c3, bk3, by(chloe), days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), fact(23), [], []).
step(unmet(c3, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(34), [=('C', c3), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [check(c3, 'ex:byLeadTraveller', met), unmet(c3, ['ex:beforeDeparture'], [])]).
step(check(c3, 'ex:byLeadTraveller', met), rule(29), [=('C', c3), =('B', bk3), =('X', chloe), =('__anon0', days(10)), =('__anon1', circumstances(at(destination, hurricane))), =('__anon2', voucher(not_offered)), =('__anon3', price(1500))], [request(c3, bk3, by(chloe), days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), booking(bk3, lead(chloe), price(1500))]).
step(booking(bk3, lead(chloe), price(1500)), fact(15), [], []).
step(unmet(c3, ['ex:beforeDeparture'], []), rule(34), [=('C', c3), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [check(c3, 'ex:beforeDeparture', met), unmet(c3, [], [])]).
step(check(c3, 'ex:beforeDeparture', met), rule(31), [=('C', c3), =('__anon8', bk3), =('__anon9', by(chloe)), =('D', 10), =('__anon10', circumstances(at(destination, hurricane))), =('__anon11', voucher(not_offered))], [request(c3, bk3, by(chloe), days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), >(10, 0)]).
step(>(10, 0), builtin, [], []).
step(unmet(c3, [], []), fact(33), [=('__anon16', c3)], []).
step(free_cancellation(directive_2015, at(destination, hurricane), yes, 'PTD Art. 12(2)'), fact(39), [=('__anon27', hurricane)], []).
step(settle(directive_2015, yes, 1500, 10, not_offered, refund(1500, within_days(14))), fact(45), [=('__anon33', directive_2015), =('P', 1500), =('__anon34', 10)], []).
step(money_basis(directive_2015, yes, not_offered, 'PTD Art. 12(4)'), fact(50), [=('__anon41', directive_2015)], []).
step(assessment(directive_2015, c4, pay_fee(percent(100), fee(2100), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(55), [=('R', directive_2015), =('C', c4), =('Outcome', pay_fee(percent(100), fee(2100), refund(0), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('B', bk4), =('__anon43', by(david)), =('D', 5), =('What', at(departure, airport_closed_by_floods)), =('V', not_offered), =('__anon44', lead(david)), =('P', 2100), =('F', no)], [regime(directive_2015), policy_result(c4, permit), request(c4, bk4, by(david), days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), booking(bk4, lead(david), price(2100)), free_cancellation(directive_2015, at(departure, airport_closed_by_floods), no, 'PTD Art. 12(1)'), settle(directive_2015, no, 2100, 5, not_offered, pay_fee(percent(100), fee(2100), refund(0), within_days(14))), money_basis(directive_2015, no, not_offered, 'PTD Art. 12(4)')]).
step(policy_result(c4, permit), rule(36), [=('C', c4), =('__anon17', bk4), =('__anon18', by(david)), =('__anon19', days(5)), =('__anon20', circumstances(at(departure, airport_closed_by_floods))), =('__anon21', voucher(not_offered)), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [request(c4, bk4, by(david), days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c4, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(request(c4, bk4, by(david), days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), fact(24), [], []).
step(unmet(c4, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(34), [=('C', c4), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [check(c4, 'ex:byLeadTraveller', met), unmet(c4, ['ex:beforeDeparture'], [])]).
step(check(c4, 'ex:byLeadTraveller', met), rule(29), [=('C', c4), =('B', bk4), =('X', david), =('__anon0', days(5)), =('__anon1', circumstances(at(departure, airport_closed_by_floods))), =('__anon2', voucher(not_offered)), =('__anon3', price(2100))], [request(c4, bk4, by(david), days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), booking(bk4, lead(david), price(2100))]).
step(booking(bk4, lead(david), price(2100)), fact(16), [], []).
step(unmet(c4, ['ex:beforeDeparture'], []), rule(34), [=('C', c4), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [check(c4, 'ex:beforeDeparture', met), unmet(c4, [], [])]).
step(check(c4, 'ex:beforeDeparture', met), rule(31), [=('C', c4), =('__anon8', bk4), =('__anon9', by(david)), =('D', 5), =('__anon10', circumstances(at(departure, airport_closed_by_floods))), =('__anon11', voucher(not_offered))], [request(c4, bk4, by(david), days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), >(5, 0)]).
step(>(5, 0), builtin, [], []).
step(unmet(c4, [], []), fact(33), [=('__anon16', c4)], []).
step(free_cancellation(directive_2015, at(departure, airport_closed_by_floods), no, 'PTD Art. 12(1)'), fact(40), [=('__anon28', airport_closed_by_floods)], []).
step(settle(directive_2015, no, 2100, 5, not_offered, pay_fee(percent(100), fee(2100), refund(0), within_days(14))), rule(44), [=('__anon31', directive_2015), =('P', 2100), =('D', 5), =('__anon32', not_offered), =('Pct', 100), =('F', 2100), =('Back', 0), =('Min', 1), =('Max', 29)], [fee_band(1, 29, 100), =<(1, 5), =<(5, 29), is(2100, //(*(2100, 100), 100)), is(0, -(2100, 2100))]).
step(=<(1, 5), builtin, [], []).
step(=<(5, 29), builtin, [], []).
step(is(2100, //(*(2100, 100), 100)), builtin, [], []).
step(is(0, -(2100, 2100)), builtin, [], []).
step(assessment(directive_2015, c5, refund(1200, within_days(14)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD Art. 12(4)'])), rule(55), [=('R', directive_2015), =('C', c5), =('Outcome', refund(1200, within_days(14))), =('Free', 'PTD Art. 12(2)'), =('Money', 'PTD Art. 12(4)'), =('B', bk5), =('__anon43', by(emma)), =('D', 12), =('What', at(destination, hurricane)), =('V', offered(refused)), =('__anon44', lead(emma)), =('P', 1200), =('F', yes)], [regime(directive_2015), policy_result(c5, permit), request(c5, bk5, by(emma), days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), booking(bk5, lead(emma), price(1200)), free_cancellation(directive_2015, at(destination, hurricane), yes, 'PTD Art. 12(2)'), settle(directive_2015, yes, 1200, 12, offered(refused), refund(1200, within_days(14))), money_basis(directive_2015, yes, offered(refused), 'PTD Art. 12(4)')]).
step(policy_result(c5, permit), rule(36), [=('C', c5), =('__anon17', bk5), =('__anon18', by(emma)), =('__anon19', days(12)), =('__anon20', circumstances(at(destination, hurricane))), =('__anon21', voucher(offered(refused))), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [request(c5, bk5, by(emma), days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c5, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(request(c5, bk5, by(emma), days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), fact(25), [], []).
step(unmet(c5, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(34), [=('C', c5), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [check(c5, 'ex:byLeadTraveller', met), unmet(c5, ['ex:beforeDeparture'], [])]).
step(check(c5, 'ex:byLeadTraveller', met), rule(29), [=('C', c5), =('B', bk5), =('X', emma), =('__anon0', days(12)), =('__anon1', circumstances(at(destination, hurricane))), =('__anon2', voucher(offered(refused))), =('__anon3', price(1200))], [request(c5, bk5, by(emma), days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), booking(bk5, lead(emma), price(1200))]).
step(booking(bk5, lead(emma), price(1200)), fact(17), [], []).
step(unmet(c5, ['ex:beforeDeparture'], []), rule(34), [=('C', c5), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [check(c5, 'ex:beforeDeparture', met), unmet(c5, [], [])]).
step(check(c5, 'ex:beforeDeparture', met), rule(31), [=('C', c5), =('__anon8', bk5), =('__anon9', by(emma)), =('D', 12), =('__anon10', circumstances(at(destination, hurricane))), =('__anon11', voucher(offered(refused)))], [request(c5, bk5, by(emma), days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), >(12, 0)]).
step(>(12, 0), builtin, [], []).
step(unmet(c5, [], []), fact(33), [=('__anon16', c5)], []).
step(settle(directive_2015, yes, 1200, 12, offered(refused), refund(1200, within_days(14))), fact(46), [=('__anon35', directive_2015), =('P', 1200), =('__anon36', 12)], []).
step(money_basis(directive_2015, yes, offered(refused), 'PTD Art. 12(4)'), fact(51), [], []).
step(assessment(directive_2015, c6, voucher(value(1600), terms(as_agreed)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD 2015: no voucher rules'])), rule(55), [=('R', directive_2015), =('C', c6), =('Outcome', voucher(value(1600), terms(as_agreed))), =('Free', 'PTD Art. 12(2)'), =('Money', 'PTD 2015: no voucher rules'), =('B', bk6), =('__anon43', by(farid)), =('D', 12), =('What', at(destination, hurricane)), =('V', offered(accepted)), =('__anon44', lead(farid)), =('P', 1600), =('F', yes)], [regime(directive_2015), policy_result(c6, permit), request(c6, bk6, by(farid), days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), booking(bk6, lead(farid), price(1600)), free_cancellation(directive_2015, at(destination, hurricane), yes, 'PTD Art. 12(2)'), settle(directive_2015, yes, 1600, 12, offered(accepted), voucher(value(1600), terms(as_agreed))), money_basis(directive_2015, yes, offered(accepted), 'PTD 2015: no voucher rules')]).
step(policy_result(c6, permit), rule(36), [=('C', c6), =('__anon17', bk6), =('__anon18', by(farid)), =('__anon19', days(12)), =('__anon20', circumstances(at(destination, hurricane))), =('__anon21', voucher(offered(accepted))), =('Ks', ['ex:byLeadTraveller', 'ex:beforeDeparture'])], [request(c6, bk6, by(farid), days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), conditions('ex:cancellation', ['ex:byLeadTraveller', 'ex:beforeDeparture']), unmet(c6, ['ex:byLeadTraveller', 'ex:beforeDeparture'], [])]).
step(request(c6, bk6, by(farid), days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), fact(26), [], []).
step(unmet(c6, ['ex:byLeadTraveller', 'ex:beforeDeparture'], []), rule(34), [=('C', c6), =('K', 'ex:byLeadTraveller'), =('Ks', ['ex:beforeDeparture']), =('Reasons', [])], [check(c6, 'ex:byLeadTraveller', met), unmet(c6, ['ex:beforeDeparture'], [])]).
step(check(c6, 'ex:byLeadTraveller', met), rule(29), [=('C', c6), =('B', bk6), =('X', farid), =('__anon0', days(12)), =('__anon1', circumstances(at(destination, hurricane))), =('__anon2', voucher(offered(accepted))), =('__anon3', price(1600))], [request(c6, bk6, by(farid), days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), booking(bk6, lead(farid), price(1600))]).
step(booking(bk6, lead(farid), price(1600)), fact(18), [], []).
step(unmet(c6, ['ex:beforeDeparture'], []), rule(34), [=('C', c6), =('K', 'ex:beforeDeparture'), =('Ks', []), =('Reasons', [])], [check(c6, 'ex:beforeDeparture', met), unmet(c6, [], [])]).
step(check(c6, 'ex:beforeDeparture', met), rule(31), [=('C', c6), =('__anon8', bk6), =('__anon9', by(farid)), =('D', 12), =('__anon10', circumstances(at(destination, hurricane))), =('__anon11', voucher(offered(accepted)))], [request(c6, bk6, by(farid), days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), >(12, 0)]).
step(unmet(c6, [], []), fact(33), [=('__anon16', c6)], []).
step(settle(directive_2015, yes, 1600, 12, offered(accepted), voucher(value(1600), terms(as_agreed))), fact(47), [=('P', 1600), =('__anon37', 12)], []).
step(money_basis(directive_2015, yes, offered(accepted), 'PTD 2015: no voucher rules'), fact(52), [], []).
step(assessment(revised_2026, c1, pay_fee(percent(25), fee(600), refund(1800), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(55), [=('R', revised_2026), =('C', c1), =('Outcome', pay_fee(percent(25), fee(600), refund(1800), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('B', bk1), =('__anon43', by(anna)), =('D', 90), =('What', none), =('V', not_offered), =('__anon44', lead(anna)), =('P', 2400), =('F', no)], [regime(revised_2026), policy_result(c1, permit), request(c1, bk1, by(anna), days(90), circumstances(none), voucher(not_offered)), booking(bk1, lead(anna), price(2400)), free_cancellation(revised_2026, none, no, 'PTD Art. 12(1)'), settle(revised_2026, no, 2400, 90, not_offered, pay_fee(percent(25), fee(600), refund(1800), within_days(14))), money_basis(revised_2026, no, not_offered, 'PTD Art. 12(4)')]).
step(free_cancellation(revised_2026, none, no, 'PTD Art. 12(1)'), fact(41), [], []).
step(settle(revised_2026, no, 2400, 90, not_offered, pay_fee(percent(25), fee(600), refund(1800), within_days(14))), rule(44), [=('__anon31', revised_2026), =('P', 2400), =('D', 90), =('__anon32', not_offered), =('Pct', 25), =('F', 600), =('Back', 1800), =('Min', 60), =('Max', 999)], [fee_band(60, 999, 25), =<(60, 90), =<(90, 999), is(600, //(*(2400, 25), 100)), is(1800, -(2400, 600))]).
step(money_basis(revised_2026, no, not_offered, 'PTD Art. 12(4)'), fact(49), [=('__anon39', revised_2026), =('__anon40', not_offered)], []).
step(assessment(revised_2026, c2, pay_fee(percent(100), fee(1800), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), rule(55), [=('R', revised_2026), =('C', c2), =('Outcome', pay_fee(percent(100), fee(1800), refund(0), within_days(14))), =('Free', 'PTD Art. 12(1)'), =('Money', 'PTD Art. 12(4)'), =('B', bk2), =('__anon43', by(ben)), =('D', 20), =('What', none), =('V', not_offered), =('__anon44', lead(ben)), =('P', 1800), =('F', no)], [regime(revised_2026), policy_result(c2, permit), request(c2, bk2, by(ben), days(20), circumstances(none), voucher(not_offered)), booking(bk2, lead(ben), price(1800)), free_cancellation(revised_2026, none, no, 'PTD Art. 12(1)'), settle(revised_2026, no, 1800, 20, not_offered, pay_fee(percent(100), fee(1800), refund(0), within_days(14))), money_basis(revised_2026, no, not_offered, 'PTD Art. 12(4)')]).
step(settle(revised_2026, no, 1800, 20, not_offered, pay_fee(percent(100), fee(1800), refund(0), within_days(14))), rule(44), [=('__anon31', revised_2026), =('P', 1800), =('D', 20), =('__anon32', not_offered), =('Pct', 100), =('F', 1800), =('Back', 0), =('Min', 1), =('Max', 29)], [fee_band(1, 29, 100), =<(1, 20), =<(20, 29), is(1800, //(*(1800, 100), 100)), is(0, -(1800, 1800))]).
step(assessment(revised_2026, c3, refund(1500, within_days(14)), basis(['ex:terms', 'revised PTD: destination', 'PTD Art. 12(4)'])), rule(55), [=('R', revised_2026), =('C', c3), =('Outcome', refund(1500, within_days(14))), =('Free', 'revised PTD: destination'), =('Money', 'PTD Art. 12(4)'), =('B', bk3), =('__anon43', by(chloe)), =('D', 10), =('What', at(destination, hurricane)), =('V', not_offered), =('__anon44', lead(chloe)), =('P', 1500), =('F', yes)], [regime(revised_2026), policy_result(c3, permit), request(c3, bk3, by(chloe), days(10), circumstances(at(destination, hurricane)), voucher(not_offered)), booking(bk3, lead(chloe), price(1500)), free_cancellation(revised_2026, at(destination, hurricane), yes, 'revised PTD: destination'), settle(revised_2026, yes, 1500, 10, not_offered, refund(1500, within_days(14))), money_basis(revised_2026, yes, not_offered, 'PTD Art. 12(4)')]).
step(free_cancellation(revised_2026, at(destination, hurricane), yes, 'revised PTD: destination'), fact(42), [=('__anon29', hurricane)], []).
step(settle(revised_2026, yes, 1500, 10, not_offered, refund(1500, within_days(14))), fact(45), [=('__anon33', revised_2026), =('P', 1500), =('__anon34', 10)], []).
step(money_basis(revised_2026, yes, not_offered, 'PTD Art. 12(4)'), fact(50), [=('__anon41', revised_2026)], []).
step(assessment(revised_2026, c4, refund(2100, within_days(14)), basis(['ex:terms', 'revised PTD: point of departure', 'PTD Art. 12(4)'])), rule(55), [=('R', revised_2026), =('C', c4), =('Outcome', refund(2100, within_days(14))), =('Free', 'revised PTD: point of departure'), =('Money', 'PTD Art. 12(4)'), =('B', bk4), =('__anon43', by(david)), =('D', 5), =('What', at(departure, airport_closed_by_floods)), =('V', not_offered), =('__anon44', lead(david)), =('P', 2100), =('F', yes)], [regime(revised_2026), policy_result(c4, permit), request(c4, bk4, by(david), days(5), circumstances(at(departure, airport_closed_by_floods)), voucher(not_offered)), booking(bk4, lead(david), price(2100)), free_cancellation(revised_2026, at(departure, airport_closed_by_floods), yes, 'revised PTD: point of departure'), settle(revised_2026, yes, 2100, 5, not_offered, refund(2100, within_days(14))), money_basis(revised_2026, yes, not_offered, 'PTD Art. 12(4)')]).
step(free_cancellation(revised_2026, at(departure, airport_closed_by_floods), yes, 'revised PTD: point of departure'), fact(43), [=('__anon30', airport_closed_by_floods)], []).
step(settle(revised_2026, yes, 2100, 5, not_offered, refund(2100, within_days(14))), fact(45), [=('__anon33', revised_2026), =('P', 2100), =('__anon34', 5)], []).
step(assessment(revised_2026, c5, refund(1200, within_days(14)), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])), rule(55), [=('R', revised_2026), =('C', c5), =('Outcome', refund(1200, within_days(14))), =('Free', 'revised PTD: destination'), =('Money', 'revised PTD: vouchers'), =('B', bk5), =('__anon43', by(emma)), =('D', 12), =('What', at(destination, hurricane)), =('V', offered(refused)), =('__anon44', lead(emma)), =('P', 1200), =('F', yes)], [regime(revised_2026), policy_result(c5, permit), request(c5, bk5, by(emma), days(12), circumstances(at(destination, hurricane)), voucher(offered(refused))), booking(bk5, lead(emma), price(1200)), free_cancellation(revised_2026, at(destination, hurricane), yes, 'revised PTD: destination'), settle(revised_2026, yes, 1200, 12, offered(refused), refund(1200, within_days(14))), money_basis(revised_2026, yes, offered(refused), 'revised PTD: vouchers')]).
step(settle(revised_2026, yes, 1200, 12, offered(refused), refund(1200, within_days(14))), fact(46), [=('__anon35', revised_2026), =('P', 1200), =('__anon36', 12)], []).
step(money_basis(revised_2026, yes, offered(refused), 'revised PTD: vouchers'), fact(53), [=('__anon42', refused)], []).
step(assessment(revised_2026, c6, voucher(value(1600), valid_months(12), unused_value_refunded), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])), rule(55), [=('R', revised_2026), =('C', c6), =('Outcome', voucher(value(1600), valid_months(12), unused_value_refunded)), =('Free', 'revised PTD: destination'), =('Money', 'revised PTD: vouchers'), =('B', bk6), =('__anon43', by(farid)), =('D', 12), =('What', at(destination, hurricane)), =('V', offered(accepted)), =('__anon44', lead(farid)), =('P', 1600), =('F', yes)], [regime(revised_2026), policy_result(c6, permit), request(c6, bk6, by(farid), days(12), circumstances(at(destination, hurricane)), voucher(offered(accepted))), booking(bk6, lead(farid), price(1600)), free_cancellation(revised_2026, at(destination, hurricane), yes, 'revised PTD: destination'), settle(revised_2026, yes, 1600, 12, offered(accepted), voucher(value(1600), valid_months(12), unused_value_refunded)), money_basis(revised_2026, yes, offered(accepted), 'revised PTD: vouchers')]).
step(settle(revised_2026, yes, 1600, 12, offered(accepted), voucher(value(1600), valid_months(12), unused_value_refunded)), fact(48), [=('P', 1600), =('__anon38', 12)], []).
step(money_basis(revised_2026, yes, offered(accepted), 'revised PTD: vouchers'), fact(53), [=('__anon42', accepted)], []).
step(complaint_plan(directive_2015, k1, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), rule(58), [=('K', k1), =('__anon45', 'pool closed for the whole stay')], [complaint(k1, 'pool closed for the whole stay')]).
step(complaint(k1, 'pool closed for the whole stay'), fact(56), [], []).
step(complaint_plan(directive_2015, k2, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), rule(58), [=('K', k2), =('__anon45', 'refund not received')], [complaint(k2, 'refund not received')]).
step(complaint(k2, 'refund not received'), fact(57), [], []).
step(complaint_plan(revised_2026, k1, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), rule(59), [=('K', k1), =('__anon46', 'pool closed for the whole stay')], [complaint(k1, 'pool closed for the whole stay')]).
step(complaint_plan(revised_2026, k2, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), rule(59), [=('K', k2), =('__anon46', 'refund not received')], [complaint(k2, 'refund not received')]).
step(changed(cancellation(c4), from(pay_fee(percent(100), fee(2100), refund(0), within_days(14))), to(refund(2100, within_days(14)))), rule(60), [=('C', c4), =('Old', pay_fee(percent(100), fee(2100), refund(0), within_days(14))), =('New', refund(2100, within_days(14))), =('__anon47', basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), =('__anon48', basis(['ex:terms', 'revised PTD: point of departure', 'PTD Art. 12(4)']))], [assessment(directive_2015, c4, pay_fee(percent(100), fee(2100), refund(0), within_days(14)), basis(['ex:terms', 'PTD Art. 12(1)', 'PTD Art. 12(4)'])), assessment(revised_2026, c4, refund(2100, within_days(14)), basis(['ex:terms', 'revised PTD: point of departure', 'PTD Art. 12(4)'])), \==(pay_fee(percent(100), fee(2100), refund(0), within_days(14)), refund(2100, within_days(14)))]).
step(\==(pay_fee(percent(100), fee(2100), refund(0), within_days(14)), refund(2100, within_days(14))), builtin, [], []).
step(changed(cancellation(c6), from(voucher(value(1600), terms(as_agreed))), to(voucher(value(1600), valid_months(12), unused_value_refunded))), rule(60), [=('C', c6), =('Old', voucher(value(1600), terms(as_agreed))), =('New', voucher(value(1600), valid_months(12), unused_value_refunded)), =('__anon47', basis(['ex:terms', 'PTD Art. 12(2)', 'PTD 2015: no voucher rules'])), =('__anon48', basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers']))], [assessment(directive_2015, c6, voucher(value(1600), terms(as_agreed)), basis(['ex:terms', 'PTD Art. 12(2)', 'PTD 2015: no voucher rules'])), assessment(revised_2026, c6, voucher(value(1600), valid_months(12), unused_value_refunded), basis(['ex:terms', 'revised PTD: destination', 'revised PTD: vouchers'])), \==(voucher(value(1600), terms(as_agreed)), voucher(value(1600), valid_months(12), unused_value_refunded))]).
step(\==(voucher(value(1600), terms(as_agreed)), voucher(value(1600), valid_months(12), unused_value_refunded)), builtin, [], []).
step(changed(complaint(k1), from(deadlines(set_by_national_law)), to(deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))), rule(61), [=('K', k1), =('Old', deadlines(set_by_national_law)), =('New', deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60)))), =('__anon49', basis(['PTD 2015: no complaint deadlines'])), =('__anon50', basis(['revised PTD: complaints']))], [complaint_plan(directive_2015, k1, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), complaint_plan(revised_2026, k1, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), \==(deadlines(set_by_national_law), deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))]).
step(\==(deadlines(set_by_national_law), deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60)))), builtin, [], []).
step(changed(complaint(k2), from(deadlines(set_by_national_law)), to(deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))), rule(61), [=('K', k2), =('Old', deadlines(set_by_national_law)), =('New', deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60)))), =('__anon49', basis(['PTD 2015: no complaint deadlines'])), =('__anon50', basis(['revised PTD: complaints']))], [complaint_plan(directive_2015, k2, deadlines(set_by_national_law), basis(['PTD 2015: no complaint deadlines'])), complaint_plan(revised_2026, k2, deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))), basis(['revised PTD: complaints'])), \==(deadlines(set_by_national_law), deadlines(acknowledge(within_days(7)), reasoned_reply(within_days(60))))]).
