breach_plan(in_force, b1, notify(authority(none), people(none)), document_breach, basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])).
breach_plan(in_force, b2, notify(authority(within_hours(72)), people(none)), document_breach, basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])).
breach_plan(in_force, b3, notify(authority(within_hours(72)), people(without_undue_delay)), document_breach, basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])).
breach_plan(omnibus_proposal, b1, notify(authority(none), people(none)), document_breach, basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])).
breach_plan(omnibus_proposal, b2, notify(authority(none), people(none)), document_breach, basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])).
breach_plan(omnibus_proposal, b3, notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)), document_breach, basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])).
changed(breach(b2), from(notify(authority(within_hours(72)), people(none))), to(notify(authority(none), people(none)))).
changed(breach(b3), from(notify(authority(within_hours(72)), people(without_undue_delay))), to(notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)))).
policy_conflict('ex:r6', resolved_by('odrl:prohibit', 'ex:noTransferUS', overrides('ex:research'))).
assessment(in_force, 'ex:r2', deny_policy(not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])), basis(['ex:policy'])).
assessment(in_force, 'ex:r3', deny_policy(prohibited_by('ex:noMarketing')), basis(['ex:policy'])).
assessment(in_force, 'ex:r4', deny_policy(not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])), basis(['ex:policy'])).
assessment(in_force, 'ex:r5', deny_policy(not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])), basis(['ex:policy'])).
assessment(in_force, 'ex:r6', deny_policy(prohibited_by('ex:noTransferUS')), basis(['ex:policy'])).
assessment(omnibus_proposal, 'ex:r2', deny_policy(not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])), basis(['ex:policy'])).
assessment(omnibus_proposal, 'ex:r3', deny_policy(prohibited_by('ex:noMarketing')), basis(['ex:policy'])).
assessment(omnibus_proposal, 'ex:r4', deny_policy(not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])), basis(['ex:policy'])).
assessment(omnibus_proposal, 'ex:r5', deny_policy(not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])), basis(['ex:policy'])).
assessment(omnibus_proposal, 'ex:r6', deny_policy(prohibited_by('ex:noTransferUS')), basis(['ex:policy'])).
assessment(in_force, 'ex:r10', permit('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])).
assessment(omnibus_proposal, 'ex:r1', permit('ex:research'), basis(['ex:policy', 'GDPR Art. 88a(3)(c)'])).
assessment(omnibus_proposal, 'ex:r10', permit('ex:research'), basis(['ex:policy', 'GDPR Art. 88a(3)(b)'])).
assessment(in_force, 'ex:r1', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])).
assessment(in_force, 'ex:r7', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])).
assessment(in_force, 'ex:r8', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])).
assessment(in_force, 'ex:r9', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])).
assessment(omnibus_proposal, 'ex:r9', await_device_consent('ex:research'), basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])).
assessment(omnibus_proposal, 'ex:r7', deny_device(refused_by_signal), basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])).
assessment(omnibus_proposal, 'ex:r8', deny_device(do_not_ask_again), basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])).
planned_duty(in_force, 'ex:r10', 'odrl:delete', within_days(90)).
planned_duty(omnibus_proposal, 'ex:r1', 'odrl:delete', within_days(90)).
planned_duty(omnibus_proposal, 'ex:r10', 'odrl:delete', within_days(90)).
changed(session('ex:r1'), from(await_device_consent('ex:research')), to(permit('ex:research'))).
changed(session('ex:r7'), from(await_device_consent('ex:research')), to(deny_device(refused_by_signal))).
changed(session('ex:r8'), from(await_device_consent('ex:research')), to(deny_device(do_not_ask_again))).

clause(5, t('ex:partnerBE', 'odrl:partOf', 'ex:consortium'), true).
clause(6, t('ex:partnerUS', 'odrl:partOf', 'ex:consortium'), true).
clause(11, t('ex:policy', 'odrl:permission', 'ex:research'), true).
clause(12, t('ex:research', 'odrl:assignee', 'ex:consortium'), true).
clause(13, t('ex:research', 'odrl:action', 'odrl:use'), true).
clause(14, t('ex:research', 'odrl:target', 'ex:labResults'), true).
clause(20, t('ex:research', 'odrl:duty', 'ex:deletion'), true).
clause(21, t('ex:deletion', 'odrl:action', 'odrl:delete'), true).
clause(22, t('ex:deletion', 'ex:withinDays', 90), true).
clause(23, t('ex:policy', 'odrl:prohibition', 'ex:noMarketing'), true).
clause(24, t('ex:noMarketing', 'odrl:assignee', 'ex:consortium'), true).
clause(25, t('ex:noMarketing', 'odrl:action', 'odrl:distribute'), true).
clause(26, t('ex:noMarketing', 'odrl:target', 'ex:labResults'), true).
clause(28, t('ex:policy', 'odrl:prohibition', 'ex:noTransferUS'), true).
clause(29, t('ex:noTransferUS', 'odrl:assignee', 'ex:partnerUS'), true).
clause(30, t('ex:noTransferUS', 'odrl:action', 'odrl:use'), true).
clause(31, t('ex:noTransferUS', 'odrl:target', 'ex:labResults'), true).
clause(38, process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(39, process('ex:r2', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:PersonalisedAdvertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(40, process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(41, process('ex:r4', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:CommercialResearch', 'dpv:ConsentWithdrawn', 'dpv:Pseudonymisation', 20261115), true).
clause(42, process('ex:r5', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Encryption', 20270301), true).
clause(43, process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(44, process('ex:r7', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(45, process('ex:r8', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(46, process('ex:r9', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(47, process('ex:r10', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), true).
clause(48, t(var('P'), 'rdf:type', 'dpv:Process'), process(var('P'), var('__anon0'), var('__anon1'), var('__anon2'), var('__anon3'), var('__anon4'), var('__anon5'), var('__anon6'))).
clause(49, t(var('P'), 'ex:requestedBy', var('Who')), process(var('P'), var('Who'), var('__anon7'), var('__anon8'), var('__anon9'), var('__anon10'), var('__anon11'), var('__anon12'))).
clause(50, t(var('P'), 'dpv:hasProcessing', var('X')), process(var('P'), var('__anon13'), var('X'), var('__anon14'), var('__anon15'), var('__anon16'), var('__anon17'), var('__anon18'))).
clause(51, t(var('P'), 'dpv:hasPersonalData', var('X')), process(var('P'), var('__anon19'), var('__anon20'), var('X'), var('__anon21'), var('__anon22'), var('__anon23'), var('__anon24'))).
clause(57, action('dpv:Use', 'odrl:use'), true).
clause(58, action('dpv:Share', 'odrl:distribute'), true).
clause(69, party(var('Who'), var('Who')), true).
clause(70, party(var('Who'), var('Group')), t(var('Who'), 'odrl:partOf', var('Group'))).
clause(71, addresses(var('P'), var('Rule')), ','(t(var('P'), 'ex:requestedBy', var('Who')), ','(t(var('Rule'), 'odrl:assignee', var('Assignee')), ','(party(var('Who'), var('Assignee')), ','(t(var('P'), 'dpv:hasProcessing', var('Processing')), ','(action(var('Processing'), var('Action')), ','(t(var('Rule'), 'odrl:action', var('Action')), ','(t(var('P'), 'dpv:hasPersonalData', var('Data')), t(var('Rule'), 'odrl:target', var('Data')))))))))).
clause(76, applies(var('P'), var('Rule')), ','(addresses(var('P'), var('Rule')), findall(var('Why'), unmet(var('P'), var('Rule'), var('Why')), []))).
clause(77, permitted(var('P'), var('Rule')), ','(t('ex:policy', 'odrl:permission', var('Rule')), applies(var('P'), var('Rule')))).
clause(78, prohibited(var('P'), var('Rule')), ','(t('ex:policy', 'odrl:prohibition', var('Rule')), applies(var('P'), var('Rule')))).
clause(79, candidate(var('P'), var('Rule')), ','(t('ex:policy', 'odrl:permission', var('Rule')), addresses(var('P'), var('Rule')))).
clause(80, policy_ready, findall(var('S'), t('ex:policy', 'odrl:conflict', var('S')), ['odrl:prohibit'])).
clause(81, policy_result(var('P'), permit(var('Rule'))), ','(policy_ready, ','(permitted(var('P'), var('Rule')), findall(var('R'), prohibited(var('P'), var('R')), [])))).
clause(82, policy_result(var('P'), deny(prohibited_by(var('Rule')))), ','(policy_ready, prohibited(var('P'), var('Rule')))).
clause(83, policy_result(var('P'), deny(not_permitted(var('Reasons')))), ','(policy_ready, ','(t(var('P'), 'rdf:type', 'dpv:Process'), ','(candidate(var('P'), var('__anon56')), ','(findall(var('R'), permitted(var('P'), var('R')), []), ','(findall(var('R'), prohibited(var('P'), var('R')), []), findall(var('Why'), ','(t('ex:policy', 'odrl:permission', var('Rule')), unmet(var('P'), var('Rule'), var('Why'))), var('Reasons')))))))).
clause(86, session('ex:r1', own_audience_measurement, first_visit), true).
clause(87, session('ex:r2', own_audience_measurement, first_visit), true).
clause(88, session('ex:r3', advertising, browser_signal(refuse)), true).
clause(89, session('ex:r4', own_audience_measurement, first_visit), true).
clause(90, session('ex:r5', requested_service, first_visit), true).
clause(91, session('ex:r6', own_audience_measurement, first_visit), true).
clause(92, session('ex:r7', advertising, browser_signal(refuse)), true).
clause(93, session('ex:r8', advertising, refused(completed_months(5))), true).
clause(94, session('ex:r9', advertising, refused(completed_months(6))), true).
clause(95, session('ex:r10', requested_service, first_visit), true).
clause(96, regime(in_force), true).
clause(97, regime(omnibus_proposal), true).
clause(98, refusal_pause(months(6)), true).
clause(101, consent(in_force, requested_service, not_needed, 'ePrivacy Art. 5(3)'), true).
clause(102, consent(in_force, own_audience_measurement, needed, 'ePrivacy Art. 5(3)'), true).
clause(104, consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), true).
clause(107, consent(omnibus_proposal, requested_service, not_needed, 'GDPR Art. 88a(3)(b)'), true).
clause(108, consent(omnibus_proposal, own_audience_measurement, not_needed, 'GDPR Art. 88a(3)(c)'), true).
clause(110, consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), true).
clause(111, ask(in_force, var('__anon57'), var('__anon58'), ask_for_consent, 'ePrivacy Art. 5(3)'), true).
clause(113, ask(omnibus_proposal, media_service(no), browser_signal(refuse), refused_by_signal, 'GDPR Art. 88b(1)-(2)'), true).
clause(115, ask(omnibus_proposal, var('__anon60'), refused(completed_months(var('M'))), do_not_ask_again, 'GDPR Art. 88a(4)(c)'), ','(integer(var('M')), ','(>=(var('M'), 0), ','(refusal_pause(months(var('Min'))), <(var('M'), var('Min')))))).
clause(116, ask(omnibus_proposal, var('__anon61'), refused(completed_months(var('M'))), ask_for_consent, 'GDPR Art. 88a(4)(c)'), ','(integer(var('M')), ','(>=(var('M'), 0), ','(refusal_pause(months(var('Min'))), >=(var('M'), var('Min')))))).
clause(117, authority(in_force, risk(unlikely), none, 'GDPR Art. 33(1)'), true).
clause(118, authority(in_force, risk(some), within_hours(72), 'GDPR Art. 33(1)'), true).
clause(119, authority(in_force, risk(high), within_hours(72), 'GDPR Art. 33(1)'), true).
clause(120, authority(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 33(1) as amended'), true).
clause(121, authority(omnibus_proposal, risk(some), none, 'GDPR Art. 33(1) as amended'), true).
clause(122, authority(omnibus_proposal, risk(high), within_hours_via_single_entry_point(96), 'GDPR Art. 33(1) as amended'), true).
clause(123, people(var('__anon62'), risk(unlikely), none, 'GDPR Art. 34(1)'), true).
clause(124, people(var('__anon63'), risk(some), none, 'GDPR Art. 34(1)'), true).
clause(125, people(var('__anon64'), risk(high), without_undue_delay, 'GDPR Art. 34(1)'), true).
clause(126, assessment(var('R'), var('P'), deny_policy(var('Reason')), basis(['ex:policy'])), ','(regime(var('R')), ','(session(var('P'), var('__anon65'), var('__anon66')), policy_result(var('P'), deny(var('Reason')))))).
clause(127, assessment(var('R'), var('P'), permit(var('Rule')), basis(['ex:policy', var('Provision')])), ','(regime(var('R')), ','(policy_result(var('P'), permit(var('Rule'))), ','(session(var('P'), var('Kind'), var('__anon67')), consent(var('R'), var('Kind'), not_needed, var('Provision')))))).
clause(128, assessment(var('R'), var('P'), await_device_consent(var('Rule')), basis(var('Basis'))), ','(regime(var('R')), ','(policy_result(var('P'), permit(var('Rule'))), ','(session(var('P'), var('Kind'), var('Before')), ','(consent(var('R'), var('Kind'), needed, var('Provision')), ','(ask(var('R'), media_service(no), var('Before'), ask_for_consent, var('Next')), device_basis(var('Provision'), var('Next'), var('Basis')))))))).
clause(129, assessment(var('R'), var('P'), deny_device(var('Reason')), basis(var('Basis'))), ','(regime(var('R')), ','(policy_result(var('P'), permit(var('__anon68'))), ','(session(var('P'), var('Kind'), var('Before')), ','(consent(var('R'), var('Kind'), needed, var('Provision')), ','(ask(var('R'), media_service(no), var('Before'), var('Reason'), var('Next')), ','(\==(var('Reason'), ask_for_consent), device_basis(var('Provision'), var('Next'), var('Basis'))))))))).
clause(130, device_basis(var('P'), var('P'), ['ex:policy', var('P')]), true).
clause(131, device_basis(var('P'), var('Q'), ['ex:policy', var('P'), var('Q')]), \==(var('P'), var('Q'))).
clause(132, policy_conflict(var('P'), resolved_by('odrl:prohibit', var('Prohibition'), overrides(var('Permission')))), ','(policy_ready, ','(session(var('P'), var('__anon69'), var('__anon70')), ','(permitted(var('P'), var('Permission')), prohibited(var('P'), var('Prohibition')))))).
clause(133, planned_duty(var('R'), var('P'), var('Action'), within_days(var('Days'))), ','(assessment(var('R'), var('P'), permit(var('Rule')), var('__anon71')), ','(t(var('Rule'), 'odrl:duty', var('Duty')), ','(t(var('Duty'), 'odrl:action', var('Action')), t(var('Duty'), 'ex:withinDays', var('Days')))))).
clause(134, breach(b1, 'encrypted laptop lost, key safe', risk(unlikely)), true).
clause(135, breach(b2, 'researcher contact addresses exposed', risk(some)), true).
clause(136, breach(b3, 'patient lab records exposed', risk(high)), true).
clause(137, breach_plan(var('R'), var('B'), notify(authority(var('When')), people(var('How'))), document_breach, basis([var('P'), var('Q'), 'GDPR Art. 33(5)'])), ','(regime(var('R')), ','(breach(var('B'), var('__anon72'), var('Risk')), ','(authority(var('R'), var('Risk'), var('When'), var('P')), people(var('R'), var('Risk'), var('How'), var('Q')))))).
clause(138, changed(session(var('P')), from(var('Old')), to(var('New'))), ','(assessment(in_force, var('P'), var('Old'), var('__anon73')), ','(assessment(omnibus_proposal, var('P'), var('New'), var('__anon74')), \==(var('Old'), var('New'))))).
clause(139, changed(breach(var('B')), from(var('Old')), to(var('New'))), ','(breach_plan(in_force, var('B'), var('Old'), var('__anon75'), var('__anon76')), ','(breach_plan(omnibus_proposal, var('B'), var('New'), var('__anon77'), var('__anon78')), \==(var('Old'), var('New'))))).

step(breach_plan(in_force, b1, notify(authority(none), people(none)), document_breach, basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), rule(137), [=('R', in_force), =('B', b1), =('When', none), =('How', none), =('P', 'GDPR Art. 33(1)'), =('Q', 'GDPR Art. 34(1)'), =('__anon72', 'encrypted laptop lost, key safe'), =('Risk', risk(unlikely))], [regime(in_force), breach(b1, 'encrypted laptop lost, key safe', risk(unlikely)), authority(in_force, risk(unlikely), none, 'GDPR Art. 33(1)'), people(in_force, risk(unlikely), none, 'GDPR Art. 34(1)')]).
step(regime(in_force), fact(96), [], []).
step(breach(b1, 'encrypted laptop lost, key safe', risk(unlikely)), fact(134), [], []).
step(authority(in_force, risk(unlikely), none, 'GDPR Art. 33(1)'), fact(117), [], []).
step(people(in_force, risk(unlikely), none, 'GDPR Art. 34(1)'), fact(123), [=('__anon62', in_force)], []).
step(breach_plan(in_force, b2, notify(authority(within_hours(72)), people(none)), document_breach, basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), rule(137), [=('R', in_force), =('B', b2), =('When', within_hours(72)), =('How', none), =('P', 'GDPR Art. 33(1)'), =('Q', 'GDPR Art. 34(1)'), =('__anon72', 'researcher contact addresses exposed'), =('Risk', risk(some))], [regime(in_force), breach(b2, 'researcher contact addresses exposed', risk(some)), authority(in_force, risk(some), within_hours(72), 'GDPR Art. 33(1)'), people(in_force, risk(some), none, 'GDPR Art. 34(1)')]).
step(breach(b2, 'researcher contact addresses exposed', risk(some)), fact(135), [], []).
step(authority(in_force, risk(some), within_hours(72), 'GDPR Art. 33(1)'), fact(118), [], []).
step(people(in_force, risk(some), none, 'GDPR Art. 34(1)'), fact(124), [=('__anon63', in_force)], []).
step(breach_plan(in_force, b3, notify(authority(within_hours(72)), people(without_undue_delay)), document_breach, basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), rule(137), [=('R', in_force), =('B', b3), =('When', within_hours(72)), =('How', without_undue_delay), =('P', 'GDPR Art. 33(1)'), =('Q', 'GDPR Art. 34(1)'), =('__anon72', 'patient lab records exposed'), =('Risk', risk(high))], [regime(in_force), breach(b3, 'patient lab records exposed', risk(high)), authority(in_force, risk(high), within_hours(72), 'GDPR Art. 33(1)'), people(in_force, risk(high), without_undue_delay, 'GDPR Art. 34(1)')]).
step(breach(b3, 'patient lab records exposed', risk(high)), fact(136), [], []).
step(authority(in_force, risk(high), within_hours(72), 'GDPR Art. 33(1)'), fact(119), [], []).
step(people(in_force, risk(high), without_undue_delay, 'GDPR Art. 34(1)'), fact(125), [=('__anon64', in_force)], []).
step(breach_plan(omnibus_proposal, b1, notify(authority(none), people(none)), document_breach, basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), rule(137), [=('R', omnibus_proposal), =('B', b1), =('When', none), =('How', none), =('P', 'GDPR Art. 33(1) as amended'), =('Q', 'GDPR Art. 34(1)'), =('__anon72', 'encrypted laptop lost, key safe'), =('Risk', risk(unlikely))], [regime(omnibus_proposal), breach(b1, 'encrypted laptop lost, key safe', risk(unlikely)), authority(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 33(1) as amended'), people(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 34(1)')]).
step(regime(omnibus_proposal), fact(97), [], []).
step(authority(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 33(1) as amended'), fact(120), [], []).
step(people(omnibus_proposal, risk(unlikely), none, 'GDPR Art. 34(1)'), fact(123), [=('__anon62', omnibus_proposal)], []).
step(breach_plan(omnibus_proposal, b2, notify(authority(none), people(none)), document_breach, basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), rule(137), [=('R', omnibus_proposal), =('B', b2), =('When', none), =('How', none), =('P', 'GDPR Art. 33(1) as amended'), =('Q', 'GDPR Art. 34(1)'), =('__anon72', 'researcher contact addresses exposed'), =('Risk', risk(some))], [regime(omnibus_proposal), breach(b2, 'researcher contact addresses exposed', risk(some)), authority(omnibus_proposal, risk(some), none, 'GDPR Art. 33(1) as amended'), people(omnibus_proposal, risk(some), none, 'GDPR Art. 34(1)')]).
step(authority(omnibus_proposal, risk(some), none, 'GDPR Art. 33(1) as amended'), fact(121), [], []).
step(people(omnibus_proposal, risk(some), none, 'GDPR Art. 34(1)'), fact(124), [=('__anon63', omnibus_proposal)], []).
step(breach_plan(omnibus_proposal, b3, notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)), document_breach, basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), rule(137), [=('R', omnibus_proposal), =('B', b3), =('When', within_hours_via_single_entry_point(96)), =('How', without_undue_delay), =('P', 'GDPR Art. 33(1) as amended'), =('Q', 'GDPR Art. 34(1)'), =('__anon72', 'patient lab records exposed'), =('Risk', risk(high))], [regime(omnibus_proposal), breach(b3, 'patient lab records exposed', risk(high)), authority(omnibus_proposal, risk(high), within_hours_via_single_entry_point(96), 'GDPR Art. 33(1) as amended'), people(omnibus_proposal, risk(high), without_undue_delay, 'GDPR Art. 34(1)')]).
step(authority(omnibus_proposal, risk(high), within_hours_via_single_entry_point(96), 'GDPR Art. 33(1) as amended'), fact(122), [], []).
step(people(omnibus_proposal, risk(high), without_undue_delay, 'GDPR Art. 34(1)'), fact(125), [=('__anon64', omnibus_proposal)], []).
step(changed(breach(b2), from(notify(authority(within_hours(72)), people(none))), to(notify(authority(none), people(none)))), rule(139), [=('B', b2), =('Old', notify(authority(within_hours(72)), people(none))), =('New', notify(authority(none), people(none))), =('__anon75', document_breach), =('__anon76', basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), =('__anon77', document_breach), =('__anon78', basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)']))], [breach_plan(in_force, b2, notify(authority(within_hours(72)), people(none)), document_breach, basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), breach_plan(omnibus_proposal, b2, notify(authority(none), people(none)), document_breach, basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), \==(notify(authority(within_hours(72)), people(none)), notify(authority(none), people(none)))]).
step(\==(notify(authority(within_hours(72)), people(none)), notify(authority(none), people(none))), builtin, [], []).
step(changed(breach(b3), from(notify(authority(within_hours(72)), people(without_undue_delay))), to(notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)))), rule(139), [=('B', b3), =('Old', notify(authority(within_hours(72)), people(without_undue_delay))), =('New', notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay))), =('__anon75', document_breach), =('__anon76', basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), =('__anon77', document_breach), =('__anon78', basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)']))], [breach_plan(in_force, b3, notify(authority(within_hours(72)), people(without_undue_delay)), document_breach, basis(['GDPR Art. 33(1)', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), breach_plan(omnibus_proposal, b3, notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)), document_breach, basis(['GDPR Art. 33(1) as amended', 'GDPR Art. 34(1)', 'GDPR Art. 33(5)'])), \==(notify(authority(within_hours(72)), people(without_undue_delay)), notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay)))]).
step(\==(notify(authority(within_hours(72)), people(without_undue_delay)), notify(authority(within_hours_via_single_entry_point(96)), people(without_undue_delay))), builtin, [], []).
step(policy_conflict('ex:r6', resolved_by('odrl:prohibit', 'ex:noTransferUS', overrides('ex:research'))), rule(132), [=('P', 'ex:r6'), =('Prohibition', 'ex:noTransferUS'), =('Permission', 'ex:research'), =('__anon69', own_audience_measurement), =('__anon70', first_visit)], [policy_ready, session('ex:r6', own_audience_measurement, first_visit), permitted('ex:r6', 'ex:research'), prohibited('ex:r6', 'ex:noTransferUS')]).
step(policy_ready, rule(80), [=('S', EYE_53_23_39_34)], [findall(EYE_53_23_39_34, t('ex:policy', 'odrl:conflict', EYE_53_23_39_34), ['odrl:prohibit'])]).
step(findall(EYE_53_23_39_34, t('ex:policy', 'odrl:conflict', EYE_53_23_39_34), ['odrl:prohibit']), collected, [], []).
step(session('ex:r6', own_audience_measurement, first_visit), fact(91), [], []).
step(permitted('ex:r6', 'ex:research'), rule(77), [=('P', 'ex:r6'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), applies('ex:r6', 'ex:research')]).
step(t('ex:policy', 'odrl:permission', 'ex:research'), fact(11), [], []).
step(applies('ex:r6', 'ex:research'), rule(76), [=('P', 'ex:r6'), =('Rule', 'ex:research'), =('Why', EYE_57_68_79_23_39_38_30)], [addresses('ex:r6', 'ex:research'), findall(EYE_57_68_79_23_39_38_30, unmet('ex:r6', 'ex:research', EYE_57_68_79_23_39_38_30), [])]).
step(addresses('ex:r6', 'ex:research'), rule(71), [=('P', 'ex:r6'), =('Rule', 'ex:research'), =('Who', 'ex:partnerUS'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r6', 'ex:requestedBy', 'ex:partnerUS'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerUS', 'ex:consortium'), t('ex:r6', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r6', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r6', 'ex:requestedBy', 'ex:partnerUS'), rule(49), [=('P', 'ex:r6'), =('Who', 'ex:partnerUS'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:AcademicResearch'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(43), [], []).
step(t('ex:research', 'odrl:assignee', 'ex:consortium'), fact(12), [], []).
step(party('ex:partnerUS', 'ex:consortium'), rule(70), [=('Who', 'ex:partnerUS'), =('Group', 'ex:consortium')], [t('ex:partnerUS', 'odrl:partOf', 'ex:consortium')]).
step(t('ex:partnerUS', 'odrl:partOf', 'ex:consortium'), fact(6), [], []).
step(t('ex:r6', 'dpv:hasProcessing', 'dpv:Use'), rule(50), [=('P', 'ex:r6'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerUS'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:AcademicResearch'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(action('dpv:Use', 'odrl:use'), fact(57), [], []).
step(t('ex:research', 'odrl:action', 'odrl:use'), fact(13), [], []).
step(t('ex:r6', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r6'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerUS'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:AcademicResearch'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r6', 'ex:partnerUS', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:research', 'odrl:target', 'ex:labResults'), fact(14), [], []).
step(findall(EYE_57_68_79_23_39_38_30, unmet('ex:r6', 'ex:research', EYE_57_68_79_23_39_38_30), []), collected, [], []).
step(prohibited('ex:r6', 'ex:noTransferUS'), rule(78), [=('P', 'ex:r6'), =('Rule', 'ex:noTransferUS')], [t('ex:policy', 'odrl:prohibition', 'ex:noTransferUS'), applies('ex:r6', 'ex:noTransferUS')]).
step(t('ex:policy', 'odrl:prohibition', 'ex:noTransferUS'), fact(28), [], []).
step(applies('ex:r6', 'ex:noTransferUS'), rule(76), [=('P', 'ex:r6'), =('Rule', 'ex:noTransferUS'), =('Why', EYE_57_68_79_23_31_31_39_33)], [addresses('ex:r6', 'ex:noTransferUS'), findall(EYE_57_68_79_23_31_31_39_33, unmet('ex:r6', 'ex:noTransferUS', EYE_57_68_79_23_31_31_39_33), [])]).
step(addresses('ex:r6', 'ex:noTransferUS'), rule(71), [=('P', 'ex:r6'), =('Rule', 'ex:noTransferUS'), =('Who', 'ex:partnerUS'), =('Assignee', 'ex:partnerUS'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r6', 'ex:requestedBy', 'ex:partnerUS'), t('ex:noTransferUS', 'odrl:assignee', 'ex:partnerUS'), party('ex:partnerUS', 'ex:partnerUS'), t('ex:r6', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:noTransferUS', 'odrl:action', 'odrl:use'), t('ex:r6', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:noTransferUS', 'odrl:target', 'ex:labResults')]).
step(t('ex:noTransferUS', 'odrl:assignee', 'ex:partnerUS'), fact(29), [], []).
step(party('ex:partnerUS', 'ex:partnerUS'), fact(69), [=('Who', 'ex:partnerUS')], []).
step(t('ex:noTransferUS', 'odrl:action', 'odrl:use'), fact(30), [], []).
step(t('ex:noTransferUS', 'odrl:target', 'ex:labResults'), fact(31), [], []).
step(findall(EYE_57_68_79_23_31_31_39_33, unmet('ex:r6', 'ex:noTransferUS', EYE_57_68_79_23_31_31_39_33), []), collected, [], []).
step(assessment(in_force, 'ex:r2', deny_policy(not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])), basis(['ex:policy'])), rule(126), [=('R', in_force), =('P', 'ex:r2'), =('Reason', not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])), =('__anon65', own_audience_measurement), =('__anon66', first_visit)], [regime(in_force), session('ex:r2', own_audience_measurement, first_visit), policy_result('ex:r2', deny(not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])))]).
step(session('ex:r2', own_audience_measurement, first_visit), fact(87), [], []).
step(policy_result('ex:r2', deny(not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')]))), rule(83), [=('P', 'ex:r2'), =('Reasons', [unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')]), =('__anon56', 'ex:research'), =('R', EYE_52_23_34_37_35_31), =('Why', EYE_57_68_79_23_34_37_35_31), =('Rule', EYE_52_75_6c_65_23_34_37_35_31)], [policy_ready, t('ex:r2', 'rdf:type', 'dpv:Process'), candidate('ex:r2', 'ex:research'), findall(EYE_52_23_34_37_35_31, permitted('ex:r2', EYE_52_23_34_37_35_31), []), findall(EYE_52_23_34_37_35_31, prohibited('ex:r2', EYE_52_23_34_37_35_31), []), findall(EYE_57_68_79_23_34_37_35_31, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_34_37_35_31), unmet('ex:r2', EYE_52_75_6c_65_23_34_37_35_31, EYE_57_68_79_23_34_37_35_31)), [unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])]).
step(t('ex:r2', 'rdf:type', 'dpv:Process'), rule(48), [=('P', 'ex:r2'), =('__anon0', 'ex:partnerBE'), =('__anon1', 'dpv:Use'), =('__anon2', 'ex:labResults'), =('__anon3', 'dpv:PersonalisedAdvertising'), =('__anon4', 'dpv:ConsentGiven'), =('__anon5', 'dpv:Pseudonymisation'), =('__anon6', 20261115)], [process('ex:r2', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:PersonalisedAdvertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r2', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:PersonalisedAdvertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(39), [], []).
step(candidate('ex:r2', 'ex:research'), rule(79), [=('P', 'ex:r2'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), addresses('ex:r2', 'ex:research')]).
step(addresses('ex:r2', 'ex:research'), rule(71), [=('P', 'ex:r2'), =('Rule', 'ex:research'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r2', 'ex:requestedBy', 'ex:partnerBE'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r2', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r2', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r2', 'ex:requestedBy', 'ex:partnerBE'), rule(49), [=('P', 'ex:r2'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:PersonalisedAdvertising'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r2', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:PersonalisedAdvertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(party('ex:partnerBE', 'ex:consortium'), rule(70), [=('Who', 'ex:partnerBE'), =('Group', 'ex:consortium')], [t('ex:partnerBE', 'odrl:partOf', 'ex:consortium')]).
step(t('ex:partnerBE', 'odrl:partOf', 'ex:consortium'), fact(5), [], []).
step(t('ex:r2', 'dpv:hasProcessing', 'dpv:Use'), rule(50), [=('P', 'ex:r2'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:PersonalisedAdvertising'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r2', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:PersonalisedAdvertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r2', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r2'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:PersonalisedAdvertising'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r2', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:PersonalisedAdvertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(findall(EYE_52_23_34_37_35_31, permitted('ex:r2', EYE_52_23_34_37_35_31), []), collected, [], []).
step(findall(EYE_52_23_34_37_35_31, prohibited('ex:r2', EYE_52_23_34_37_35_31), []), collected, [], []).
step(findall(EYE_57_68_79_23_34_37_35_31, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_34_37_35_31), unmet('ex:r2', EYE_52_75_6c_65_23_34_37_35_31, EYE_57_68_79_23_34_37_35_31)), [unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')]), collected, [], []).
step(assessment(in_force, 'ex:r3', deny_policy(prohibited_by('ex:noMarketing')), basis(['ex:policy'])), rule(126), [=('R', in_force), =('P', 'ex:r3'), =('Reason', prohibited_by('ex:noMarketing')), =('__anon65', advertising), =('__anon66', browser_signal(refuse))], [regime(in_force), session('ex:r3', advertising, browser_signal(refuse)), policy_result('ex:r3', deny(prohibited_by('ex:noMarketing')))]).
step(session('ex:r3', advertising, browser_signal(refuse)), fact(88), [], []).
step(policy_result('ex:r3', deny(prohibited_by('ex:noMarketing'))), rule(82), [=('P', 'ex:r3'), =('Rule', 'ex:noMarketing')], [policy_ready, prohibited('ex:r3', 'ex:noMarketing')]).
step(prohibited('ex:r3', 'ex:noMarketing'), rule(78), [=('P', 'ex:r3'), =('Rule', 'ex:noMarketing')], [t('ex:policy', 'odrl:prohibition', 'ex:noMarketing'), applies('ex:r3', 'ex:noMarketing')]).
step(t('ex:policy', 'odrl:prohibition', 'ex:noMarketing'), fact(23), [], []).
step(applies('ex:r3', 'ex:noMarketing'), rule(76), [=('P', 'ex:r3'), =('Rule', 'ex:noMarketing'), =('Why', EYE_57_68_79_23_35_32_37_31)], [addresses('ex:r3', 'ex:noMarketing'), findall(EYE_57_68_79_23_35_32_37_31, unmet('ex:r3', 'ex:noMarketing', EYE_57_68_79_23_35_32_37_31), [])]).
step(addresses('ex:r3', 'ex:noMarketing'), rule(71), [=('P', 'ex:r3'), =('Rule', 'ex:noMarketing'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Share'), =('Action', 'odrl:distribute'), =('Data', 'ex:labResults')], [t('ex:r3', 'ex:requestedBy', 'ex:partnerBE'), t('ex:noMarketing', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r3', 'dpv:hasProcessing', 'dpv:Share'), action('dpv:Share', 'odrl:distribute'), t('ex:noMarketing', 'odrl:action', 'odrl:distribute'), t('ex:r3', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:noMarketing', 'odrl:target', 'ex:labResults')]).
step(t('ex:r3', 'ex:requestedBy', 'ex:partnerBE'), rule(49), [=('P', 'ex:r3'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Share'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:Advertising'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(40), [], []).
step(t('ex:noMarketing', 'odrl:assignee', 'ex:consortium'), fact(24), [], []).
step(t('ex:r3', 'dpv:hasProcessing', 'dpv:Share'), rule(50), [=('P', 'ex:r3'), =('X', 'dpv:Share'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:Advertising'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(action('dpv:Share', 'odrl:distribute'), fact(58), [], []).
step(t('ex:noMarketing', 'odrl:action', 'odrl:distribute'), fact(25), [], []).
step(t('ex:r3', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r3'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Share'), =('__anon21', 'dpv:Advertising'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r3', 'ex:partnerBE', 'dpv:Share', 'ex:labResults', 'dpv:Advertising', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:noMarketing', 'odrl:target', 'ex:labResults'), fact(26), [], []).
step(findall(EYE_57_68_79_23_35_32_37_31, unmet('ex:r3', 'ex:noMarketing', EYE_57_68_79_23_35_32_37_31), []), collected, [], []).
step(assessment(in_force, 'ex:r4', deny_policy(not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])), basis(['ex:policy'])), rule(126), [=('R', in_force), =('P', 'ex:r4'), =('Reason', not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])), =('__anon65', own_audience_measurement), =('__anon66', first_visit)], [regime(in_force), session('ex:r4', own_audience_measurement, first_visit), policy_result('ex:r4', deny(not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])))]).
step(session('ex:r4', own_audience_measurement, first_visit), fact(89), [], []).
step(policy_result('ex:r4', deny(not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')]))), rule(83), [=('P', 'ex:r4'), =('Reasons', [unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')]), =('__anon56', 'ex:research'), =('R', EYE_52_23_35_36_36_33), =('Why', EYE_57_68_79_23_35_36_36_33), =('Rule', EYE_52_75_6c_65_23_35_36_36_33)], [policy_ready, t('ex:r4', 'rdf:type', 'dpv:Process'), candidate('ex:r4', 'ex:research'), findall(EYE_52_23_35_36_36_33, permitted('ex:r4', EYE_52_23_35_36_36_33), []), findall(EYE_52_23_35_36_36_33, prohibited('ex:r4', EYE_52_23_35_36_36_33), []), findall(EYE_57_68_79_23_35_36_36_33, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_35_36_36_33), unmet('ex:r4', EYE_52_75_6c_65_23_35_36_36_33, EYE_57_68_79_23_35_36_36_33)), [unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])]).
step(t('ex:r4', 'rdf:type', 'dpv:Process'), rule(48), [=('P', 'ex:r4'), =('__anon0', 'ex:partnerBE'), =('__anon1', 'dpv:Use'), =('__anon2', 'ex:labResults'), =('__anon3', 'dpv:CommercialResearch'), =('__anon4', 'dpv:ConsentWithdrawn'), =('__anon5', 'dpv:Pseudonymisation'), =('__anon6', 20261115)], [process('ex:r4', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:CommercialResearch', 'dpv:ConsentWithdrawn', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r4', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:CommercialResearch', 'dpv:ConsentWithdrawn', 'dpv:Pseudonymisation', 20261115), fact(41), [], []).
step(candidate('ex:r4', 'ex:research'), rule(79), [=('P', 'ex:r4'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), addresses('ex:r4', 'ex:research')]).
step(addresses('ex:r4', 'ex:research'), rule(71), [=('P', 'ex:r4'), =('Rule', 'ex:research'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r4', 'ex:requestedBy', 'ex:partnerBE'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r4', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r4', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r4', 'ex:requestedBy', 'ex:partnerBE'), rule(49), [=('P', 'ex:r4'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:CommercialResearch'), =('__anon10', 'dpv:ConsentWithdrawn'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r4', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:CommercialResearch', 'dpv:ConsentWithdrawn', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r4', 'dpv:hasProcessing', 'dpv:Use'), rule(50), [=('P', 'ex:r4'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:CommercialResearch'), =('__anon16', 'dpv:ConsentWithdrawn'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r4', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:CommercialResearch', 'dpv:ConsentWithdrawn', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r4', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r4'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:CommercialResearch'), =('__anon22', 'dpv:ConsentWithdrawn'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r4', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:CommercialResearch', 'dpv:ConsentWithdrawn', 'dpv:Pseudonymisation', 20261115)]).
step(findall(EYE_52_23_35_36_36_33, permitted('ex:r4', EYE_52_23_35_36_36_33), []), collected, [], []).
step(findall(EYE_52_23_35_36_36_33, prohibited('ex:r4', EYE_52_23_35_36_36_33), []), collected, [], []).
step(findall(EYE_57_68_79_23_35_36_36_33, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_35_36_36_33), unmet('ex:r4', EYE_52_75_6c_65_23_35_36_36_33, EYE_57_68_79_23_35_36_36_33)), [unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')]), collected, [], []).
step(assessment(in_force, 'ex:r5', deny_policy(not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])), basis(['ex:policy'])), rule(126), [=('R', in_force), =('P', 'ex:r5'), =('Reason', not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])), =('__anon65', requested_service), =('__anon66', first_visit)], [regime(in_force), session('ex:r5', requested_service, first_visit), policy_result('ex:r5', deny(not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])))]).
step(session('ex:r5', requested_service, first_visit), fact(90), [], []).
step(policy_result('ex:r5', deny(not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)]))), rule(83), [=('P', 'ex:r5'), =('Reasons', [unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)]), =('__anon56', 'ex:research'), =('R', EYE_52_23_36_31_38_37), =('Why', EYE_57_68_79_23_36_31_38_37), =('Rule', EYE_52_75_6c_65_23_36_31_38_37)], [policy_ready, t('ex:r5', 'rdf:type', 'dpv:Process'), candidate('ex:r5', 'ex:research'), findall(EYE_52_23_36_31_38_37, permitted('ex:r5', EYE_52_23_36_31_38_37), []), findall(EYE_52_23_36_31_38_37, prohibited('ex:r5', EYE_52_23_36_31_38_37), []), findall(EYE_57_68_79_23_36_31_38_37, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_36_31_38_37), unmet('ex:r5', EYE_52_75_6c_65_23_36_31_38_37, EYE_57_68_79_23_36_31_38_37)), [unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])]).
step(t('ex:r5', 'rdf:type', 'dpv:Process'), rule(48), [=('P', 'ex:r5'), =('__anon0', 'ex:partnerBE'), =('__anon1', 'dpv:Use'), =('__anon2', 'ex:labResults'), =('__anon3', 'dpv:AcademicResearch'), =('__anon4', 'dpv:ConsentGiven'), =('__anon5', 'dpv:Encryption'), =('__anon6', 20270301)], [process('ex:r5', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Encryption', 20270301)]).
step(process('ex:r5', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Encryption', 20270301), fact(42), [], []).
step(candidate('ex:r5', 'ex:research'), rule(79), [=('P', 'ex:r5'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), addresses('ex:r5', 'ex:research')]).
step(addresses('ex:r5', 'ex:research'), rule(71), [=('P', 'ex:r5'), =('Rule', 'ex:research'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r5', 'ex:requestedBy', 'ex:partnerBE'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r5', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r5', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r5', 'ex:requestedBy', 'ex:partnerBE'), rule(49), [=('P', 'ex:r5'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:AcademicResearch'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Encryption'), =('__anon12', 20270301)], [process('ex:r5', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Encryption', 20270301)]).
step(t('ex:r5', 'dpv:hasProcessing', 'dpv:Use'), rule(50), [=('P', 'ex:r5'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:AcademicResearch'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Encryption'), =('__anon18', 20270301)], [process('ex:r5', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Encryption', 20270301)]).
step(t('ex:r5', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r5'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:AcademicResearch'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Encryption'), =('__anon24', 20270301)], [process('ex:r5', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Encryption', 20270301)]).
step(findall(EYE_52_23_36_31_38_37, permitted('ex:r5', EYE_52_23_36_31_38_37), []), collected, [], []).
step(findall(EYE_52_23_36_31_38_37, prohibited('ex:r5', EYE_52_23_36_31_38_37), []), collected, [], []).
step(findall(EYE_57_68_79_23_36_31_38_37, ','(t('ex:policy', 'odrl:permission', EYE_52_75_6c_65_23_36_31_38_37), unmet('ex:r5', EYE_52_75_6c_65_23_36_31_38_37, EYE_57_68_79_23_36_31_38_37)), [unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)]), collected, [], []).
step(assessment(in_force, 'ex:r6', deny_policy(prohibited_by('ex:noTransferUS')), basis(['ex:policy'])), rule(126), [=('R', in_force), =('P', 'ex:r6'), =('Reason', prohibited_by('ex:noTransferUS')), =('__anon65', own_audience_measurement), =('__anon66', first_visit)], [regime(in_force), session('ex:r6', own_audience_measurement, first_visit), policy_result('ex:r6', deny(prohibited_by('ex:noTransferUS')))]).
step(policy_result('ex:r6', deny(prohibited_by('ex:noTransferUS'))), rule(82), [=('P', 'ex:r6'), =('Rule', 'ex:noTransferUS')], [policy_ready, prohibited('ex:r6', 'ex:noTransferUS')]).
step(assessment(omnibus_proposal, 'ex:r2', deny_policy(not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])), basis(['ex:policy'])), rule(126), [=('R', omnibus_proposal), =('P', 'ex:r2'), =('Reason', not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])), =('__anon65', own_audience_measurement), =('__anon66', first_visit)], [regime(omnibus_proposal), session('ex:r2', own_audience_measurement, first_visit), policy_result('ex:r2', deny(not_permitted([unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment')])))]).
step(assessment(omnibus_proposal, 'ex:r3', deny_policy(prohibited_by('ex:noMarketing')), basis(['ex:policy'])), rule(126), [=('R', omnibus_proposal), =('P', 'ex:r3'), =('Reason', prohibited_by('ex:noMarketing')), =('__anon65', advertising), =('__anon66', browser_signal(refuse))], [regime(omnibus_proposal), session('ex:r3', advertising, browser_signal(refuse)), policy_result('ex:r3', deny(prohibited_by('ex:noMarketing')))]).
step(assessment(omnibus_proposal, 'ex:r4', deny_policy(not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])), basis(['ex:policy'])), rule(126), [=('R', omnibus_proposal), =('P', 'ex:r4'), =('Reason', not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])), =('__anon65', own_audience_measurement), =('__anon66', first_visit)], [regime(omnibus_proposal), session('ex:r4', own_audience_measurement, first_visit), policy_result('ex:r4', deny(not_permitted([unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')])))]).
step(assessment(omnibus_proposal, 'ex:r5', deny_policy(not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])), basis(['ex:policy'])), rule(126), [=('R', omnibus_proposal), =('P', 'ex:r5'), =('Reason', not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])), =('__anon65', requested_service), =('__anon66', first_visit)], [regime(omnibus_proposal), session('ex:r5', requested_service, first_visit), policy_result('ex:r5', deny(not_permitted([unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)])))]).
step(assessment(omnibus_proposal, 'ex:r6', deny_policy(prohibited_by('ex:noTransferUS')), basis(['ex:policy'])), rule(126), [=('R', omnibus_proposal), =('P', 'ex:r6'), =('Reason', prohibited_by('ex:noTransferUS')), =('__anon65', own_audience_measurement), =('__anon66', first_visit)], [regime(omnibus_proposal), session('ex:r6', own_audience_measurement, first_visit), policy_result('ex:r6', deny(prohibited_by('ex:noTransferUS')))]).
step(assessment(in_force, 'ex:r10', permit('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])), rule(127), [=('R', in_force), =('P', 'ex:r10'), =('Rule', 'ex:research'), =('Provision', 'ePrivacy Art. 5(3)'), =('Kind', requested_service), =('__anon67', first_visit)], [regime(in_force), policy_result('ex:r10', permit('ex:research')), session('ex:r10', requested_service, first_visit), consent(in_force, requested_service, not_needed, 'ePrivacy Art. 5(3)')]).
step(policy_result('ex:r10', permit('ex:research')), rule(81), [=('P', 'ex:r10'), =('Rule', 'ex:research'), =('R', EYE_52_23_31_32_32_36_36)], [policy_ready, permitted('ex:r10', 'ex:research'), findall(EYE_52_23_31_32_32_36_36, prohibited('ex:r10', EYE_52_23_31_32_32_36_36), [])]).
step(permitted('ex:r10', 'ex:research'), rule(77), [=('P', 'ex:r10'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), applies('ex:r10', 'ex:research')]).
step(applies('ex:r10', 'ex:research'), rule(76), [=('P', 'ex:r10'), =('Rule', 'ex:research'), =('Why', EYE_57_68_79_23_31_32_32_37_32)], [addresses('ex:r10', 'ex:research'), findall(EYE_57_68_79_23_31_32_32_37_32, unmet('ex:r10', 'ex:research', EYE_57_68_79_23_31_32_32_37_32), [])]).
step(addresses('ex:r10', 'ex:research'), rule(71), [=('P', 'ex:r10'), =('Rule', 'ex:research'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r10', 'ex:requestedBy', 'ex:partnerBE'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r10', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r10', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r10', 'ex:requestedBy', 'ex:partnerBE'), rule(49), [=('P', 'ex:r10'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:AcademicResearch'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r10', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r10', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(47), [], []).
step(t('ex:r10', 'dpv:hasProcessing', 'dpv:Use'), rule(50), [=('P', 'ex:r10'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:AcademicResearch'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r10', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r10', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r10'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:AcademicResearch'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r10', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(findall(EYE_57_68_79_23_31_32_32_37_32, unmet('ex:r10', 'ex:research', EYE_57_68_79_23_31_32_32_37_32), []), collected, [], []).
step(findall(EYE_52_23_31_32_32_36_36, prohibited('ex:r10', EYE_52_23_31_32_32_36_36), []), collected, [], []).
step(session('ex:r10', requested_service, first_visit), fact(95), [], []).
step(consent(in_force, requested_service, not_needed, 'ePrivacy Art. 5(3)'), fact(101), [], []).
step(assessment(omnibus_proposal, 'ex:r1', permit('ex:research'), basis(['ex:policy', 'GDPR Art. 88a(3)(c)'])), rule(127), [=('R', omnibus_proposal), =('P', 'ex:r1'), =('Rule', 'ex:research'), =('Provision', 'GDPR Art. 88a(3)(c)'), =('Kind', own_audience_measurement), =('__anon67', first_visit)], [regime(omnibus_proposal), policy_result('ex:r1', permit('ex:research')), session('ex:r1', own_audience_measurement, first_visit), consent(omnibus_proposal, own_audience_measurement, not_needed, 'GDPR Art. 88a(3)(c)')]).
step(policy_result('ex:r1', permit('ex:research')), rule(81), [=('P', 'ex:r1'), =('Rule', 'ex:research'), =('R', EYE_52_23_31_34_33_38_35)], [policy_ready, permitted('ex:r1', 'ex:research'), findall(EYE_52_23_31_34_33_38_35, prohibited('ex:r1', EYE_52_23_31_34_33_38_35), [])]).
step(permitted('ex:r1', 'ex:research'), rule(77), [=('P', 'ex:r1'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), applies('ex:r1', 'ex:research')]).
step(applies('ex:r1', 'ex:research'), rule(76), [=('P', 'ex:r1'), =('Rule', 'ex:research'), =('Why', EYE_57_68_79_23_31_34_33_39_31)], [addresses('ex:r1', 'ex:research'), findall(EYE_57_68_79_23_31_34_33_39_31, unmet('ex:r1', 'ex:research', EYE_57_68_79_23_31_34_33_39_31), [])]).
step(addresses('ex:r1', 'ex:research'), rule(71), [=('P', 'ex:r1'), =('Rule', 'ex:research'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r1', 'ex:requestedBy', 'ex:partnerBE'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r1', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r1', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r1', 'ex:requestedBy', 'ex:partnerBE'), rule(49), [=('P', 'ex:r1'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:AcademicResearch'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(38), [], []).
step(t('ex:r1', 'dpv:hasProcessing', 'dpv:Use'), rule(50), [=('P', 'ex:r1'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:AcademicResearch'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r1', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r1'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:AcademicResearch'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r1', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(findall(EYE_57_68_79_23_31_34_33_39_31, unmet('ex:r1', 'ex:research', EYE_57_68_79_23_31_34_33_39_31), []), collected, [], []).
step(findall(EYE_52_23_31_34_33_38_35, prohibited('ex:r1', EYE_52_23_31_34_33_38_35), []), collected, [], []).
step(session('ex:r1', own_audience_measurement, first_visit), fact(86), [], []).
step(consent(omnibus_proposal, own_audience_measurement, not_needed, 'GDPR Art. 88a(3)(c)'), fact(108), [], []).
step(assessment(omnibus_proposal, 'ex:r10', permit('ex:research'), basis(['ex:policy', 'GDPR Art. 88a(3)(b)'])), rule(127), [=('R', omnibus_proposal), =('P', 'ex:r10'), =('Rule', 'ex:research'), =('Provision', 'GDPR Art. 88a(3)(b)'), =('Kind', requested_service), =('__anon67', first_visit)], [regime(omnibus_proposal), policy_result('ex:r10', permit('ex:research')), session('ex:r10', requested_service, first_visit), consent(omnibus_proposal, requested_service, not_needed, 'GDPR Art. 88a(3)(b)')]).
step(consent(omnibus_proposal, requested_service, not_needed, 'GDPR Art. 88a(3)(b)'), fact(107), [], []).
step(assessment(in_force, 'ex:r1', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])), rule(128), [=('R', in_force), =('P', 'ex:r1'), =('Rule', 'ex:research'), =('Basis', ['ex:policy', 'ePrivacy Art. 5(3)']), =('Kind', own_audience_measurement), =('Before', first_visit), =('Provision', 'ePrivacy Art. 5(3)'), =('Next', 'ePrivacy Art. 5(3)')], [regime(in_force), policy_result('ex:r1', permit('ex:research')), session('ex:r1', own_audience_measurement, first_visit), consent(in_force, own_audience_measurement, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(no), first_visit, ask_for_consent, 'ePrivacy Art. 5(3)'), device_basis('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ex:policy', 'ePrivacy Art. 5(3)'])]).
step(consent(in_force, own_audience_measurement, needed, 'ePrivacy Art. 5(3)'), fact(102), [], []).
step(ask(in_force, media_service(no), first_visit, ask_for_consent, 'ePrivacy Art. 5(3)'), fact(111), [=('__anon57', media_service(no)), =('__anon58', first_visit)], []).
step(device_basis('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ex:policy', 'ePrivacy Art. 5(3)']), fact(130), [=('P', 'ePrivacy Art. 5(3)')], []).
step(assessment(in_force, 'ex:r7', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])), rule(128), [=('R', in_force), =('P', 'ex:r7'), =('Rule', 'ex:research'), =('Basis', ['ex:policy', 'ePrivacy Art. 5(3)']), =('Kind', advertising), =('Before', browser_signal(refuse)), =('Provision', 'ePrivacy Art. 5(3)'), =('Next', 'ePrivacy Art. 5(3)')], [regime(in_force), policy_result('ex:r7', permit('ex:research')), session('ex:r7', advertising, browser_signal(refuse)), consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(no), browser_signal(refuse), ask_for_consent, 'ePrivacy Art. 5(3)'), device_basis('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ex:policy', 'ePrivacy Art. 5(3)'])]).
step(policy_result('ex:r7', permit('ex:research')), rule(81), [=('P', 'ex:r7'), =('Rule', 'ex:research'), =('R', EYE_52_23_31_36_35_30_35)], [policy_ready, permitted('ex:r7', 'ex:research'), findall(EYE_52_23_31_36_35_30_35, prohibited('ex:r7', EYE_52_23_31_36_35_30_35), [])]).
step(permitted('ex:r7', 'ex:research'), rule(77), [=('P', 'ex:r7'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), applies('ex:r7', 'ex:research')]).
step(applies('ex:r7', 'ex:research'), rule(76), [=('P', 'ex:r7'), =('Rule', 'ex:research'), =('Why', EYE_57_68_79_23_31_36_35_31_31)], [addresses('ex:r7', 'ex:research'), findall(EYE_57_68_79_23_31_36_35_31_31, unmet('ex:r7', 'ex:research', EYE_57_68_79_23_31_36_35_31_31), [])]).
step(addresses('ex:r7', 'ex:research'), rule(71), [=('P', 'ex:r7'), =('Rule', 'ex:research'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r7', 'ex:requestedBy', 'ex:partnerBE'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r7', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r7', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r7', 'ex:requestedBy', 'ex:partnerBE'), rule(49), [=('P', 'ex:r7'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:AcademicResearch'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r7', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r7', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(44), [], []).
step(t('ex:r7', 'dpv:hasProcessing', 'dpv:Use'), rule(50), [=('P', 'ex:r7'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:AcademicResearch'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r7', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r7', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r7'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:AcademicResearch'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r7', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(findall(EYE_57_68_79_23_31_36_35_31_31, unmet('ex:r7', 'ex:research', EYE_57_68_79_23_31_36_35_31_31), []), collected, [], []).
step(findall(EYE_52_23_31_36_35_30_35, prohibited('ex:r7', EYE_52_23_31_36_35_30_35), []), collected, [], []).
step(session('ex:r7', advertising, browser_signal(refuse)), fact(92), [], []).
step(consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), fact(104), [], []).
step(ask(in_force, media_service(no), browser_signal(refuse), ask_for_consent, 'ePrivacy Art. 5(3)'), fact(111), [=('__anon57', media_service(no)), =('__anon58', browser_signal(refuse))], []).
step(assessment(in_force, 'ex:r8', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])), rule(128), [=('R', in_force), =('P', 'ex:r8'), =('Rule', 'ex:research'), =('Basis', ['ex:policy', 'ePrivacy Art. 5(3)']), =('Kind', advertising), =('Before', refused(completed_months(5))), =('Provision', 'ePrivacy Art. 5(3)'), =('Next', 'ePrivacy Art. 5(3)')], [regime(in_force), policy_result('ex:r8', permit('ex:research')), session('ex:r8', advertising, refused(completed_months(5))), consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(no), refused(completed_months(5)), ask_for_consent, 'ePrivacy Art. 5(3)'), device_basis('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ex:policy', 'ePrivacy Art. 5(3)'])]).
step(policy_result('ex:r8', permit('ex:research')), rule(81), [=('P', 'ex:r8'), =('Rule', 'ex:research'), =('R', EYE_52_23_31_36_35_30_35)], [policy_ready, permitted('ex:r8', 'ex:research'), findall(EYE_52_23_31_36_35_30_35, prohibited('ex:r8', EYE_52_23_31_36_35_30_35), [])]).
step(permitted('ex:r8', 'ex:research'), rule(77), [=('P', 'ex:r8'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), applies('ex:r8', 'ex:research')]).
step(applies('ex:r8', 'ex:research'), rule(76), [=('P', 'ex:r8'), =('Rule', 'ex:research'), =('Why', EYE_57_68_79_23_31_36_35_31_31)], [addresses('ex:r8', 'ex:research'), findall(EYE_57_68_79_23_31_36_35_31_31, unmet('ex:r8', 'ex:research', EYE_57_68_79_23_31_36_35_31_31), [])]).
step(addresses('ex:r8', 'ex:research'), rule(71), [=('P', 'ex:r8'), =('Rule', 'ex:research'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r8', 'ex:requestedBy', 'ex:partnerBE'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r8', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r8', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r8', 'ex:requestedBy', 'ex:partnerBE'), rule(49), [=('P', 'ex:r8'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:AcademicResearch'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r8', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r8', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(45), [], []).
step(t('ex:r8', 'dpv:hasProcessing', 'dpv:Use'), rule(50), [=('P', 'ex:r8'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:AcademicResearch'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r8', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r8', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r8'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:AcademicResearch'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r8', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(findall(EYE_57_68_79_23_31_36_35_31_31, unmet('ex:r8', 'ex:research', EYE_57_68_79_23_31_36_35_31_31), []), collected, [], []).
step(findall(EYE_52_23_31_36_35_30_35, prohibited('ex:r8', EYE_52_23_31_36_35_30_35), []), collected, [], []).
step(session('ex:r8', advertising, refused(completed_months(5))), fact(93), [], []).
step(ask(in_force, media_service(no), refused(completed_months(5)), ask_for_consent, 'ePrivacy Art. 5(3)'), fact(111), [=('__anon57', media_service(no)), =('__anon58', refused(completed_months(5)))], []).
step(assessment(in_force, 'ex:r9', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])), rule(128), [=('R', in_force), =('P', 'ex:r9'), =('Rule', 'ex:research'), =('Basis', ['ex:policy', 'ePrivacy Art. 5(3)']), =('Kind', advertising), =('Before', refused(completed_months(6))), =('Provision', 'ePrivacy Art. 5(3)'), =('Next', 'ePrivacy Art. 5(3)')], [regime(in_force), policy_result('ex:r9', permit('ex:research')), session('ex:r9', advertising, refused(completed_months(6))), consent(in_force, advertising, needed, 'ePrivacy Art. 5(3)'), ask(in_force, media_service(no), refused(completed_months(6)), ask_for_consent, 'ePrivacy Art. 5(3)'), device_basis('ePrivacy Art. 5(3)', 'ePrivacy Art. 5(3)', ['ex:policy', 'ePrivacy Art. 5(3)'])]).
step(policy_result('ex:r9', permit('ex:research')), rule(81), [=('P', 'ex:r9'), =('Rule', 'ex:research'), =('R', EYE_52_23_31_36_35_30_35)], [policy_ready, permitted('ex:r9', 'ex:research'), findall(EYE_52_23_31_36_35_30_35, prohibited('ex:r9', EYE_52_23_31_36_35_30_35), [])]).
step(permitted('ex:r9', 'ex:research'), rule(77), [=('P', 'ex:r9'), =('Rule', 'ex:research')], [t('ex:policy', 'odrl:permission', 'ex:research'), applies('ex:r9', 'ex:research')]).
step(applies('ex:r9', 'ex:research'), rule(76), [=('P', 'ex:r9'), =('Rule', 'ex:research'), =('Why', EYE_57_68_79_23_31_36_35_31_31)], [addresses('ex:r9', 'ex:research'), findall(EYE_57_68_79_23_31_36_35_31_31, unmet('ex:r9', 'ex:research', EYE_57_68_79_23_31_36_35_31_31), [])]).
step(addresses('ex:r9', 'ex:research'), rule(71), [=('P', 'ex:r9'), =('Rule', 'ex:research'), =('Who', 'ex:partnerBE'), =('Assignee', 'ex:consortium'), =('Processing', 'dpv:Use'), =('Action', 'odrl:use'), =('Data', 'ex:labResults')], [t('ex:r9', 'ex:requestedBy', 'ex:partnerBE'), t('ex:research', 'odrl:assignee', 'ex:consortium'), party('ex:partnerBE', 'ex:consortium'), t('ex:r9', 'dpv:hasProcessing', 'dpv:Use'), action('dpv:Use', 'odrl:use'), t('ex:research', 'odrl:action', 'odrl:use'), t('ex:r9', 'dpv:hasPersonalData', 'ex:labResults'), t('ex:research', 'odrl:target', 'ex:labResults')]).
step(t('ex:r9', 'ex:requestedBy', 'ex:partnerBE'), rule(49), [=('P', 'ex:r9'), =('Who', 'ex:partnerBE'), =('__anon7', 'dpv:Use'), =('__anon8', 'ex:labResults'), =('__anon9', 'dpv:AcademicResearch'), =('__anon10', 'dpv:ConsentGiven'), =('__anon11', 'dpv:Pseudonymisation'), =('__anon12', 20261115)], [process('ex:r9', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(process('ex:r9', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115), fact(46), [], []).
step(t('ex:r9', 'dpv:hasProcessing', 'dpv:Use'), rule(50), [=('P', 'ex:r9'), =('X', 'dpv:Use'), =('__anon13', 'ex:partnerBE'), =('__anon14', 'ex:labResults'), =('__anon15', 'dpv:AcademicResearch'), =('__anon16', 'dpv:ConsentGiven'), =('__anon17', 'dpv:Pseudonymisation'), =('__anon18', 20261115)], [process('ex:r9', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(t('ex:r9', 'dpv:hasPersonalData', 'ex:labResults'), rule(51), [=('P', 'ex:r9'), =('X', 'ex:labResults'), =('__anon19', 'ex:partnerBE'), =('__anon20', 'dpv:Use'), =('__anon21', 'dpv:AcademicResearch'), =('__anon22', 'dpv:ConsentGiven'), =('__anon23', 'dpv:Pseudonymisation'), =('__anon24', 20261115)], [process('ex:r9', 'ex:partnerBE', 'dpv:Use', 'ex:labResults', 'dpv:AcademicResearch', 'dpv:ConsentGiven', 'dpv:Pseudonymisation', 20261115)]).
step(findall(EYE_57_68_79_23_31_36_35_31_31, unmet('ex:r9', 'ex:research', EYE_57_68_79_23_31_36_35_31_31), []), collected, [], []).
step(findall(EYE_52_23_31_36_35_30_35, prohibited('ex:r9', EYE_52_23_31_36_35_30_35), []), collected, [], []).
step(session('ex:r9', advertising, refused(completed_months(6))), fact(94), [], []).
step(ask(in_force, media_service(no), refused(completed_months(6)), ask_for_consent, 'ePrivacy Art. 5(3)'), fact(111), [=('__anon57', media_service(no)), =('__anon58', refused(completed_months(6)))], []).
step(assessment(omnibus_proposal, 'ex:r9', await_device_consent('ex:research'), basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])), rule(128), [=('R', omnibus_proposal), =('P', 'ex:r9'), =('Rule', 'ex:research'), =('Basis', ['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']), =('Kind', advertising), =('Before', refused(completed_months(6))), =('Provision', 'GDPR Art. 88a(1)'), =('Next', 'GDPR Art. 88a(4)(c)')], [regime(omnibus_proposal), policy_result('ex:r9', permit('ex:research')), session('ex:r9', advertising, refused(completed_months(6))), consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), ask(omnibus_proposal, media_service(no), refused(completed_months(6)), ask_for_consent, 'GDPR Art. 88a(4)(c)'), device_basis('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)', ['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])]).
step(consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), fact(110), [], []).
step(ask(omnibus_proposal, media_service(no), refused(completed_months(6)), ask_for_consent, 'GDPR Art. 88a(4)(c)'), rule(116), [=('__anon61', media_service(no)), =('M', 6), =('Min', 6)], [integer(6), >=(6, 0), refusal_pause(months(6)), >=(6, 6)]).
step(integer(6), builtin, [], []).
step(>=(6, 0), builtin, [], []).
step(refusal_pause(months(6)), fact(98), [], []).
step(>=(6, 6), builtin, [], []).
step(device_basis('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)', ['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']), rule(131), [=('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88a(4)(c)')], [\==('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)')]).
step(\==('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'), builtin, [], []).
step(assessment(omnibus_proposal, 'ex:r7', deny_device(refused_by_signal), basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])), rule(129), [=('R', omnibus_proposal), =('P', 'ex:r7'), =('Reason', refused_by_signal), =('Basis', ['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)']), =('__anon68', 'ex:research'), =('Kind', advertising), =('Before', browser_signal(refuse)), =('Provision', 'GDPR Art. 88a(1)'), =('Next', 'GDPR Art. 88b(1)-(2)')], [regime(omnibus_proposal), policy_result('ex:r7', permit('ex:research')), session('ex:r7', advertising, browser_signal(refuse)), consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), ask(omnibus_proposal, media_service(no), browser_signal(refuse), refused_by_signal, 'GDPR Art. 88b(1)-(2)'), \==(refused_by_signal, ask_for_consent), device_basis('GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)', ['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])]).
step(ask(omnibus_proposal, media_service(no), browser_signal(refuse), refused_by_signal, 'GDPR Art. 88b(1)-(2)'), fact(113), [], []).
step(\==(refused_by_signal, ask_for_consent), builtin, [], []).
step(device_basis('GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)', ['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)']), rule(131), [=('P', 'GDPR Art. 88a(1)'), =('Q', 'GDPR Art. 88b(1)-(2)')], [\==('GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)')]).
step(\==('GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'), builtin, [], []).
step(assessment(omnibus_proposal, 'ex:r8', deny_device(do_not_ask_again), basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])), rule(129), [=('R', omnibus_proposal), =('P', 'ex:r8'), =('Reason', do_not_ask_again), =('Basis', ['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']), =('__anon68', 'ex:research'), =('Kind', advertising), =('Before', refused(completed_months(5))), =('Provision', 'GDPR Art. 88a(1)'), =('Next', 'GDPR Art. 88a(4)(c)')], [regime(omnibus_proposal), policy_result('ex:r8', permit('ex:research')), session('ex:r8', advertising, refused(completed_months(5))), consent(omnibus_proposal, advertising, needed, 'GDPR Art. 88a(1)'), ask(omnibus_proposal, media_service(no), refused(completed_months(5)), do_not_ask_again, 'GDPR Art. 88a(4)(c)'), \==(do_not_ask_again, ask_for_consent), device_basis('GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)', ['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])]).
step(ask(omnibus_proposal, media_service(no), refused(completed_months(5)), do_not_ask_again, 'GDPR Art. 88a(4)(c)'), rule(115), [=('__anon60', media_service(no)), =('M', 5), =('Min', 6)], [integer(5), >=(5, 0), refusal_pause(months(6)), <(5, 6)]).
step(integer(5), builtin, [], []).
step(>=(5, 0), builtin, [], []).
step(<(5, 6), builtin, [], []).
step(\==(do_not_ask_again, ask_for_consent), builtin, [], []).
step(planned_duty(in_force, 'ex:r10', 'odrl:delete', within_days(90)), rule(133), [=('R', in_force), =('P', 'ex:r10'), =('Action', 'odrl:delete'), =('Days', 90), =('Rule', 'ex:research'), =('__anon71', basis(['ex:policy', 'ePrivacy Art. 5(3)'])), =('Duty', 'ex:deletion')], [assessment(in_force, 'ex:r10', permit('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])), t('ex:research', 'odrl:duty', 'ex:deletion'), t('ex:deletion', 'odrl:action', 'odrl:delete'), t('ex:deletion', 'ex:withinDays', 90)]).
step(t('ex:research', 'odrl:duty', 'ex:deletion'), fact(20), [], []).
step(t('ex:deletion', 'odrl:action', 'odrl:delete'), fact(21), [], []).
step(t('ex:deletion', 'ex:withinDays', 90), fact(22), [], []).
step(planned_duty(omnibus_proposal, 'ex:r1', 'odrl:delete', within_days(90)), rule(133), [=('R', omnibus_proposal), =('P', 'ex:r1'), =('Action', 'odrl:delete'), =('Days', 90), =('Rule', 'ex:research'), =('__anon71', basis(['ex:policy', 'GDPR Art. 88a(3)(c)'])), =('Duty', 'ex:deletion')], [assessment(omnibus_proposal, 'ex:r1', permit('ex:research'), basis(['ex:policy', 'GDPR Art. 88a(3)(c)'])), t('ex:research', 'odrl:duty', 'ex:deletion'), t('ex:deletion', 'odrl:action', 'odrl:delete'), t('ex:deletion', 'ex:withinDays', 90)]).
step(planned_duty(omnibus_proposal, 'ex:r10', 'odrl:delete', within_days(90)), rule(133), [=('R', omnibus_proposal), =('P', 'ex:r10'), =('Action', 'odrl:delete'), =('Days', 90), =('Rule', 'ex:research'), =('__anon71', basis(['ex:policy', 'GDPR Art. 88a(3)(b)'])), =('Duty', 'ex:deletion')], [assessment(omnibus_proposal, 'ex:r10', permit('ex:research'), basis(['ex:policy', 'GDPR Art. 88a(3)(b)'])), t('ex:research', 'odrl:duty', 'ex:deletion'), t('ex:deletion', 'odrl:action', 'odrl:delete'), t('ex:deletion', 'ex:withinDays', 90)]).
step(changed(session('ex:r1'), from(await_device_consent('ex:research')), to(permit('ex:research'))), rule(138), [=('P', 'ex:r1'), =('Old', await_device_consent('ex:research')), =('New', permit('ex:research')), =('__anon73', basis(['ex:policy', 'ePrivacy Art. 5(3)'])), =('__anon74', basis(['ex:policy', 'GDPR Art. 88a(3)(c)']))], [assessment(in_force, 'ex:r1', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])), assessment(omnibus_proposal, 'ex:r1', permit('ex:research'), basis(['ex:policy', 'GDPR Art. 88a(3)(c)'])), \==(await_device_consent('ex:research'), permit('ex:research'))]).
step(\==(await_device_consent('ex:research'), permit('ex:research')), builtin, [], []).
step(changed(session('ex:r7'), from(await_device_consent('ex:research')), to(deny_device(refused_by_signal))), rule(138), [=('P', 'ex:r7'), =('Old', await_device_consent('ex:research')), =('New', deny_device(refused_by_signal)), =('__anon73', basis(['ex:policy', 'ePrivacy Art. 5(3)'])), =('__anon74', basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)']))], [assessment(in_force, 'ex:r7', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])), assessment(omnibus_proposal, 'ex:r7', deny_device(refused_by_signal), basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88b(1)-(2)'])), \==(await_device_consent('ex:research'), deny_device(refused_by_signal))]).
step(\==(await_device_consent('ex:research'), deny_device(refused_by_signal)), builtin, [], []).
step(changed(session('ex:r8'), from(await_device_consent('ex:research')), to(deny_device(do_not_ask_again))), rule(138), [=('P', 'ex:r8'), =('Old', await_device_consent('ex:research')), =('New', deny_device(do_not_ask_again)), =('__anon73', basis(['ex:policy', 'ePrivacy Art. 5(3)'])), =('__anon74', basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)']))], [assessment(in_force, 'ex:r8', await_device_consent('ex:research'), basis(['ex:policy', 'ePrivacy Art. 5(3)'])), assessment(omnibus_proposal, 'ex:r8', deny_device(do_not_ask_again), basis(['ex:policy', 'GDPR Art. 88a(1)', 'GDPR Art. 88a(4)(c)'])), \==(await_device_consent('ex:research'), deny_device(do_not_ask_again))]).
step(\==(await_device_consent('ex:research'), deny_device(do_not_ask_again)), builtin, [], []).
